export type IslandBoardProfileId = 'spark40_ring';

export interface IslandBoardProfile {
  id: IslandBoardProfileId;
  tileCount: number;
  /**
   * Visual-only positioning hints for the 5 landmark HUD buttons rendered in
   * orbit around the board. These indices pick which tile each landmark button
   * is visually anchored above — they do NOT affect gameplay on the ring.
   *
   * The player token never "lands on" a landmark; landmarks are accessed by
   * tapping the HUD button. The underlying ring remains 40 pure movement
   * tiles generated by the normal tile-map generator.
   */
  landmarkOrbitAnchors: [number, number, number, number, number];
}

const BOARD_PROFILES: Record<IslandBoardProfileId, IslandBoardProfile> = {
  spark40_ring: {
    id: 'spark40_ring',
    tileCount: 40,
    // Anchors at quarters (0, 10, 20, 30) + boss anchor (39).
    landmarkOrbitAnchors: [0, 10, 20, 30, 39],
  },
};

export const DEFAULT_ISLAND_BOARD_PROFILE_ID: IslandBoardProfileId = 'spark40_ring';

export function resolveIslandBoardProfile(profileId: IslandBoardProfileId = DEFAULT_ISLAND_BOARD_PROFILE_ID): IslandBoardProfile {
  return BOARD_PROFILES[profileId] ?? BOARD_PROFILES[DEFAULT_ISLAND_BOARD_PROFILE_ID];
}
