const MAX_ISLANDS = 120;

const ISLAND_NAMES: readonly string[] = [
  // 1–24: Awakening / Calm & Nature
  'First Light Shore',
  'Pebble Bay',
  'Coconut Cove',
  'Driftwood Isle',
  'Crown of Tides',
  'Turtle Beach',
  'Coral Garden',
  'Whispering Palms',
  'Seaglass Shore',
  'Lagoon Haven',
  'Shell Harbor',
  'Festival of Waves',
  'Bluewater Bay',
  'Mango Isle',
  'Starfish Shore',
  'Windy Coast',
  'Hidden Lagoon',
  'Shrine of Sands',
  'Bamboo Bay',
  'Golden Sands',
  'Horizon Isle',
  'Calmwater Key',
  'Sunset Cove',
  'Dawnbreaker Isle',
  // 25–48: Growth / Jungle & Life
  'Emerald Jungle',
  'Vinefall Isle',
  'Rainforest Rise',
  'Wildroot Valley',
  'Bloom Haven',
  'Crown of Vines',
  'Petal Plains',
  'Mistleaf Isle',
  'Fernwood Retreat',
  'Orchid Oasis',
  'Canopy Crown',
  'Festival of Bloom',
  'Riverbend Isle',
  'Greenheart Grove',
  'Nectar Falls',
  'Lotus Lagoon',
  'Sunpetal Isle',
  'Shrine of Growth',
  'Verdant Cliffs',
  'Ivy Spiral',
  'LifeBloom Isle',
  'Hidden Canopy',
  'Jungle Crown',
  'Wildcore Isle',
  // 49–72: Power / Elements & Intensity
  'Ember Island',
  'Ashfall Ridge',
  'Molten Core',
  'Lava Loop',
  'Stormbreaker Isle',
  'Crown of Flames',
  'Thunder Peak',
  'Lightning Bay',
  'Cyclone Coast',
  'Tempest Harbor',
  'Frostbite Isle',
  'Festival of Storms',
  'Glacier Gate',
  'Icewind Harbor',
  'Blizzard Reach',
  'Crystal Caverns',
  'Obsidian Isle',
  'Shrine of Balance',
  'Magma Forge',
  'Tempest Rift',
  'Firestorm Ridge',
  'Polar Crown',
  'Elemental Rift',
  'Equilibrium Isle',
  // 73–96: Mastery / Fantasy & Identity
  'Dragon’s Rest',
  'Knightfall Keep',
  'Mystic Harbor',
  'Wizard’s Isle',
  'Arcane Bay',
  'Crown of Magic',
  'Crystal Kingdom',
  'Enchanted Shores',
  'Rune Island',
  'Sorcery Sands',
  'Crowned Isle',
  'Festival of Legends',
  'Moonlight Kingdom',
  'Phoenix Nest',
  'Shadow Realm',
  'Golden Throne Isle',
  'Elven Coast',
  'Shrine of Heroes',
  'Dwarven Depths',
  'Spellbound Bay',
  'Royal Garden Isle',
  'Hero’s Landing',
  'Legend’s Rise',
  'Mythic Horizon',
  // 97–110: Futuristic / Tech Shift
  'Neon Circuit Isle',
  'Cyber Coast',
  'Quantum Bay',
  'Data Stream Island',
  'AI Nexus',
  'Crown of Code',
  'Hologram Harbor',
  'Pixel Plains',
  'Codebase Island',
  'Digital Dream Isle',
  'Server Core',
  'Festival of Signals',
  'Nano Island',
  'Synapse Isle',
  // 111–120: Transcendence / Cosmic Endgame
  'Starfall Island',
  'Cosmic Drift',
  'Nebula Shores',
  'Galaxy Gate',
  'Lunar Haven',
  'Crown of Infinity',
  'Astral Plains',
  'Voidwalker Isle',
  'Ascension Isle',
  'Final Horizon',
] as const;

export function getIslandDisplayName(islandNumber: number): string {
  const safeIsland = Number.isFinite(islandNumber)
    ? Math.min(MAX_ISLANDS, Math.max(1, Math.floor(islandNumber)))
    : 1;
  return ISLAND_NAMES[safeIsland - 1] ?? `Island ${safeIsland}`;
}
