import type { IslandNarrativeDefinition } from '../islandNarrativeTypes';

export const island001NarrativeDefinition = {
  version: 1,
  islandNumber: 1,
  islandName: 'Luma Isle',
  civilizationName: 'The Lumin',
  characters: [
    { id: 'miri', displayName: 'Miri', role: 'Local routekeeper and first-contact guide.' },
    { id: 'sava', displayName: 'Elder Sava', role: 'Memory keeper and former dragon-route engineer.' },
    { id: 'poko', displayName: 'Poko', role: 'Hatchery tinkerer and warm supporting citizen.' },
    { id: 'ivo', displayName: 'Captain Ivo', role: 'Compass Expedition voice.' },
    { id: 'noctyra', displayName: 'Noctyra', role: 'Black Crystal Dragon and guardian of Luma Isle.' },
  ],
  beats: [
    {
      id: 'I001-B02',
      trigger: { kind: 'island_entered', islandNumber: 1 },
      surface: 'story_reader',
      priority: 'major',
      repeatPolicy: 'once',
      episodePath: '/islands/001/story/arrival/manifest.json',
    },
    {
      id: 'I001-B03',
      trigger: { kind: 'arrival_closed', islandNumber: 1 },
      speakerId: 'miri',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Start small. Help us wake one gentle place.',
    },
    {
      id: 'I001-B04',
      trigger: { kind: 'stop_opened', islandNumber: 1, stopId: 'hatchery' },
      speakerId: 'poko',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'The Hatchery is quiet, not gone. Help me wake one cradle.',
    },
    {
      id: 'I001-B24',
      trigger: { kind: 'landmark_level_completed', islandNumber: 1, stopId: 'hatchery', level: 1 },
      speakerId: 'miri',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'The island noticed.',
    },
    {
      id: 'I001-B26',
      trigger: { kind: 'boss_eligible', islandNumber: 1 },
      speakerId: 'sava',
      surface: 'dialogue_sheet',
      priority: 'major',
      repeatPolicy: 'once',
      text: 'The five lights are speaking again. Now we ask, not attack.',
      secondaryText: 'Aim for the crystal around her, not the heart inside it.',
    },
    {
      id: 'I001-B29',
      trigger: { kind: 'boss_resolved', islandNumber: 1 },
      surface: 'story_reader',
      priority: 'major',
      repeatPolicy: 'once',
      episodePath: '/islands/001/story/resolution/manifest.json',
    },
    {
      id: 'I001-B30',
      trigger: { kind: 'island_clear_travel_ready', islandNumber: 1 },
      speakerId: 'miri',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'The route is open because we opened it together.',
      displayCtaText: 'Follow the restored route',
    },
  ],
} satisfies IslandNarrativeDefinition;
