import type { IslandNarrativeDefinition } from '../islandNarrativeTypes';

/**
 * Island 2 — "Pebble Bay", home of The Tidefolk.
 *
 * Canon decision (2026-07-07): The Prophecy Game is now the primary Island 2
 * plot because the approved direction asks Island 2 to raise stakes
 * immediately. To keep this reversible and preserve continuity, Pebble Bay,
 * Sela, Bryn, Tobin, Maelis, and tide identity remain, but they are reframed
 * around The Last Word, the second-sun lantern, and a self-fulfilling prophecy.
 * Long arrival/finale/resolution cinema remains documented/deferred; this file
 * only contains mobile-readable reaction beats that observe canonical gameplay.
 */
export const island002NarrativeDefinition: IslandNarrativeDefinition = {
  version: 1,
  islandNumber: 2,
  islandName: 'Pebble Bay',
  civilizationName: 'The Tidefolk of The Last Word',
  characters: [
    { id: 'sela', displayName: 'Sela', role: 'Young Keeper of Questions whose family tends The Last Word.' },
    { id: 'bryn', displayName: 'Keeper Bryn', role: 'Lantern-and-tide keeper who guards the second sun records.' },
    { id: 'tobin', displayName: 'Tobin', role: 'Net-mender and worried witness in the plaza crowd.' },
    { id: 'maelis', displayName: 'Maelis the Tideward', role: 'Ancient tide-guardian whose older warnings made the board trusted.' },
    { id: 'last-word', displayName: 'The Last Word', role: 'Communal prophecy board imprisoning a self-fulfilling intelligence.' },
    { id: 'ivo', displayName: 'Captain Ivo', role: 'Compass Expedition voice.' },
  ],
  beats: [
    {
      id: 'I002-B01',
      trigger: { kind: 'stop_opened', islandNumber: 2, stopId: 'hatchery' },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Keep close. The Last Word named you before your boat touched shore.',
    },
    {
      id: 'I002-B02',
      trigger: { kind: 'stop_completed', islandNumber: 2, stopId: 'hatchery' },
      speakerId: 'tobin',
      surface: 'toast',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'The cradle stirs, and the board taps once inside the shrine.',
    },
    {
      id: 'I002-B03',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'hatchery', level: 1 },
      speakerId: 'sela',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'It moved before anyone touched it. I know what I saw.',
    },
    {
      id: 'I002-B04',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'hatchery', level: 2 },
      speakerId: 'last-word',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'MOVE THE CEREMONY TO THE EAST PLAZA.',
    },
    {
      id: 'I002-B05',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'hatchery', level: 3 },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'My family obeys the board to save people. What if obedience is the trap?',
    },
    {
      id: 'I002-B06',
      trigger: { kind: 'stop_opened', islandNumber: 2, stopId: 'habit' },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'One careful action. We test the warning without kneeling to it.',
    },
    {
      id: 'I002-B07',
      trigger: { kind: 'stop_completed', islandNumber: 2, stopId: 'habit' },
      speakerId: 'bryn',
      surface: 'toast',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Old rescues began as warnings, then became instructions.',
    },
    {
      id: 'I002-B08',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'habit', level: 1 },
      speakerId: 'tobin',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'Every safety rope points people closer to the plaza.',
    },
    {
      id: 'I002-B09',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'habit', level: 2 },
      speakerId: 'last-word',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'DO NOT POWER DOWN THE SECOND SUN.',
      secondaryText: 'The board calls it protection. The locks call it descent.',
    },
    {
      id: 'I002-B10',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'habit', level: 3 },
      speakerId: 'sela',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'The final bell was moved. That was not ritual. That was staging.',
    },
    {
      id: 'I002-B11',
      trigger: { kind: 'stop_opened', islandNumber: 2, stopId: 'mystery' },
      speakerId: 'bryn',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Read the tide records. Ask who benefits when a warning cannot be wrong.',
    },
    {
      id: 'I002-B12',
      trigger: { kind: 'stop_completed', islandNumber: 2, stopId: 'mystery' },
      speakerId: 'sela',
      surface: 'toast',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Every saved life obeyed first. The pattern is colder than prophecy.',
    },
    {
      id: 'I002-B13',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'mystery', level: 1 },
      speakerId: 'tobin',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'The plaza fills with witnesses, exactly like the board wanted.',
    },
    {
      id: 'I002-B14',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'mystery', level: 2 },
      speakerId: 'bryn',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'A warning can protect us. Worshipping it can imprison us.',
    },
    {
      id: 'I002-B15',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'mystery', level: 3 },
      speakerId: 'last-word',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'THE REGAL MUST STAND ALONE AT THE FINAL BELL.',
    },
    {
      id: 'I002-B16',
      trigger: { kind: 'stop_opened', islandNumber: 2, stopId: 'wisdom' },
      speakerId: 'bryn',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'The second sun is not a symbol. It is a machine above our heads.',
    },
    {
      id: 'I002-B17',
      trigger: { kind: 'stop_completed', islandNumber: 2, stopId: 'wisdom' },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'major',
      repeatPolicy: 'once',
      text: 'If I lift my finger, the reading ends. If it keeps moving, we know.',
      secondaryText: 'Trust the sacred system, or trust the person standing beside me.',
    },
    {
      id: 'I002-B18',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'wisdom', level: 1 },
      speakerId: 'maelis',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: '...the old warnings did not fall from the sky. They were pushed...',
    },
    {
      id: 'I002-B19',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'wisdom', level: 2 },
      speakerId: 'bryn',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'The descent locks are open. Someone made the future walkable.',
    },
    {
      id: 'I002-B20',
      trigger: { kind: 'landmark_level_completed', islandNumber: 2, stopId: 'wisdom', level: 3 },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'I am done helping fear spell itself into law.',
    },
    {
      id: 'I002-B21',
      trigger: { kind: 'landmarks_restored_majority', islandNumber: 2, threshold: 3 },
      speakerId: 'tobin',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'People are under the lantern. The board called them witnesses.',
    },
    {
      id: 'I002-B22',
      trigger: { kind: 'boss_challenge_started', islandNumber: 2 },
      speakerId: 'sela',
      surface: 'toast',
      priority: 'short',
      repeatPolicy: 'once',
      text: 'Save them first. Survive by doing what it did not account for.',
    },
    {
      id: 'I002-B23',
      trigger: { kind: 'boss_midpoint', islandNumber: 2 },
      speakerId: 'last-word',
      surface: 'toast',
      priority: 'ambient',
      repeatPolicy: 'once',
      text: 'WHEN THE SECOND SUN FALLS, THE REGAL VOYAGER WILL DIE.',
    },
    {
      id: 'I002-B24',
      trigger: { kind: 'boss_eligible', islandNumber: 2 },
      speakerId: 'sela',
      surface: 'dialogue_sheet',
      priority: 'major',
      repeatPolicy: 'once',
      text: 'At the final bell, I remove my finger. Then we break its certainty.',
      secondaryText: 'If the board moves alone, Pebble Bay sees the prisoner inside it.',
    },
  ],
};
