import { claimFirstSessionCreaturePackReward } from '../islandRunFirstSessionCreaturePackAction';
import { claimFullWelcomePack } from '../islandRunWelcomePackFullClaimAction';
import { WELCOME_PACK_CARD_COUNT } from '../islandRunWelcomePackClaimAction';
import {
  WELCOME_PACK_BUNDLE_DICE,
  WELCOME_PACK_BUNDLE_ESSENCE,
  WELCOME_PACK_BUNDLE_EVENT_TICKETS,
} from '../islandRunWelcomePackRewardBundleAction';
import { __resetIslandRunActionMutexesForTests } from '../islandRunActionMutex';
import {
  readIslandRunGameStateRecord,
  resetIslandRunRuntimeCommitCoordinatorForTests,
  writeIslandRunGameStateRecord,
  type IslandRunGameStateRecord,
} from '../islandRunGameStateStore';
import { __resetIslandRunStateStoreForTests, refreshIslandRunStateFromLocal } from '../islandRunStateStore';
import { assertEqual, createMemoryStorage, installWindowWithStorage, type TestCase } from './testHarness';

const USER_ID = 'welcome-pack-full-claim-action-test-user';
const makeSession = () => ({ user: { id: USER_ID, user_metadata: {} } } as unknown as import('@supabase/supabase-js').Session);
const reset = () => { resetIslandRunRuntimeCommitCoordinatorForTests(); __resetIslandRunActionMutexesForTests(); __resetIslandRunStateStoreForTests(); installWindowWithStorage(createMemoryStorage()); };
const seed = async (overrides: Partial<IslandRunGameStateRecord>) => { const s = makeSession(); const base = readIslandRunGameStateRecord(s); await writeIslandRunGameStateRecord({ session: s, client: null, record: { ...base, ...overrides } }); refreshIslandRunStateFromLocal(s); };
const totalCopies = (record: IslandRunGameStateRecord) => record.creatureCollection.reduce((sum, entry) => sum + entry.copies, 0);

export const islandRunWelcomePackFullClaimActionTests: TestCase[] = [
  { name: 'fresh state claims cards and reward bundle with combined payloads', run: async () => { reset(); await seed({ welcomePackClaimed: false, welcomePackRewardBundleClaimed: false, creatureCollection: [], dicePool: 10, essence: 5, activeTimedEvent: { eventId: 'feeding_frenzy:1', eventType: 'feeding_frenzy', startedAtMs: 0, expiresAtMs: Date.now() + 999999, version: 1 }, minigameTicketsByEvent: {} }); const result = await claimFullWelcomePack({ session: makeSession(), client: null }); const persisted = readIslandRunGameStateRecord(makeSession()); assertEqual(result.status, 'claimed', 'overall should be claimed'); assertEqual(result.cards.revealPayload?.cards.length, WELCOME_PACK_CARD_COUNT, 'cards payload present'); assertEqual(result.bundle.granted.dice, WELCOME_PACK_BUNDLE_DICE, 'dice payload present'); assertEqual(result.bundle.granted.essence, WELCOME_PACK_BUNDLE_ESSENCE, 'essence payload present'); assertEqual(result.bundle.granted.eventTickets, WELCOME_PACK_BUNDLE_EVENT_TICKETS, 'event tickets payload present'); assertEqual(totalCopies(persisted), WELCOME_PACK_CARD_COUNT, 'exactly five cards granted'); assertEqual(persisted.dicePool, 10 + WELCOME_PACK_BUNDLE_DICE, 'dice applied once'); assertEqual(persisted.essence, 5 + WELCOME_PACK_BUNDLE_ESSENCE, 'essence applied once'); } },
  { name: 'repeat full claim call is idempotent with no duplicate rewards', run: async () => { reset(); await seed({ welcomePackClaimed: false, welcomePackRewardBundleClaimed: false, creatureCollection: [], dicePool: 3, essence: 7, minigameTicketsByEvent: {} }); const first = await claimFullWelcomePack({ session: makeSession(), client: null }); const second = await claimFullWelcomePack({ session: makeSession(), client: null }); const persisted = readIslandRunGameStateRecord(makeSession()); assertEqual(first.status === 'already_claimed', false, 'first should not be already_claimed'); assertEqual(second.status, 'already_claimed', 'second should be already_claimed'); assertEqual(totalCopies(persisted), WELCOME_PACK_CARD_COUNT, 'cards should not duplicate'); assertEqual(persisted.dicePool, 3 + WELCOME_PACK_BUNDLE_DICE, 'dice should not duplicate'); assertEqual(persisted.essence, 7 + WELCOME_PACK_BUNDLE_ESSENCE, 'essence should not duplicate'); } },
  { name: 'partial state cards already claimed grants only reward bundle', run: async () => { reset(); await seed({ welcomePackClaimed: true, welcomePackRewardBundleClaimed: false, creatureCollection: [], dicePool: 1, essence: 2, minigameTicketsByEvent: {} }); const result = await claimFullWelcomePack({ session: makeSession(), client: null }); const persisted = readIslandRunGameStateRecord(makeSession()); assertEqual(result.status, 'partially_claimed', 'overall should be partial'); assertEqual(result.cards.status, 'already_claimed', 'cards should remain already claimed'); assertEqual(result.bundle.status === 'already_claimed', false, 'bundle should claim'); assertEqual(totalCopies(persisted), 0, 'no new cards should be granted'); assertEqual(persisted.dicePool, 1 + WELCOME_PACK_BUNDLE_DICE, 'dice grant should apply'); assertEqual(persisted.essence, 2 + WELCOME_PACK_BUNDLE_ESSENCE, 'essence grant should apply'); } },
  { name: 'partial state rewards already claimed grants only cards', run: async () => { reset(); await seed({ welcomePackClaimed: false, welcomePackRewardBundleClaimed: true, creatureCollection: [], dicePool: 9, essence: 11, minigameTicketsByEvent: {} }); const result = await claimFullWelcomePack({ session: makeSession(), client: null }); const persisted = readIslandRunGameStateRecord(makeSession()); assertEqual(result.status, 'partially_claimed', 'overall should be partial'); assertEqual(result.cards.status, 'claimed', 'cards should claim'); assertEqual(result.bundle.status, 'already_claimed', 'bundle should stay already claimed'); assertEqual(totalCopies(persisted), WELCOME_PACK_CARD_COUNT, 'cards should grant once'); assertEqual(persisted.dicePool, 9, 'dice should not change'); assertEqual(persisted.essence, 11, 'essence should not change'); } },
  { name: 'no active event fallback is surfaced clearly', run: async () => { reset(); await seed({ welcomePackClaimed: false, welcomePackRewardBundleClaimed: false, activeTimedEvent: null, minigameTicketsByEvent: {} }); const result = await claimFullWelcomePack({ session: makeSession(), client: null }); assertEqual(result.bundle.status, 'claimed_without_active_event', 'bundle should report fallback status'); assertEqual(result.bundle.granted.eventTickets, 0, 'no tickets should be granted'); assertEqual(result.status, 'claimed', 'overall still claimed when both sub-actions claimed'); } },
  { name: 'first-session creature pack behavior remains unchanged after full welcome pack helper', run: async () => { reset(); await seed({ runtimeVersion: 0, currentIslandNumber: 1, cycleIndex: 0, dicePool: 4, firstSessionTutorialState: 'first_creature_pack_available', creatureCollection: [], welcomePackClaimed: false, welcomePackRewardBundleClaimed: false }); const result = await claimFirstSessionCreaturePackReward({ session: makeSession(), client: null, nowMs: 7777 }); const persisted = readIslandRunGameStateRecord(makeSession()); assertEqual(result.status, 'claimed', 'first-session creature pack should still claim successfully'); assertEqual(persisted.dicePool, 104, 'first-session pack should still grant +100 dice'); } },
];
