import { creatureCatalogTests } from './creatureCatalog.test';
import { creatureCollectionServiceTests } from './creatureCollectionService.test';
import { creatureTreatInventoryServiceTests } from './creatureTreatInventoryService.test';
import { creatureFitEngineTests } from './creatureFitEngine.test';
import { companionRegenModifierTests } from './companionRegenModifier.test';
import { companionFeastGameTests } from './companionFeastGame.test';
import { minigameHudContractTests } from './minigameHudContract.test';
import { minigameJuiceTests } from './minigameJuice.test';
import { fortuneEngineGameTests } from './fortuneEngineGame.test';
import { fortuneEngineProgressionTests } from './fortuneEngineProgression.test';
import { fortuneEngineEconomyModelTests } from './fortuneEngineEconomyModel.test';
import { fortuneEngineStateActionsTests } from './fortuneEngineStateActions.test';
import { islandWorkshopGameTests } from './islandWorkshopGame.test';
import { momentumMatrixGameTests } from './momentumMatrixGame.test';
import { momentumMatrixStateActionsTests } from './momentumMatrixStateActions.test';
import { creatureImageManifestTests } from './creatureImageManifest.test';
import { creatureCardCatalogTests } from './creatureCardCatalog.test';
import { creatureCardAssetManifestTests } from './creatureCardAssetManifest.test';
import { creatureSanctuaryAdapterTests } from './creatureSanctuaryAdapter.test';
import { creatureCardV2AdapterTests } from './creatureCardV2Adapter.test';
import { creatureCardV2ContentSchemaTests } from './creatureCardV2ContentSchema.test';
import { creatureCollectionProgressTests } from './creatureCollectionProgress.test';
import { encounterServiceTests } from './encounterService.test';
import { islandBoardTopologyTests } from './islandBoardTopology.test';
import { islandRunFoundationTests } from './islandRunFoundations.test';
import { islandRunIslandMetadataTests } from './islandRunIslandMetadata.test';
import { islandRunPreIslandLuckyRollGateTests } from './islandRunPreIslandLuckyRollGate.test';
import { islandArtManifestTests } from './islandArtManifest.test';
import { islandRunContractV2EnergyTests } from './islandRunContractV2Energy.test';
import { islandRunContractV2SemanticsTests } from './islandRunContractV2Semantics.test';
import { islandRunContractV2StopResolverTests } from './islandRunContractV2StopResolver.test';
import { islandRunContractV2EssenceBuildTests } from './islandRunContractV2EssenceBuild.test';
import { islandRunSequentialBuildTests } from './islandRunSequentialBuild.test';
import { islandRunBuildModalV2ViewModelTests } from './islandRunBuildModalV2ViewModel.test';
import { islandRunContractV2RewardBarTests } from './islandRunContractV2RewardBar.test';
import { islandRunIntegratedEconomySafetyTests } from './islandRunIntegratedEconomySafety.test';
import { islandRunEconomyTelemetryTests } from './islandRunEconomyTelemetry.test';
import { islandRunProgressionTests } from './islandRunProgression.test';
import { islandRunRuntimeStateIntegrationTests } from './islandRunRuntimeState.integration.test';
import { islandRunRuntimeRegenTests } from './islandRunRuntimeRegen.test';
import { islandRunTimerProgressionTests } from './islandRunTimerProgression.test';
import { islandRunTreasurePathEggRewardTests } from './islandRunTreasurePathEggReward.test';
import { islandRunStopCompletionTests } from './islandRunStopCompletion.test';
import { islandRunStopStreakTests } from './islandRunStopStreak.test';
import { islandRunDiceRegenerationTests } from './islandRunDiceRegeneration.test';
import { islandRunDormantDoorMinigameTests } from './islandRunDormantDoorMinigame.test';
import { islandRunTrafficLightTileTests } from './islandRunTrafficLightTile.test';
import { islandRunStopTicketsTests } from './islandRunStopTickets.test';
import { islandRunLifeIntakeServiceTests } from './islandRunLifeIntakeService.test';
import { islandRunHabitSuggestionEngineTests } from './islandRunHabitSuggestionEngine.test';
import { islandRunAdaptiveAreasTests } from './islandRunAdaptiveAreas.test';
import { islandContentManifestTests } from './islandContentManifest.test';
import { compassCurriculumTests } from './compassCurriculum.test';
import { compassStateReducerTests } from './compassStateReducer.test';
import { islandRunStopTapRoutingTests } from './islandRunStopTapRouting.test';
import { islandRunShopAffordabilityTests } from './islandRunShopAffordability.test';
import { islandRunPlaceholderServiceTests } from './islandRunPlaceholderService.test';
import { islandRunEggSellAdvisorTests } from './islandRunEggSellAdvisor.test';
import { islandRunEggManiaTests } from './islandRunEggMania.test';
import { islandRunEggConflictMergeTests } from './islandRunEggConflictMerge.test';
import { islandRunBonusTileTests } from './islandRunBonusTile.test';
import { islandRunBossEncounterTests } from './islandRunBossEncounter.test';
import { islandRunBuildAccelerationTests } from './islandRunBuildAcceleration.test';
import { islandRunActionMutexTests } from './islandRunActionMutex.test';
import { islandRunRollActionTests } from './islandRunRollAction.test';
import { islandRunTileRewardActionTests } from './islandRunTileRewardAction.test';
import { islandRunLuckyRollActionTests } from './islandRunLuckyRollAction.test';
import { islandRunPostRareTreasurePathActionTests } from './islandRunPostRareTreasurePathAction.test';
import { islandRunEggRewardInventoryActionTests } from './islandRunEggRewardInventoryAction.test';
import { islandRunFirstSessionCreaturePackActionTests } from './islandRunFirstSessionCreaturePackAction.test';
import { islandRunAdminDevPackGrantActionTests } from './islandRunAdminDevPackGrantAction.test';
import { islandRunLuckyRollBoardConfigTests } from './islandRunLuckyRollBoardConfig.test';
import { islandRunProgressResetTests } from './islandRunProgressReset.test';
import { developerDayLoopTests } from './developerDayLoop.test';
import { islandRunStoryFastModeTests } from './islandRunStoryFastMode.test';
import { dailySpinRewardPolicyTests } from './dailySpinRewardPolicy.test';
import { islandRunDailySpinRewardActionTests } from './islandRunDailySpinRewardAction.test';
import { islandRunStateStoreTests } from './islandRunStateStore.test';
import { islandRunWelcomePackEligibilityTests } from './islandRunWelcomePackEligibility.test';
import { islandRunWelcomePackClaimActionTests } from './islandRunWelcomePackClaimAction.test';
import { islandRunWelcomePackRewardBundleActionTests } from './islandRunWelcomePackRewardBundleAction.test';
import { islandRunWelcomePackFullClaimActionTests } from './islandRunWelcomePackFullClaimAction.test';
import { islandRunWelcomePackOnboardingUiTests } from './islandRunWelcomePackOnboardingUi.test';
import { islandRunWelcomePackCopyTests } from './islandRunWelcomePackCopy.test';
import { islandRunStateActionsTests } from './islandRunStateActions.test';
import { islandRunAudioTests } from './islandRunAudio.test';
import { islandRunAmbienceTests } from './islandRunAmbience.test';
import { islandRunMusicTests } from './islandRunMusic.test';
import { storySoundtrackPolicyTests } from './storySoundtrackPolicy.test';
import { islandRunFirstSessionTutorialUiTests } from './islandRunFirstSessionTutorialUi.test';
import { islandRunCoreLoopTutorialUiTests } from './islandRunCoreLoopTutorialUi.test';
import { islandRunBestNextActionAdvisorTests } from './islandRunBestNextActionAdvisor.test';
import { islandRunBoardEssenceParityTests } from './islandRunBoardEssenceParity.test';
import { useBoardCameraTests } from './useBoardCamera.test';
import { minigameConsolidationPhase1Tests } from './minigameConsolidationPhase1.test';
import { minigameConsolidationPhase2Tests } from './minigameConsolidationPhase2.test';
import { minigameConsolidationPhase3Tests } from './minigameConsolidationPhase3.test';
import { minigameConsolidationPhase4Tests } from './minigameConsolidationPhase4.test';
import { minigameConsolidationPhase5Tests } from './minigameConsolidationPhase5.test';
import { minigameConsolidationPhase6Tests } from './minigameConsolidationPhase6.test';
import { islandRunArenaPreferencesTests } from './islandRunArenaPreferences.test';
import { arenaPuzzleGamesTests } from './arenaPuzzleGames.test';
import { spaceExcavatorCluesTests } from './spaceExcavatorClues.test';
import { spaceExcavatorDepthsTests } from './spaceExcavatorDepths.test';
import { spaceExcavatorObjectsTests } from './spaceExcavatorObjects.test';
import { spaceExcavatorRewardUxTests } from './spaceExcavatorRewardUx.test';
import { islandRunShooterControllerBridgeTests } from './islandRunShooterControllerBridge.test';
import { islandRunShooterControllerTelemetryTests } from './islandRunShooterControllerTelemetry.test';
import { shooterBlitzLaneLogicTests } from './shooterBlitzLaneLogic.test';
import { islandRunShooterControllerQaMatrixTests } from './islandRunShooterControllerQaMatrix.test';
import { outsideRewardGatewayTests } from './outsideRewardGateway.test';
import { landingPageTreatTests } from './landingPageTreat.test';
import { dicePackPurchasesTests } from './dicePackPurchases.test';
import { todayRewardsParityTests } from './todayRewardsParity.test';
import { dualTrackOverlayAdapterTests } from './dualTrackOverlayAdapter.test';
import { islandRunControllerVisualContractTests } from './islandRunControllerVisualContract.test';
import { combinedJourneyLevelTests } from './combinedJourneyLevel.test';
import { combinedJourneyRewardLadderTests } from './combinedJourneyRewardLadder.test';
import { combinedJourneyRewardClaimActionTests } from './combinedJourneyRewardClaimAction.test';
import { combinedJourneyRewardGrantTests } from './combinedJourneyRewardGrant.test';
import { combinedJourneyChestClaimTests } from './combinedJourneyChestClaim.test';
import { combinedJourneyRewardClaimsReadTests } from './combinedJourneyRewardClaimsRead.test';
import { combinedJourneyRewardBaselineTests } from './combinedJourneyRewardBaseline.test';
import { island001InhabitantTests } from '../../inhabitants/__tests__/island001Inhabitants.test';
import { islandConversationValidationTests } from '../../inhabitants/__tests__/islandConversationValidation.test';
import { islandConversationTraversalTests } from '../../inhabitants/__tests__/islandConversationTraversal.test';
import { islandRetroConversationComponentTests } from '../../inhabitants/__tests__/islandRetroConversationComponent.test';
import { islandInhabitantEncounterComponentTests } from '../../inhabitants/__tests__/islandInhabitantEncounterComponent.test';
import { islandInhabitantFlowStateTests } from '../../inhabitants/__tests__/islandInhabitantFlowState.test';
import { islandInhabitantFlowComponentTests } from '../../inhabitants/__tests__/islandInhabitantFlowComponent.test';
import { islandInhabitantFlowBlockingTests } from '../../inhabitants/__tests__/islandInhabitantFlowBlocking.test';
import { islandInhabitantBoardIntegrationTests } from '../../inhabitants/__tests__/islandInhabitantBoardIntegration.test';
import { islandCaretakerConcordTests } from '../../inhabitants/__tests__/islandCaretakerConcord.test';
import { island001NarrativeTests } from '../../narrative/__tests__/island001Narrative.test';
import { island002NarrativeTests } from '../../narrative/__tests__/island002Narrative.test';
import { island003to005NarrativeTests } from '../../narrative/__tests__/island003to005Narrative.test';
import { islandNarrativeDialogueComponentTests } from '../../narrative/__tests__/islandNarrativeDialogueComponent.test';
import { islandStoryReaderComponentTests } from '../../narrative/__tests__/islandStoryReaderComponent.test';
import { islandNarrativeOpeningFlowTests } from '../../narrative/__tests__/islandNarrativeOpeningFlow.test';
import { islandChampionshipPresentationTests } from '../../narrative/__tests__/islandChampionshipPresentation.test';
import { islandNarrativeSeenStateTests } from '../../narrative/__tests__/islandNarrativeSeenState.test';
import { islandNarrativeReactionDispatchTests } from '../../narrative/__tests__/islandNarrativeReactionDispatch.test';
import { islandNarrativeRegistryTests } from '../../narrative/__tests__/islandNarrativeRegistry.test';
import { islandNarrativeValidationTests, islandStoryManifestValidationTests } from '../../narrative/__tests__/islandNarrativeValidation.test';
import { landmarkWhispersTests } from '../../narrative/__tests__/landmarkWhispers.test';
import { islandRunModalTextColorGuardTests } from './islandRunModalTextColorGuards.test';
import { islandRunTechCollectionTests } from './islandRunTechCollection.test';
import { islandRunTechnologyFragmentRenderingGuardTests } from './islandRunTechnologyFragmentRenderingGuards.test';
import { islandRunBoardPerformanceGuardTests } from './islandRunBoardPerformanceGuards.test';
import { islandRunDiscoveryFogTests } from './islandRunDiscoveryFog.test';
import { islandRunTechCollectionPersistenceTests } from './islandRunTechCollectionPersistence.test';
import { islandTechCollectionComponentTests } from './islandTechCollectionComponent.test';
import { islandRunTechnologyUnlockTests } from './islandRunTechnologyUnlocks.test';
import { islandRunSignatureMissionTests } from './islandRunSignatureMissions.test';
import { islandRunConcordHubEntryTests } from './islandRunConcordHubEntry.test';
import { islandRunConcordRollProtectionTests } from './islandRunConcordRollProtection.test';
import { islandCommunicationAccessTests } from './islandCommunicationAccess.test';
import { bossRhythmGameTests } from './bossRhythmGame.test';
import { islandRunReflectionCurriculumTests } from './islandRunReflectionCurriculum.test';
import { islandRunClueCardCurriculumTests } from './islandRunClueCardCurriculum.test';
import { islandRunCardDrawCadenceTests } from './islandRunCardDrawCadence.test';
import { islandRunGuestFunnelStateTests } from './islandRunGuestFunnelState.test';
import { islandRunGuestTravelGateTests } from './islandRunGuestTravelGate.test';
import { islandRunModalVisibilityTests } from './islandRunModalVisibility.test';
import { islandRunGuestClaimServiceTests } from './islandRunGuestClaimService.test';
import { islandRunRoutekeeperTinyActionsTests } from './islandRunRoutekeeperTinyActions.test';
import { islandRunHabitLandmarkActionTests } from './islandRunHabitLandmarkAction.test';
import { islandRunFirstPlayerModalSchedulerTests } from './islandRunFirstPlayerModalScheduler.test';
import { islandCameraLockedKitTests } from './islandCameraLockedKit.test';
import { islandRun3DWorldRoutingTests } from './islandRun3DWorldRouting.test';
import { island5ThreePilotContractTests } from './island5ThreePilotContract.test';
import { island10RootheartThreeWorldContractTests } from './island10RootheartThreeWorldContract.test';
import { islandRunArenaCreaturePresentationTests } from './islandRunArenaCreaturePresentation.test';
import { eggHatchThreePresentationTests } from './eggHatchThreePresentation.test';
import { eggHatchThreeContractTests } from './eggHatchThreeContract.test';
import { expeditionShipThreeContractTests } from './expeditionShipThreeContract.test';
import { islandRunArenaCreatureRosterTests } from './islandRunArenaCreatureRoster.test';
import { islandRunCreatureArenaBattleTests } from './islandRunCreatureArenaBattle.test';
import { journeyDiscArenaGameTests } from './journeyDiscArenaGame.test';
import { journeyDiscArenaProgressionTests } from './journeyDiscArenaProgression.test';
import { journeyDiscArenaStateActionsTests } from './journeyDiscArenaStateActions.test';
import { journeyDiscArmoryTests } from './journeyDiscArmory.test';
import { journeyDiscArenaIslandIntegrationTests } from './journeyDiscArenaIslandIntegration.test';
import { islandRunCreatureArenaBattleActionTests } from './islandRunCreatureArenaBattleAction.test';
import { islandRunBuildOpenFlowTests } from './islandRunBuildOpenFlow.test';
import { islandRunControllerTuckPresentationTests } from './islandRunControllerTuckPresentation.test';
import { caretakerThreeModelContractTests } from './caretakerThreeModelContract.test';
import { feedPetCompanionPresentationTests } from '../../../../habits/feedPetCompanionPresentation.test';
import type { TestCase } from './testHarness';

const suites: Array<{ label: string; tests: TestCase[] }> = [
  { label: 'developerDayLoop', tests: developerDayLoopTests },
  { label: 'islandRunStoryFastMode', tests: islandRunStoryFastModeTests },
  { label: 'dailySpinRewardPolicy', tests: dailySpinRewardPolicyTests },
  { label: 'islandRunDailySpinRewardAction', tests: islandRunDailySpinRewardActionTests },
  { label: 'islandCameraLockedKit', tests: islandCameraLockedKitTests },
  { label: 'islandRun3DWorldRouting', tests: islandRun3DWorldRoutingTests },
  { label: 'island5ThreePilotContract', tests: island5ThreePilotContractTests },
  { label: 'island10RootheartThreeWorldContract', tests: island10RootheartThreeWorldContractTests },
  { label: 'islandRunArenaCreaturePresentation', tests: islandRunArenaCreaturePresentationTests },
  { label: 'eggHatchThreePresentation', tests: eggHatchThreePresentationTests },
  { label: 'eggHatchThreeContract', tests: eggHatchThreeContractTests },
  { label: 'expeditionShipThreeContract', tests: expeditionShipThreeContractTests },
  { label: 'islandRunArenaCreatureRoster', tests: islandRunArenaCreatureRosterTests },
  { label: 'islandRunCreatureArenaBattle', tests: islandRunCreatureArenaBattleTests },
  { label: 'journeyDiscArenaGame', tests: journeyDiscArenaGameTests },
  { label: 'journeyDiscArenaProgression', tests: journeyDiscArenaProgressionTests },
  { label: 'journeyDiscArenaStateActions', tests: journeyDiscArenaStateActionsTests },
  { label: 'journeyDiscArmory', tests: journeyDiscArmoryTests },
  { label: 'journeyDiscArenaIslandIntegration', tests: journeyDiscArenaIslandIntegrationTests },
  { label: 'islandRunCreatureArenaBattleAction', tests: islandRunCreatureArenaBattleActionTests },
  { label: 'islandRunBuildOpenFlow', tests: islandRunBuildOpenFlowTests },
  { label: 'islandRunControllerTuckPresentation', tests: islandRunControllerTuckPresentationTests },
  { label: 'caretakerThreeModelContract', tests: caretakerThreeModelContractTests },
  { label: 'creatureCatalog', tests: creatureCatalogTests },
  { label: 'creatureCollectionService', tests: creatureCollectionServiceTests },
  { label: 'creatureTreatInventoryService', tests: creatureTreatInventoryServiceTests },
  { label: 'creatureFitEngine', tests: creatureFitEngineTests },
  { label: 'companionRegenModifier', tests: companionRegenModifierTests },
  { label: 'companionFeastGame', tests: companionFeastGameTests },
  { label: 'minigameJuice', tests: minigameJuiceTests },
  { label: 'minigameHudContract', tests: minigameHudContractTests },
  { label: 'fortuneEngineGame', tests: fortuneEngineGameTests },
  { label: 'fortuneEngineProgression', tests: fortuneEngineProgressionTests },
  { label: 'fortuneEngineEconomyModel', tests: fortuneEngineEconomyModelTests },
  { label: 'fortuneEngineStateActions', tests: fortuneEngineStateActionsTests },
  { label: 'islandWorkshopGame', tests: islandWorkshopGameTests },
  { label: 'momentumMatrixGame', tests: momentumMatrixGameTests },
  { label: 'momentumMatrixStateActions', tests: momentumMatrixStateActionsTests },
  { label: 'creatureImageManifest', tests: creatureImageManifestTests },
  { label: 'creatureCardCatalog', tests: creatureCardCatalogTests },
  { label: 'creatureCardAssetManifest', tests: creatureCardAssetManifestTests },
  { label: 'creatureSanctuaryAdapter', tests: creatureSanctuaryAdapterTests },
  { label: 'creatureCardV2Adapter', tests: creatureCardV2AdapterTests },
  { label: 'creatureCardV2ContentSchema', tests: creatureCardV2ContentSchemaTests },
  { label: 'creatureCollectionProgress', tests: creatureCollectionProgressTests },
  { label: 'encounterService', tests: encounterServiceTests },
  { label: 'islandBoardTopology', tests: islandBoardTopologyTests },
  { label: 'islandRunFoundations', tests: islandRunFoundationTests },
  { label: 'islandRunIslandMetadata', tests: islandRunIslandMetadataTests },
  { label: 'islandRunPreIslandLuckyRollGate', tests: islandRunPreIslandLuckyRollGateTests },
  { label: 'islandArtManifest', tests: islandArtManifestTests },
  { label: 'islandConversationValidation', tests: islandConversationValidationTests },
  { label: 'islandConversationTraversal', tests: islandConversationTraversalTests },
  { label: 'islandRetroConversationComponent', tests: islandRetroConversationComponentTests },
  { label: 'islandInhabitantEncounterComponent', tests: islandInhabitantEncounterComponentTests },
  { label: 'islandInhabitantFlowState', tests: islandInhabitantFlowStateTests },
  { label: 'islandInhabitantFlowComponent', tests: islandInhabitantFlowComponentTests },
  { label: 'islandInhabitantFlowBlocking', tests: islandInhabitantFlowBlockingTests },
  { label: 'islandInhabitantBoardIntegration', tests: islandInhabitantBoardIntegrationTests },
  { label: 'islandCaretakerConcord', tests: islandCaretakerConcordTests },
  { label: 'island001Inhabitants', tests: island001InhabitantTests },
  { label: 'islandNarrativeValidation', tests: islandNarrativeValidationTests },
  { label: 'island001Narrative', tests: island001NarrativeTests },
  { label: 'island002Narrative', tests: island002NarrativeTests },
  { label: 'island003to005Narrative', tests: island003to005NarrativeTests },
  { label: 'islandNarrativeDialogueComponent', tests: islandNarrativeDialogueComponentTests },
  { label: 'islandStoryReaderComponent', tests: islandStoryReaderComponentTests },
  { label: 'islandNarrativeOpeningFlow', tests: islandNarrativeOpeningFlowTests },
  { label: 'islandChampionshipPresentation', tests: islandChampionshipPresentationTests },
  { label: 'islandNarrativeSeenState', tests: islandNarrativeSeenStateTests },
  { label: 'islandNarrativeReactionDispatch', tests: islandNarrativeReactionDispatchTests },
  { label: 'islandNarrativeRegistry', tests: islandNarrativeRegistryTests },
  { label: 'landmarkWhispers', tests: landmarkWhispersTests },
  { label: 'islandRunModalTextColorGuards', tests: islandRunModalTextColorGuardTests },
  { label: 'islandStoryManifestValidation', tests: islandStoryManifestValidationTests },
  { label: 'islandRunContractV2Energy', tests: islandRunContractV2EnergyTests },
  { label: 'islandRunContractV2Semantics', tests: islandRunContractV2SemanticsTests },
  { label: 'islandRunContractV2StopResolver', tests: islandRunContractV2StopResolverTests },
  { label: 'islandRunContractV2EssenceBuild', tests: islandRunContractV2EssenceBuildTests },
  { label: 'islandRunSequentialBuild', tests: islandRunSequentialBuildTests },
  { label: 'islandRunBuildModalV2ViewModel', tests: islandRunBuildModalV2ViewModelTests },
  { label: 'islandRunContractV2RewardBar', tests: islandRunContractV2RewardBarTests },
  { label: 'islandRunIntegratedEconomySafety', tests: islandRunIntegratedEconomySafetyTests },
  { label: 'islandRunEconomyTelemetry', tests: islandRunEconomyTelemetryTests },
  { label: 'islandRunProgression', tests: islandRunProgressionTests },
  { label: 'islandRunRuntimeStateIntegration', tests: islandRunRuntimeStateIntegrationTests },
  { label: 'islandRunRuntimeRegen', tests: islandRunRuntimeRegenTests },
  { label: 'islandRunTimerProgression', tests: islandRunTimerProgressionTests },
  { label: 'islandRunTreasurePathEggReward', tests: islandRunTreasurePathEggRewardTests },
  { label: 'islandRunStopCompletion', tests: islandRunStopCompletionTests },
  { label: 'islandRunStopStreak', tests: islandRunStopStreakTests },
  { label: 'islandRunDiceRegeneration', tests: islandRunDiceRegenerationTests },
  { label: 'islandRunDormantDoorMinigame', tests: islandRunDormantDoorMinigameTests },
  { label: 'islandRunTrafficLightTile', tests: islandRunTrafficLightTileTests },
  { label: 'islandRunStopTickets', tests: islandRunStopTicketsTests },
  { label: 'islandRunLifeIntakeService', tests: islandRunLifeIntakeServiceTests },
  { label: 'islandRunHabitSuggestionEngine', tests: islandRunHabitSuggestionEngineTests },
  { label: 'islandRunHabitLandmarkAction', tests: islandRunHabitLandmarkActionTests },
  { label: 'islandRunAdaptiveAreas', tests: islandRunAdaptiveAreasTests },
  { label: 'islandContentManifest', tests: islandContentManifestTests },
  { label: 'compassCurriculum', tests: compassCurriculumTests },
  { label: 'compassStateReducer', tests: compassStateReducerTests },
  { label: 'islandRunStopTapRouting', tests: islandRunStopTapRoutingTests },
  { label: 'islandRunShopAffordability', tests: islandRunShopAffordabilityTests },
  { label: 'islandRunPlaceholderService', tests: islandRunPlaceholderServiceTests },
  { label: 'islandRunEggSellAdvisor', tests: islandRunEggSellAdvisorTests },
  { label: 'islandRunEggMania', tests: islandRunEggManiaTests },
  { label: 'islandRunEggConflictMerge', tests: islandRunEggConflictMergeTests },
  { label: 'islandRunBonusTile', tests: islandRunBonusTileTests },
  { label: 'islandRunBossEncounter', tests: islandRunBossEncounterTests },
  { label: 'islandRunBuildAcceleration', tests: islandRunBuildAccelerationTests },
  { label: 'islandRunActionMutex', tests: islandRunActionMutexTests },
  { label: 'islandRunRollAction', tests: islandRunRollActionTests },
  { label: 'islandRunTileRewardAction', tests: islandRunTileRewardActionTests },
  { label: 'islandRunLuckyRollAction', tests: islandRunLuckyRollActionTests },
  { label: 'islandRunPostRareTreasurePathAction', tests: islandRunPostRareTreasurePathActionTests },
  { label: 'islandRunEggRewardInventoryAction', tests: islandRunEggRewardInventoryActionTests },
  { label: 'islandRunFirstSessionCreaturePackAction', tests: islandRunFirstSessionCreaturePackActionTests },
  { label: 'islandRunAdminDevPackGrantAction', tests: islandRunAdminDevPackGrantActionTests },
  { label: 'islandRunLuckyRollBoardConfig', tests: islandRunLuckyRollBoardConfigTests },
  { label: 'islandRunProgressReset', tests: islandRunProgressResetTests },
  { label: 'islandRunStateStore', tests: islandRunStateStoreTests },
  { label: 'islandRunWelcomePackEligibility', tests: islandRunWelcomePackEligibilityTests },
  { label: 'islandRunWelcomePackClaimAction', tests: islandRunWelcomePackClaimActionTests },
  { label: 'islandRunWelcomePackRewardBundleAction', tests: islandRunWelcomePackRewardBundleActionTests },
  { label: 'islandRunWelcomePackFullClaimAction', tests: islandRunWelcomePackFullClaimActionTests },
  { label: 'islandRunWelcomePackOnboardingUi', tests: islandRunWelcomePackOnboardingUiTests },
  { label: 'islandRunWelcomePackCopy', tests: islandRunWelcomePackCopyTests },
  { label: 'islandRunStateActions', tests: islandRunStateActionsTests },
  { label: 'islandRunAudio', tests: islandRunAudioTests },
  { label: 'islandRunAmbience', tests: islandRunAmbienceTests },
  { label: 'islandRunMusic', tests: islandRunMusicTests },
  { label: 'storySoundtrackPolicy', tests: storySoundtrackPolicyTests },
  { label: 'islandRunFirstSessionTutorialUi', tests: islandRunFirstSessionTutorialUiTests },
  { label: 'islandRunCoreLoopTutorialUi', tests: islandRunCoreLoopTutorialUiTests },
  { label: 'islandRunBestNextActionAdvisor', tests: islandRunBestNextActionAdvisorTests },
  { label: 'islandRunBoardEssenceParity', tests: islandRunBoardEssenceParityTests },
  { label: 'useBoardCamera', tests: useBoardCameraTests },
  { label: 'minigameConsolidationPhase1', tests: minigameConsolidationPhase1Tests },
  { label: 'minigameConsolidationPhase2', tests: minigameConsolidationPhase2Tests },
  { label: 'minigameConsolidationPhase3', tests: minigameConsolidationPhase3Tests },
  { label: 'minigameConsolidationPhase4', tests: minigameConsolidationPhase4Tests },
  { label: 'minigameConsolidationPhase5', tests: minigameConsolidationPhase5Tests },
  { label: 'minigameConsolidationPhase6', tests: minigameConsolidationPhase6Tests },
  { label: 'spaceExcavatorClues', tests: spaceExcavatorCluesTests },
  { label: 'spaceExcavatorDepths', tests: spaceExcavatorDepthsTests },
  { label: 'spaceExcavatorObjects', tests: spaceExcavatorObjectsTests },
  { label: 'spaceExcavatorRewardUx', tests: spaceExcavatorRewardUxTests },
  { label: 'islandRunShooterControllerBridge', tests: islandRunShooterControllerBridgeTests },
  { label: 'islandRunShooterControllerTelemetry', tests: islandRunShooterControllerTelemetryTests },
  { label: 'shooterBlitzLaneLogic', tests: shooterBlitzLaneLogicTests },
  { label: 'islandRunShooterControllerQaMatrix', tests: islandRunShooterControllerQaMatrixTests },
  { label: 'outsideRewardGateway', tests: outsideRewardGatewayTests },
  { label: 'landingPageTreat', tests: landingPageTreatTests },
  { label: 'dicePackPurchases', tests: dicePackPurchasesTests },
  { label: 'todayRewardsParity', tests: todayRewardsParityTests },
  { label: 'dualTrackOverlayAdapter', tests: dualTrackOverlayAdapterTests },
  { label: 'islandRunControllerVisualContract', tests: islandRunControllerVisualContractTests },
  { label: 'combinedJourneyLevel', tests: combinedJourneyLevelTests },
  { label: 'combinedJourneyRewardLadder', tests: combinedJourneyRewardLadderTests },
  { label: 'combinedJourneyRewardClaimAction', tests: combinedJourneyRewardClaimActionTests },
  { label: 'combinedJourneyRewardGrant', tests: combinedJourneyRewardGrantTests },
  { label: 'combinedJourneyChestClaim', tests: combinedJourneyChestClaimTests },
  { label: 'combinedJourneyRewardClaimsRead', tests: combinedJourneyRewardClaimsReadTests },
  { label: 'combinedJourneyRewardBaseline', tests: combinedJourneyRewardBaselineTests },
  { label: 'islandRunTechCollection', tests: islandRunTechCollectionTests },
  { label: 'islandRunTechnologyFragmentRenderingGuards', tests: islandRunTechnologyFragmentRenderingGuardTests },
  { label: 'islandRunBoardPerformanceGuards', tests: islandRunBoardPerformanceGuardTests },
  { label: 'islandRunDiscoveryFog', tests: islandRunDiscoveryFogTests },
  { label: 'islandRunTechCollectionPersistence', tests: islandRunTechCollectionPersistenceTests },
  { label: 'islandTechCollectionComponent', tests: islandTechCollectionComponentTests },
  { label: 'islandRunTechnologyUnlocks', tests: islandRunTechnologyUnlockTests },
  { label: 'islandRunSignatureMissions', tests: islandRunSignatureMissionTests },
  { label: 'islandRunConcordHubEntry', tests: islandRunConcordHubEntryTests },
  { label: 'islandRunConcordRollProtection', tests: islandRunConcordRollProtectionTests },
  { label: 'islandCommunicationAccess', tests: islandCommunicationAccessTests },
  { label: 'bossRhythmGame', tests: bossRhythmGameTests },
  { label: 'islandRunReflectionCurriculum', tests: islandRunReflectionCurriculumTests },
  { label: 'islandRunClueCardCurriculum', tests: islandRunClueCardCurriculumTests },
  { label: 'islandRunCardDrawCadence', tests: islandRunCardDrawCadenceTests },
  { label: 'islandRunGuestFunnelState', tests: islandRunGuestFunnelStateTests },
  { label: 'islandRunGuestTravelGate', tests: islandRunGuestTravelGateTests },
  { label: 'islandRunModalVisibility', tests: islandRunModalVisibilityTests },
  { label: 'islandRunArenaPreferences', tests: islandRunArenaPreferencesTests },
  { label: 'arenaPuzzleGames', tests: arenaPuzzleGamesTests },
  { label: 'islandRunGuestClaimService', tests: islandRunGuestClaimServiceTests },
  { label: 'islandRunRoutekeeperTinyActions', tests: islandRunRoutekeeperTinyActionsTests },
  { label: 'islandRunFirstPlayerModalScheduler', tests: islandRunFirstPlayerModalSchedulerTests },
  { label: 'feedPetCompanionPresentation', tests: feedPetCompanionPresentationTests },
];

async function main() {
  let passed = 0;
  let failed = 0;

  for (const suite of suites) {
    for (const test of suite.tests) {
      try {
        await test.run();
        passed += 1;
        console.log(`PASS ${suite.label}: ${test.name}`);
      } catch (error) {
        failed += 1;
        const message = error instanceof Error ? error.message : String(error);
        console.error(`FAIL ${suite.label}: ${test.name}`);
        console.error(`  ${message}`);
      }
    }
  }

  console.log(`\nIsland Run tests complete: ${passed} passed, ${failed} failed.`);

  if (failed > 0) {
    throw new Error(`Island Run tests failed: ${failed} case${failed === 1 ? '' : 's'} failing.`);
  }
}

void main();
