import { LIFE_WHEEL_AREAS, type LifeWheelArea } from '../life-wheel/lifeWheelTaxonomy';

/**
 * Suggested-habit areas are the canonical life-wheel areas (see
 * lifeWheelTaxonomy.ts), so each habit maps 1:1 to a check-in category.
 */
export type SuggestedHabitLifeWheelArea = LifeWheelArea;

export type SuggestedHabitDifficultyTier = 'tiny' | 'easy' | 'medium';

export type SuggestedHabitDefaultTiming = 'morning' | 'afternoon' | 'evening' | 'anytime';

export type SuggestedHabit = {
  suggestedHabitId: string;
  title: string;
  lifeWheelArea: SuggestedHabitLifeWheelArea;
  goalIntentTags: string[];
  difficultyTier: SuggestedHabitDifficultyTier;
  tinyVersion: string;
  normalVersion: string;
  stretchVersion: string;
  cueSuggestions: string[];
  environmentHacks: string[];
  blockerTags: string[];
  defaultTiming: SuggestedHabitDefaultTiming;
  emoji: string;
};

const SUGGESTED_HABITS: readonly SuggestedHabit[] = [
  { suggestedHabitId: 'health-water-glass', title: 'Drink one glass of water', lifeWheelArea: 'Health', goalIntentTags: ['energy', 'hydration'], difficultyTier: 'tiny', tinyVersion: 'Drink 4 sips of water.', normalVersion: 'Drink one full glass of water.', stretchVersion: 'Drink two full glasses of water.', cueSuggestions: ['After you wake up', 'Before your first coffee'], environmentHacks: ['Keep a filled bottle by your bed', 'Put a glass beside the sink'], blockerTags: ['forgetting', 'low-energy'], defaultTiming: 'morning', emoji: '💧' },
  { suggestedHabitId: 'health-5-min-walk', title: 'Walk for 5 minutes', lifeWheelArea: 'Health', goalIntentTags: ['movement', 'energy'], difficultyTier: 'easy', tinyVersion: 'Walk for 2 minutes.', normalVersion: 'Walk for 5 minutes.', stretchVersion: 'Walk for 10 minutes.', cueSuggestions: ['Right after lunch', 'After a work block'], environmentHacks: ['Keep shoes near the door', 'Set a 5-minute timer'], blockerTags: ['bad-weather', 'time-crunch'], defaultTiming: 'afternoon', emoji: '🚶' },
  { suggestedHabitId: 'health-2-min-stretch', title: 'Stretch for 2 minutes', lifeWheelArea: 'Health', goalIntentTags: ['mobility', 'stress-relief'], difficultyTier: 'tiny', tinyVersion: 'Do one gentle stretch for 30 seconds.', normalVersion: 'Stretch for 2 minutes.', stretchVersion: 'Stretch for 5 minutes.', cueSuggestions: ['After sitting 60+ minutes'], environmentHacks: ['Leave a yoga mat visible'], blockerTags: ['stiffness', 'forgetting'], defaultTiming: 'anytime', emoji: '🧘' },

  { suggestedHabitId: 'mind-3-breaths', title: 'Take 3 calm breaths', lifeWheelArea: 'Mind', goalIntentTags: ['calm', 'focus'], difficultyTier: 'tiny', tinyVersion: 'Take 1 slow breath.', normalVersion: 'Take 3 calm breaths.', stretchVersion: 'Take 10 calm breaths.', cueSuggestions: ['Before opening messages'], environmentHacks: ['Use a sticky note that says “breathe”'], blockerTags: ['rushing', 'stress'], defaultTiming: 'anytime', emoji: '🌬️' },
  { suggestedHabitId: 'mind-one-sentence', title: 'Write one sentence', lifeWheelArea: 'Mind', goalIntentTags: ['clarity', 'reflection'], difficultyTier: 'tiny', tinyVersion: 'Write 3 words.', normalVersion: 'Write one complete sentence.', stretchVersion: 'Write three sentences.', cueSuggestions: ['Before bed'], environmentHacks: ['Keep a note app pinned'], blockerTags: ['perfectionism', 'mental-fatigue'], defaultTiming: 'evening', emoji: '✍️' },
  { suggestedHabitId: 'mind-1-min-reset', title: 'Do a 1-minute reset', lifeWheelArea: 'Mind', goalIntentTags: ['reset', 'stress-relief'], difficultyTier: 'tiny', tinyVersion: 'Close your eyes for 20 seconds.', normalVersion: 'Take a full 1-minute pause.', stretchVersion: 'Take a 3-minute pause.', cueSuggestions: ['Between tasks'], environmentHacks: ['Set a recurring chime every 2 hours'], blockerTags: ['busy-schedule'], defaultTiming: 'afternoon', emoji: '🧠' },

  { suggestedHabitId: 'work-must-win', title: 'Pick one must-win task', lifeWheelArea: 'Work', goalIntentTags: ['focus', 'productivity'], difficultyTier: 'easy', tinyVersion: 'Name one task out loud.', normalVersion: 'Write one must-win task.', stretchVersion: 'Write one must-win + one backup task.', cueSuggestions: ['Start of work session'], environmentHacks: ['Keep a must-win sticky note on desk'], blockerTags: ['overwhelm', 'distraction'], defaultTiming: 'morning', emoji: '🎯' },
  { suggestedHabitId: 'work-2-min-start', title: 'Start with 2 focused minutes', lifeWheelArea: 'Work', goalIntentTags: ['momentum', 'focus'], difficultyTier: 'tiny', tinyVersion: 'Open the task and work 30 seconds.', normalVersion: 'Work for 2 focused minutes.', stretchVersion: 'Work for 10 focused minutes.', cueSuggestions: ['Before checking email'], environmentHacks: ['Open your task doc before breaks'], blockerTags: ['procrastination'], defaultTiming: 'morning', emoji: '⏱️' },
  { suggestedHabitId: 'work-end-next-step', title: 'Write the next step before stopping', lifeWheelArea: 'Work', goalIntentTags: ['planning', 'consistency'], difficultyTier: 'easy', tinyVersion: 'Write one keyword for next step.', normalVersion: 'Write one clear next step.', stretchVersion: 'Write next step and start time.', cueSuggestions: ['Last 2 minutes of work'], environmentHacks: ['Leave tomorrow task open on screen'], blockerTags: ['fatigue', 'forgetting'], defaultTiming: 'evening', emoji: '➡️' },

  { suggestedHabitId: 'money-check-balance', title: 'Check your main account balance', lifeWheelArea: 'Money', goalIntentTags: ['awareness', 'stability'], difficultyTier: 'tiny', tinyVersion: 'Open your banking app.', normalVersion: 'Check your main account balance.', stretchVersion: 'Check balance and one recent transaction.', cueSuggestions: ['After breakfast'], environmentHacks: ['Place banking app on first screen'], blockerTags: ['avoidance', 'anxiety'], defaultTiming: 'morning', emoji: '💵' },
  { suggestedHabitId: 'money-log-one-spend', title: 'Log one expense', lifeWheelArea: 'Money', goalIntentTags: ['tracking', 'budgeting'], difficultyTier: 'easy', tinyVersion: 'Capture expense amount only.', normalVersion: 'Log one expense with category.', stretchVersion: 'Log three expenses with category.', cueSuggestions: ['After any purchase'], environmentHacks: ['Keep a one-tap expense shortcut'], blockerTags: ['forgetting', 'time-crunch'], defaultTiming: 'anytime', emoji: '🧾' },
  { suggestedHabitId: 'money-transfer-small', title: 'Transfer a small amount to savings', lifeWheelArea: 'Money', goalIntentTags: ['saving', 'future-planning'], difficultyTier: 'easy', tinyVersion: 'Move $1 to savings.', normalVersion: 'Move a small preset amount to savings.', stretchVersion: 'Move twice your preset amount to savings.', cueSuggestions: ['Payday or income day'], environmentHacks: ['Enable automatic transfer template'], blockerTags: ['low-cash', 'inconsistency'], defaultTiming: 'afternoon', emoji: '🏦' },

  { suggestedHabitId: 'relationships-warm-message', title: 'Send one warm message', lifeWheelArea: 'Love', goalIntentTags: ['connection', 'kindness'], difficultyTier: 'tiny', tinyVersion: 'Send one emoji check-in.', normalVersion: 'Send one warm sentence.', stretchVersion: 'Send warm message + one follow-up question.', cueSuggestions: ['During a short break'], environmentHacks: ['Keep a favorites contact list'], blockerTags: ['busyness', 'social-anxiety'], defaultTiming: 'afternoon', emoji: '💌' },
  { suggestedHabitId: 'relationships-one-appreciation', title: 'Share one appreciation', lifeWheelArea: 'Love', goalIntentTags: ['gratitude', 'connection'], difficultyTier: 'easy', tinyVersion: 'Think of one appreciation silently.', normalVersion: 'Share one specific appreciation.', stretchVersion: 'Share appreciation and why it mattered.', cueSuggestions: ['Dinner time'], environmentHacks: ['Capture good moments in notes'], blockerTags: ['awkwardness', 'forgetting'], defaultTiming: 'evening', emoji: '🙏' },
  { suggestedHabitId: 'relationships-pause-breath', title: 'Pause for one breath before reacting', lifeWheelArea: 'Love', goalIntentTags: ['emotional-regulation', 'communication'], difficultyTier: 'tiny', tinyVersion: 'Pause for half a breath.', normalVersion: 'Pause for one full breath.', stretchVersion: 'Pause for three breaths.', cueSuggestions: ['When you feel tension rising'], environmentHacks: ['Set lock screen reminder: “one breath first”'], blockerTags: ['reactivity', 'stress'], defaultTiming: 'anytime', emoji: '🕊️' },

  { suggestedHabitId: 'home-clear-surface', title: 'Clear one small surface', lifeWheelArea: 'Home', goalIntentTags: ['tidy', 'calm-space'], difficultyTier: 'easy', tinyVersion: 'Clear one item.', normalVersion: 'Clear one small surface.', stretchVersion: 'Clear one surface and wipe it down.', cueSuggestions: ['Before bed'], environmentHacks: ['Keep a quick-drop basket nearby'], blockerTags: ['clutter', 'low-energy'], defaultTiming: 'evening', emoji: '🧹' },
  { suggestedHabitId: 'home-2-min-reset', title: 'Do a 2-minute room reset', lifeWheelArea: 'Home', goalIntentTags: ['order', 'momentum'], difficultyTier: 'tiny', tinyVersion: 'Reset for 30 seconds.', normalVersion: 'Reset one room for 2 minutes.', stretchVersion: 'Reset two rooms for 2 minutes each.', cueSuggestions: ['After arriving home'], environmentHacks: ['Use a visible 2-minute timer'], blockerTags: ['fatigue', 'overwhelm'], defaultTiming: 'evening', emoji: '🏠' },
  { suggestedHabitId: 'home-prep-tomorrow-item', title: 'Prep one item for tomorrow', lifeWheelArea: 'Home', goalIntentTags: ['planning', 'smooth-mornings'], difficultyTier: 'tiny', tinyVersion: 'Place one needed item by the door.', normalVersion: 'Prep one item for tomorrow morning.', stretchVersion: 'Prep outfit + one key item.', cueSuggestions: ['Right after dinner'], environmentHacks: ['Create a fixed launch spot'], blockerTags: ['forgetting', 'rushing'], defaultTiming: 'evening', emoji: '🎒' },

  { suggestedHabitId: 'growth-read-one-page', title: 'Read one page', lifeWheelArea: 'Work', goalIntentTags: ['learning', 'self-improvement'], difficultyTier: 'tiny', tinyVersion: 'Read one paragraph.', normalVersion: 'Read one page.', stretchVersion: 'Read five pages and note one idea.', cueSuggestions: ['Before scrolling social media'], environmentHacks: ['Keep book visible on table'], blockerTags: ['distraction', 'time-crunch'], defaultTiming: 'anytime', emoji: '📚' },
  { suggestedHabitId: 'growth-learn-one-note', title: 'Capture one learning note', lifeWheelArea: 'Work', goalIntentTags: ['reflection', 'learning'], difficultyTier: 'tiny', tinyVersion: 'Write one keyword.', normalVersion: 'Write one learning note.', stretchVersion: 'Write one note and one action step.', cueSuggestions: ['After a podcast/video'], environmentHacks: ['Use pinned “learn note” template'], blockerTags: ['forgetting', 'mental-fatigue'], defaultTiming: 'afternoon', emoji: '📝' },
  { suggestedHabitId: 'growth-ask-one-question', title: 'Ask one growth question', lifeWheelArea: 'Work', goalIntentTags: ['curiosity', 'skill-building'], difficultyTier: 'easy', tinyVersion: 'Think of one question.', normalVersion: 'Ask one person or source one question.', stretchVersion: 'Ask one question and summarize the answer.', cueSuggestions: ['During work or study block'], environmentHacks: ['Keep a “questions” running list'], blockerTags: ['self-doubt', 'inertia'], defaultTiming: 'afternoon', emoji: '❓' },

  { suggestedHabitId: 'fun-5-min-play', title: 'Do 5 minutes of playful activity', lifeWheelArea: 'Fun', goalIntentTags: ['joy', 'recovery'], difficultyTier: 'easy', tinyVersion: 'Do 1 minute of play.', normalVersion: 'Do 5 minutes of playful activity.', stretchVersion: 'Do 15 minutes of playful activity.', cueSuggestions: ['After finishing one task'], environmentHacks: ['Keep a short “fun list” ready'], blockerTags: ['guilt', 'busy-schedule'], defaultTiming: 'evening', emoji: '🎉' },
  { suggestedHabitId: 'fun-notice-beauty', title: 'Notice one beautiful thing', lifeWheelArea: 'Fun', goalIntentTags: ['presence', 'joy'], difficultyTier: 'tiny', tinyVersion: 'Pause and notice one color.', normalVersion: 'Notice and name one beautiful thing.', stretchVersion: 'Notice three things and take one photo.', cueSuggestions: ['On a walk or commute'], environmentHacks: ['Use a phone wallpaper reminder'], blockerTags: ['autopilot', 'stress'], defaultTiming: 'anytime', emoji: '✨' },
  { suggestedHabitId: 'fun-micro-creative', title: 'Create something tiny', lifeWheelArea: 'Fun', goalIntentTags: ['creativity', 'self-expression'], difficultyTier: 'tiny', tinyVersion: 'Doodle one line.', normalVersion: 'Create something tiny for 2 minutes.', stretchVersion: 'Create for 10 minutes.', cueSuggestions: ['Before bed wind-down'], environmentHacks: ['Leave one creative tool visible'], blockerTags: ['perfectionism', 'low-energy'], defaultTiming: 'evening', emoji: '🎨' },

  { suggestedHabitId: 'connections-text-friend', title: 'Text a friend you miss', lifeWheelArea: 'Connections', goalIntentTags: ['connection', 'kindness'], difficultyTier: 'tiny', tinyVersion: 'Send one “thinking of you” emoji.', normalVersion: 'Text one friend you miss.', stretchVersion: 'Text a friend and suggest a time to talk.', cueSuggestions: ['During a coffee break'], environmentHacks: ['Pin a “people I miss” note in your phone'], blockerTags: ['busyness', 'social-anxiety'], defaultTiming: 'afternoon', emoji: '📱' },
  { suggestedHabitId: 'connections-call-family', title: 'Check in with family', lifeWheelArea: 'Connections', goalIntentTags: ['connection', 'communication'], difficultyTier: 'easy', tinyVersion: 'Send a family member one quick message.', normalVersion: 'Call or voice-note one family member.', stretchVersion: 'Have a 10-minute catch-up call with family.', cueSuggestions: ['After dinner'], environmentHacks: ['Keep favourite family contacts at the top'], blockerTags: ['forgetting', 'time-crunch'], defaultTiming: 'evening', emoji: '📞' },
  { suggestedHabitId: 'connections-plan-meetup', title: 'Plan one small meetup', lifeWheelArea: 'Connections', goalIntentTags: ['connection', 'kindness'], difficultyTier: 'easy', tinyVersion: 'Suggest one date to meet.', normalVersion: 'Plan one small meetup with a friend.', stretchVersion: 'Plan a meetup and send a calendar invite.', cueSuggestions: ['On a weekend morning'], environmentHacks: ['Keep a short list of low-effort meetup ideas'], blockerTags: ['scheduling', 'inertia'], defaultTiming: 'anytime', emoji: '🧑‍🤝‍🧑' },

  // ── Library expansion: two more options per area ──
  { suggestedHabitId: 'health-morning-light', title: 'Get a dose of morning light', lifeWheelArea: 'Health', goalIntentTags: ['energy', 'movement'], difficultyTier: 'tiny', tinyVersion: 'Step outside for 30 seconds.', normalVersion: 'Get 2 minutes of morning light.', stretchVersion: 'Get 10 minutes of morning light outside.', cueSuggestions: ['Right after waking up'], environmentHacks: ['Leave your shoes by the door'], blockerTags: ['bad-weather', 'low-energy'], defaultTiming: 'morning', emoji: '🌅' },
  { suggestedHabitId: 'health-protein-breakfast', title: 'Add protein to breakfast', lifeWheelArea: 'Health', goalIntentTags: ['energy', 'nutrition'], difficultyTier: 'easy', tinyVersion: 'Add one bite of protein.', normalVersion: 'Add a protein source to breakfast.', stretchVersion: 'Build a balanced protein-first breakfast.', cueSuggestions: ['While making breakfast'], environmentHacks: ['Keep easy protein options stocked'], blockerTags: ['time-crunch', 'forgetting'], defaultTiming: 'morning', emoji: '🥚' },

  { suggestedHabitId: 'mind-note-good-thing', title: 'Note one good thing', lifeWheelArea: 'Mind', goalIntentTags: ['gratitude', 'reflection'], difficultyTier: 'tiny', tinyVersion: 'Think of one good thing.', normalVersion: 'Write down one good thing from today.', stretchVersion: 'Write three good things and why they mattered.', cueSuggestions: ['Before bed'], environmentHacks: ['Keep a gratitude note pinned'], blockerTags: ['mental-fatigue', 'forgetting'], defaultTiming: 'evening', emoji: '🌟' },
  { suggestedHabitId: 'mind-delay-phone', title: 'Delay your first phone check', lifeWheelArea: 'Mind', goalIntentTags: ['calm', 'focus'], difficultyTier: 'easy', tinyVersion: 'Wait 1 minute before checking your phone.', normalVersion: 'Wait 10 minutes before checking your phone.', stretchVersion: 'Keep the first 30 minutes phone-free.', cueSuggestions: ['Right after waking up'], environmentHacks: ['Charge your phone outside the bedroom'], blockerTags: ['habit-loop', 'distraction'], defaultTiming: 'morning', emoji: '📵' },

  { suggestedHabitId: 'money-pause-impulse', title: 'Pause one impulse buy', lifeWheelArea: 'Money', goalIntentTags: ['awareness', 'budgeting'], difficultyTier: 'tiny', tinyVersion: 'Pause 10 seconds before buying.', normalVersion: 'Wait an hour before one impulse buy.', stretchVersion: 'Wait a day before any non-essential buy.', cueSuggestions: ['At checkout'], environmentHacks: ['Remove saved cards from shopping apps'], blockerTags: ['impulse', 'stress'], defaultTiming: 'anytime', emoji: '✋' },
  { suggestedHabitId: 'money-review-subscription', title: 'Review one subscription', lifeWheelArea: 'Money', goalIntentTags: ['awareness', 'saving'], difficultyTier: 'easy', tinyVersion: 'Open your subscriptions list.', normalVersion: 'Review one subscription you rarely use.', stretchVersion: 'Cancel one unused subscription.', cueSuggestions: ['On payday'], environmentHacks: ['Keep a running list of subscriptions'], blockerTags: ['avoidance', 'forgetting'], defaultTiming: 'afternoon', emoji: '🔁' },

  { suggestedHabitId: 'love-ask-about-day', title: 'Ask about their day', lifeWheelArea: 'Love', goalIntentTags: ['connection', 'communication'], difficultyTier: 'tiny', tinyVersion: 'Ask one question about their day.', normalVersion: 'Ask and really listen to their day.', stretchVersion: 'Ask, listen, and follow up on one detail.', cueSuggestions: ['Over dinner'], environmentHacks: ['Put phones away during catch-ups'], blockerTags: ['distraction', 'busyness'], defaultTiming: 'evening', emoji: '👂' },
  { suggestedHabitId: 'love-plan-small-date', title: 'Plan a small date', lifeWheelArea: 'Love', goalIntentTags: ['connection', 'kindness'], difficultyTier: 'easy', tinyVersion: 'Suggest one date idea.', normalVersion: 'Plan one small date this week.', stretchVersion: 'Plan a date and lock in the time.', cueSuggestions: ['On a weekend'], environmentHacks: ['Keep a shared list of date ideas'], blockerTags: ['scheduling', 'inertia'], defaultTiming: 'anytime', emoji: '💞' },

  { suggestedHabitId: 'connections-thank-someone', title: 'Thank someone', lifeWheelArea: 'Connections', goalIntentTags: ['gratitude', 'kindness'], difficultyTier: 'tiny', tinyVersion: 'Send one quick thank-you.', normalVersion: 'Thank someone specifically for something.', stretchVersion: 'Thank them and say why it mattered.', cueSuggestions: ['When someone helps you'], environmentHacks: ['Keep a “people who helped” note'], blockerTags: ['forgetting', 'awkwardness'], defaultTiming: 'anytime', emoji: '🙌' },
  { suggestedHabitId: 'connections-reply-overdue', title: 'Reply to one overdue message', lifeWheelArea: 'Connections', goalIntentTags: ['connection', 'communication'], difficultyTier: 'easy', tinyVersion: 'Open one overdue message.', normalVersion: 'Reply to one overdue message.', stretchVersion: 'Clear two overdue replies.', cueSuggestions: ['During a quiet moment'], environmentHacks: ['Flag overdue messages so they stay visible'], blockerTags: ['overwhelm', 'avoidance'], defaultTiming: 'afternoon', emoji: '💬' },

  { suggestedHabitId: 'home-make-bed', title: 'Make your bed', lifeWheelArea: 'Home', goalIntentTags: ['order', 'momentum'], difficultyTier: 'tiny', tinyVersion: 'Straighten the pillows.', normalVersion: 'Make your bed.', stretchVersion: 'Make your bed and tidy the nightstand.', cueSuggestions: ['Right after getting up'], environmentHacks: ['Keep bedding simple to straighten'], blockerTags: ['rushing', 'low-energy'], defaultTiming: 'morning', emoji: '🛏️' },
  { suggestedHabitId: 'home-one-load-laundry', title: 'Start one load of laundry', lifeWheelArea: 'Home', goalIntentTags: ['order', 'tidy'], difficultyTier: 'easy', tinyVersion: 'Sort one pile of laundry.', normalVersion: 'Start one load of laundry.', stretchVersion: 'Wash, dry, and put away one load.', cueSuggestions: ['Before leaving the house'], environmentHacks: ['Keep a basket by the machine'], blockerTags: ['procrastination', 'forgetting'], defaultTiming: 'anytime', emoji: '🧺' },

  { suggestedHabitId: 'fun-dance-one-song', title: 'Dance to one song', lifeWheelArea: 'Fun', goalIntentTags: ['joy', 'movement'], difficultyTier: 'tiny', tinyVersion: 'Sway to 30 seconds of a song.', normalVersion: 'Dance to one full song.', stretchVersion: 'Dance to three songs in a row.', cueSuggestions: ['While getting ready'], environmentHacks: ['Keep a feel-good playlist ready'], blockerTags: ['self-consciousness', 'low-energy'], defaultTiming: 'anytime', emoji: '💃' },
  { suggestedHabitId: 'fun-try-something-new', title: 'Try one tiny new thing', lifeWheelArea: 'Fun', goalIntentTags: ['curiosity', 'joy'], difficultyTier: 'easy', tinyVersion: 'Notice one new option to try.', normalVersion: 'Try one small new thing today.', stretchVersion: 'Try something new and tell someone about it.', cueSuggestions: ['On a free afternoon'], environmentHacks: ['Keep a “want to try” list'], blockerTags: ['routine-rut', 'inertia'], defaultTiming: 'afternoon', emoji: '🎲' },

  // ── Health deep-dive library: sleep, movement, nutrition, environment ──
  { suggestedHabitId: 'health-bed-eight-hours', title: 'Be in bed for eight hours', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'recovery'], difficultyTier: 'easy', tinyVersion: 'Be in bed for 6 hours.', normalVersion: 'Be in bed for a full eight hours.', stretchVersion: 'Be in bed eight hours after a proper wind-down.', cueSuggestions: ['At your target bedtime'], environmentHacks: ['Set a “go to bed” alarm 30 minutes before'], blockerTags: ['late-nights', 'screens'], defaultTiming: 'evening', emoji: '🛌' },
  { suggestedHabitId: 'health-consistent-bedtime', title: 'Keep the same bedtime', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'routine'], difficultyTier: 'easy', tinyVersion: 'Go to bed within 60 minutes of your target.', normalVersion: 'Go to bed at the same time tonight.', stretchVersion: 'Hit the same bedtime every night this week.', cueSuggestions: ['When your bedtime alarm goes off'], environmentHacks: ['Set a recurring nightly bedtime alarm'], blockerTags: ['irregular-schedule', 'late-nights'], defaultTiming: 'evening', emoji: '⏰' },
  { suggestedHabitId: 'health-bed-before-midnight', title: 'Be in bed before midnight', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'recovery'], difficultyTier: 'easy', tinyVersion: 'Be in bed by 12:30.', normalVersion: 'Be in bed before midnight.', stretchVersion: 'Be in bed by 11pm.', cueSuggestions: ['After your wind-down routine'], environmentHacks: ['Set a “lights out” alarm for 11:30'], blockerTags: ['late-nights', 'screens'], defaultTiming: 'evening', emoji: '🌙' },
  { suggestedHabitId: 'health-no-late-eating', title: 'Stop eating before bed', lifeWheelArea: 'Health', goalIntentTags: ['digestion', 'sleep'], difficultyTier: 'easy', tinyVersion: 'Stop eating 1 hour before bed.', normalVersion: 'Stop eating 2–3 hours before bed.', stretchVersion: 'Keep a clean 3-hour eating cutoff before sleep.', cueSuggestions: ['Right after dinner'], environmentHacks: ['Brush your teeth straight after dinner'], blockerTags: ['late-snacking', 'habit-loop'], defaultTiming: 'evening', emoji: '🚫' },
  { suggestedHabitId: 'health-calm-dinner', title: 'Choose calm foods for dinner', lifeWheelArea: 'Health', goalIntentTags: ['nutrition', 'sleep'], difficultyTier: 'easy', tinyVersion: 'Swap one heavy dinner item for something lighter.', normalVersion: 'Make dinner light and easy to digest.', stretchVersion: 'Build a calm, whole-food dinner.', cueSuggestions: ['While planning dinner'], environmentHacks: ['Keep simple light-dinner options stocked'], blockerTags: ['convenience', 'cravings'], defaultTiming: 'evening', emoji: '🍲' },
  { suggestedHabitId: 'health-no-screens-before-bed', title: 'No screens one hour before bed', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'calm'], difficultyTier: 'medium', tinyVersion: 'No screens for 15 minutes before bed.', normalVersion: 'No screens for one hour before bed.', stretchVersion: 'No screens for 90 minutes before bed.', cueSuggestions: ['When your wind-down starts'], environmentHacks: ['Charge your phone outside the bedroom'], blockerTags: ['habit-loop', 'boredom'], defaultTiming: 'evening', emoji: '📵' },
  { suggestedHabitId: 'health-skip-processed-food', title: 'Skip ultra-processed food', lifeWheelArea: 'Health', goalIntentTags: ['nutrition', 'energy'], difficultyTier: 'medium', tinyVersion: 'Skip one processed snack today.', normalVersion: 'Skip added-sugar and fried convenience foods today.', stretchVersion: 'Eat fully unprocessed for the whole day.', cueSuggestions: ['At the store or vending machine'], environmentHacks: ['Don’t keep convenience snacks at home'], blockerTags: ['cravings', 'convenience'], defaultTiming: 'anytime', emoji: '🥤' },
  { suggestedHabitId: 'health-shoes-off', title: 'Take your shoes off at the door', lifeWheelArea: 'Health', goalIntentTags: ['clean-living', 'home'], difficultyTier: 'tiny', tinyVersion: 'Take your shoes off once today.', normalVersion: 'Take your shoes off at the door.', stretchVersion: 'Set a shoes-off rule for the whole household.', cueSuggestions: ['The moment you walk in'], environmentHacks: ['Put a shoe rack by the entrance'], blockerTags: ['forgetting', 'rushing'], defaultTiming: 'anytime', emoji: '👟' },
  { suggestedHabitId: 'health-whole-foods-meal', title: 'Eat a whole-foods meal', lifeWheelArea: 'Health', goalIntentTags: ['nutrition', 'energy'], difficultyTier: 'easy', tinyVersion: 'Add one whole food to a meal.', normalVersion: 'Make one meal from whole foods.', stretchVersion: 'Eat whole foods across the whole day.', cueSuggestions: ['While preparing a meal'], environmentHacks: ['Keep fruit and veg visible and ready'], blockerTags: ['convenience', 'time-crunch'], defaultTiming: 'anytime', emoji: '🥦' },
  { suggestedHabitId: 'health-move-after-meals', title: 'Move after meals', lifeWheelArea: 'Health', goalIntentTags: ['movement', 'digestion'], difficultyTier: 'tiny', tinyVersion: 'Do 5 air squats after a meal.', normalVersion: 'Walk a few minutes or do air squats after a meal.', stretchVersion: 'Take a 10-minute walk after each main meal.', cueSuggestions: ['Right after eating'], environmentHacks: ['Keep a clear path for a quick post-meal walk'], blockerTags: ['fatigue', 'time-crunch'], defaultTiming: 'afternoon', emoji: '🚶' },
  { suggestedHabitId: 'health-raise-heart-rate', title: 'Get your heart rate up', lifeWheelArea: 'Health', goalIntentTags: ['fitness', 'energy'], difficultyTier: 'medium', tinyVersion: 'Do 1 minute of brisk movement.', normalVersion: 'Get your heart rate up for 10 minutes.', stretchVersion: 'Do 20+ minutes of real cardio.', cueSuggestions: ['After a work block'], environmentHacks: ['Lay out your workout clothes in advance'], blockerTags: ['low-energy', 'time-crunch'], defaultTiming: 'afternoon', emoji: '🏃' },
  { suggestedHabitId: 'health-lift-heavy', title: 'Lift something heavy', lifeWheelArea: 'Health', goalIntentTags: ['strength', 'fitness'], difficultyTier: 'medium', tinyVersion: 'Do 5 bodyweight squats.', normalVersion: 'Do one short strength set.', stretchVersion: 'Complete a full strength session.', cueSuggestions: ['On a strength-training day'], environmentHacks: ['Keep weights or resistance bands in sight'], blockerTags: ['low-energy', 'intimidation'], defaultTiming: 'anytime', emoji: '🏋️' },
  { suggestedHabitId: 'health-oral-care-routine', title: 'Full oral care, morning and night', lifeWheelArea: 'Health', goalIntentTags: ['hygiene', 'prevention'], difficultyTier: 'easy', tinyVersion: 'Brush your teeth.', normalVersion: 'Brush, floss, and scrape your tongue.', stretchVersion: 'Water pick, floss, brush, and tongue scrape, morning and night.', cueSuggestions: ['After waking and before bed'], environmentHacks: ['Keep floss and a tongue scraper next to your brush'], blockerTags: ['rushing', 'forgetting'], defaultTiming: 'anytime', emoji: '🪥' },
  { suggestedHabitId: 'health-sun-protection', title: 'Protect your skin in midday sun', lifeWheelArea: 'Health', goalIntentTags: ['skin', 'prevention'], difficultyTier: 'tiny', tinyVersion: 'Find shade for a few minutes at midday.', normalVersion: 'Apply sunscreen or cover up before midday sun.', stretchVersion: 'Use sunscreen, a hat, and shade through peak hours.', cueSuggestions: ['Before going out around midday'], environmentHacks: ['Keep sunscreen by the door'], blockerTags: ['forgetting'], defaultTiming: 'afternoon', emoji: '🧴' },
  { suggestedHabitId: 'health-stand-tall', title: 'Stand up straight', lifeWheelArea: 'Health', goalIntentTags: ['posture', 'energy'], difficultyTier: 'tiny', tinyVersion: 'Roll your shoulders back once.', normalVersion: 'Reset your posture and stand tall.', stretchVersion: 'Check and fix your posture every hour.', cueSuggestions: ['When you catch yourself slouching'], environmentHacks: ['Put a posture reminder on your screen'], blockerTags: ['autopilot', 'fatigue'], defaultTiming: 'anytime', emoji: '🧍' },
  { suggestedHabitId: 'health-see-a-friend', title: 'See a friend this week', lifeWheelArea: 'Health', goalIntentTags: ['connection', 'wellbeing'], difficultyTier: 'easy', tinyVersion: 'Message a friend to set something up.', normalVersion: 'Meet one friend in person this week.', stretchVersion: 'See two friends this week.', cueSuggestions: ['On a free evening or weekend'], environmentHacks: ['Keep a shortlist of friends to see'], blockerTags: ['busyness', 'inertia'], defaultTiming: 'anytime', emoji: '🧑‍🤝‍🧑' },
  { suggestedHabitId: 'health-avoid-plastic', title: 'Avoid plastic where you can', lifeWheelArea: 'Health', goalIntentTags: ['clean-living', 'environment'], difficultyTier: 'easy', tinyVersion: 'Skip one single-use plastic today.', normalVersion: 'Choose non-plastic options where you can.', stretchVersion: 'Keep food and drink plastic-free all day.', cueSuggestions: ['When shopping or storing food'], environmentHacks: ['Keep glass containers and a reusable bottle handy'], blockerTags: ['convenience', 'cost'], defaultTiming: 'anytime', emoji: '♻️' },
  { suggestedHabitId: 'health-air-out-rooms', title: 'Air out your rooms', lifeWheelArea: 'Health', goalIntentTags: ['air-quality', 'home'], difficultyTier: 'tiny', tinyVersion: 'Open one window for 2 minutes.', normalVersion: 'Air out your main rooms today.', stretchVersion: 'Cross-ventilate the whole home for 10 minutes.', cueSuggestions: ['In the morning'], environmentHacks: ['Keep a window easy to reach and open'], blockerTags: ['bad-weather', 'forgetting'], defaultTiming: 'morning', emoji: '🪟' },
  { suggestedHabitId: 'health-breathe-when-stressed', title: 'Breathe when stressed', lifeWheelArea: 'Health', goalIntentTags: ['calm', 'stress-relief'], difficultyTier: 'tiny', tinyVersion: 'Take one slow breath.', normalVersion: 'Take a few slow breaths when stress rises.', stretchVersion: 'Do a full minute of slow breathing.', cueSuggestions: ['When you feel tension rising'], environmentHacks: ['Put a “breathe” note on your lock screen'], blockerTags: ['reactivity', 'rushing'], defaultTiming: 'anytime', emoji: '🌬️' },
  { suggestedHabitId: 'health-dental-visits', title: 'Keep up with dental visits', lifeWheelArea: 'Health', goalIntentTags: ['hygiene', 'prevention'], difficultyTier: 'easy', tinyVersion: 'Note when your last dental visit was.', normalVersion: 'Book your next dental check-up.', stretchVersion: 'Book and confirm your dental and hygienist visits.', cueSuggestions: ['When you think of it'], environmentHacks: ['Add a recurring dental reminder to your calendar'], blockerTags: ['avoidance', 'cost'], defaultTiming: 'anytime', emoji: '🦷' },
  { suggestedHabitId: 'health-break-up-sitting', title: 'Break up long sitting', lifeWheelArea: 'Health', goalIntentTags: ['movement', 'circulation'], difficultyTier: 'tiny', tinyVersion: 'Stand up and stretch once.', normalVersion: 'Stand and move for 2 minutes every hour.', stretchVersion: 'Take a short walk every 45 minutes.', cueSuggestions: ['After sitting 60+ minutes'], environmentHacks: ['Set an hourly stand-up reminder'], blockerTags: ['focus-flow', 'forgetting'], defaultTiming: 'afternoon', emoji: '🪑' },
  { suggestedHabitId: 'health-protect-hearing', title: 'Protect your hearing', lifeWheelArea: 'Health', goalIntentTags: ['hearing', 'prevention'], difficultyTier: 'tiny', tinyVersion: 'Lower your volume one notch.', normalVersion: 'Keep volume moderate and take loud-noise breaks.', stretchVersion: 'Use ear protection in loud places.', cueSuggestions: ['When you put in headphones or enter a loud place'], environmentHacks: ['Carry earplugs in your bag'], blockerTags: ['habit-loop', 'forgetting'], defaultTiming: 'anytime', emoji: '🎧' },
  { suggestedHabitId: 'health-alcohol-free-day', title: 'Have an alcohol-free day', lifeWheelArea: 'Health', goalIntentTags: ['clean-living', 'recovery'], difficultyTier: 'easy', tinyVersion: 'Delay your first drink by an hour.', normalVersion: 'Keep today completely alcohol-free.', stretchVersion: 'String together several alcohol-free days.', cueSuggestions: ['When you’d usually pour a drink'], environmentHacks: ['Keep an appealing non-alcoholic option ready'], blockerTags: ['habit-loop', 'social-pressure'], defaultTiming: 'evening', emoji: '🚱' },
  { suggestedHabitId: 'health-coffee-before-noon', title: 'Finish coffee before noon', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'energy'], difficultyTier: 'easy', tinyVersion: 'Have your last coffee by 2pm.', normalVersion: 'Finish all caffeine before noon.', stretchVersion: 'Switch to decaf or water after your morning cup.', cueSuggestions: ['At lunchtime'], environmentHacks: ['Only keep decaf available in the afternoon'], blockerTags: ['habit-loop', 'afternoon-slump'], defaultTiming: 'morning', emoji: '☕' },
  { suggestedHabitId: 'health-dim-lights-evening', title: 'Dim bright lights after sunset', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'calm'], difficultyTier: 'tiny', tinyVersion: 'Turn off one overhead light after sunset.', normalVersion: 'Switch to dim, warm lighting after sunset.', stretchVersion: 'Use only low, warm light for the last hour before bed.', cueSuggestions: ['After the sun goes down'], environmentHacks: ['Set up warm, dimmable lamps'], blockerTags: ['forgetting', 'habit-loop'], defaultTiming: 'evening', emoji: '🕯️' },
  { suggestedHabitId: 'health-cool-bedroom', title: 'Sleep in a cool room', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'recovery'], difficultyTier: 'tiny', tinyVersion: 'Crack a window before bed.', normalVersion: 'Cool your bedroom down before sleep.', stretchVersion: 'Keep your bedroom around 18°C / 65°F all night.', cueSuggestions: ['As you start your wind-down'], environmentHacks: ['Set a thermostat schedule for the night'], blockerTags: ['cost', 'bad-weather'], defaultTiming: 'evening', emoji: '🌡️' },
  { suggestedHabitId: 'health-no-texting-driving', title: 'Phone away while driving', lifeWheelArea: 'Health', goalIntentTags: ['safety', 'focus'], difficultyTier: 'tiny', tinyVersion: 'Put your phone on silent before driving.', normalVersion: 'Keep your phone out of reach while driving.', stretchVersion: 'Enable a driving “do not disturb” mode every trip.', cueSuggestions: ['Before you start the car'], environmentHacks: ['Turn on auto “do not disturb while driving”'], blockerTags: ['habit-loop', 'fomo'], defaultTiming: 'anytime', emoji: '🚗' },
  { suggestedHabitId: 'health-notifications-off', title: 'Turn off non-essential notifications', lifeWheelArea: 'Health', goalIntentTags: ['focus', 'calm'], difficultyTier: 'easy', tinyVersion: 'Turn off notifications for one noisy app.', normalVersion: 'Turn off all non-essential notifications.', stretchVersion: 'Keep only calls and messages from key people on.', cueSuggestions: ['When an app interrupts you'], environmentHacks: ['Review your notification settings in one sitting'], blockerTags: ['fomo', 'habit-loop'], defaultTiming: 'anytime', emoji: '🔕' },
  { suggestedHabitId: 'health-limit-social-media', title: 'Limit social media', lifeWheelArea: 'Health', goalIntentTags: ['focus', 'calm'], difficultyTier: 'medium', tinyVersion: 'Delay your first social check by 30 minutes.', normalVersion: 'Keep social media under a set time today.', stretchVersion: 'Take a full day off social media.', cueSuggestions: ['When you reach for a social app'], environmentHacks: ['Set an app time limit'], blockerTags: ['habit-loop', 'boredom'], defaultTiming: 'anytime', emoji: '📱' },
  { suggestedHabitId: 'health-smoke-free', title: 'Stay smoke-free today', lifeWheelArea: 'Health', goalIntentTags: ['clean-living', 'recovery'], difficultyTier: 'medium', tinyVersion: 'Delay your next cigarette by 30 minutes.', normalVersion: 'Get through today smoke-free.', stretchVersion: 'String together several smoke-free days.', cueSuggestions: ['When a craving hits'], environmentHacks: ['Keep cigarettes out of the house'], blockerTags: ['cravings', 'stress'], defaultTiming: 'anytime', emoji: '🚭' },
  { suggestedHabitId: 'health-read-before-bed', title: 'Read a book before bed', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'calm'], difficultyTier: 'tiny', tinyVersion: 'Read one page before bed.', normalVersion: 'Read a few pages of a book before bed.', stretchVersion: 'Read for 20 minutes before sleep.', cueSuggestions: ['Once you are in bed'], environmentHacks: ['Keep a paper book on your nightstand'], blockerTags: ['screens', 'fatigue'], defaultTiming: 'evening', emoji: '📖' },
  { suggestedHabitId: 'health-wind-down-hour', title: 'Wind down for an hour before bed', lifeWheelArea: 'Health', goalIntentTags: ['sleep', 'calm'], difficultyTier: 'medium', tinyVersion: 'Take 10 quiet minutes before bed.', normalVersion: 'Wind down for an hour before bed.', stretchVersion: 'Keep a full, screen-free wind-down hour every night.', cueSuggestions: ['One hour before your bedtime'], environmentHacks: ['Set a “start winding down” alarm'], blockerTags: ['busyness', 'screens'], defaultTiming: 'evening', emoji: '🛁' },
];

const STARTER_HABIT_BY_AREA: Record<SuggestedHabitLifeWheelArea, SuggestedHabit> = LIFE_WHEEL_AREAS.reduce(
  (acc, area) => {
    const first = SUGGESTED_HABITS.find((habit) => habit.lifeWheelArea === area);
    if (first) {
      acc[area] = first;
    }
    return acc;
  },
  {} as Record<SuggestedHabitLifeWheelArea, SuggestedHabit>,
);

export function getAllSuggestedHabits(): SuggestedHabit[] {
  return [...SUGGESTED_HABITS];
}

export function getSuggestedHabitsByLifeWheelArea(area: SuggestedHabitLifeWheelArea): SuggestedHabit[] {
  return SUGGESTED_HABITS.filter((habit) => habit.lifeWheelArea === area);
}

export function getSuggestedHabitsByGoalIntent(intentTag: string): SuggestedHabit[] {
  return SUGGESTED_HABITS.filter((habit) => habit.goalIntentTags.includes(intentTag));
}

export function getSuggestedHabitById(id: string): SuggestedHabit | undefined {
  return SUGGESTED_HABITS.find((habit) => habit.suggestedHabitId === id);
}

export function getStarterHabitForArea(area: SuggestedHabitLifeWheelArea): SuggestedHabit {
  return STARTER_HABIT_BY_AREA[area];
}
