import type { SuitKey } from '../identity/archetypes/archetypeDeck';
import type { TraitKey } from '../identity/personalityTestData';

export type AvatarItemCategory = 'tools' | 'charms' | 'garments' | 'auras' | 'badges' | 'companions';

export type AvatarItem = {
  id: string;
  emoji: string;
  name: string;
  description: string;
  rarity: 'Common' | 'Rare' | 'Epic' | 'Legendary';
  category: AvatarItemCategory;
  suitAffinity?: SuitKey;
  archetypeAffinity?: string[];
  traitRequirement?: { trait: TraitKey; minScore: number };
  unlockCondition: 'free' | 'personality' | 'achievement' | 'purchase';
  price?: number;
};

export const AVATAR_ITEM_CATALOG: AvatarItem[] = [
  // POWER SUIT ITEMS (Red/Agency)
  // Tools
  {
    id: 'battle-horn',
    emoji: '📯',
    name: 'Battle Horn',
    description: 'Rally your forces and charge forward',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'iron-gauntlets',
    emoji: '🥊',
    name: 'Iron Gauntlets',
    description: 'Strike with unstoppable force',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['champion', 'challenger'],
    unlockCondition: 'personality',
  },
  {
    id: 'commanders-baton',
    emoji: '🎖️',
    name: "Commander's Baton",
    description: 'Direct your team with precision',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'diplomat'],
    unlockCondition: 'personality',
  },
  {
    id: 'war-map',
    emoji: '🗺️',
    name: 'War Map',
    description: 'Plan every strategic move',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['strategist'],
    unlockCondition: 'personality',
  },
  {
    id: 'dragon-scale-shield',
    emoji: '🛡️',
    name: 'Dragon Scale Shield',
    description: 'Impenetrable defense',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['guardian'],
    unlockCondition: 'personality',
  },
  {
    id: 'titans-hammer',
    emoji: '🔨',
    name: "Titan's Hammer",
    description: 'Crushing power in every blow',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['warlord', 'champion'],
    unlockCondition: 'personality',
  },
  {
    id: 'power-crystal',
    emoji: '💎',
    name: 'Power Crystal',
    description: 'Channel raw energy',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'victory-banner',
    emoji: '🚩',
    name: 'Victory Banner',
    description: 'Mark your triumphs',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'power',
    archetypeAffinity: ['champion'],
    unlockCondition: 'personality',
  },

  // Charms
  {
    id: 'lions-mane-talisman',
    emoji: '🦁',
    name: "Lion's Mane Talisman",
    description: 'Courage of the king',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'phoenix-feather',
    emoji: '🔥',
    name: 'Phoenix Feather',
    description: 'Rise from any defeat',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['champion', 'challenger'],
    unlockCondition: 'personality',
  },
  {
    id: 'dragons-tooth',
    emoji: '🦷',
    name: "Dragon's Tooth",
    description: 'Ancient power awakened',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'wolf-fang-pendant',
    emoji: '🐺',
    name: 'Wolf Fang Pendant',
    description: 'Pack loyalty and strength',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['guardian'],
    unlockCondition: 'personality',
  },
  {
    id: 'thors-rune',
    emoji: '⚡',
    name: "Thor's Rune",
    description: 'Thunder god blessing',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'gladiators-coin',
    emoji: '🪙',
    name: "Gladiator's Coin",
    description: 'Victory or death',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['champion'],
    unlockCondition: 'personality',
  },
  {
    id: 'red-star-gem',
    emoji: '⭐',
    name: 'Red Star Gem',
    description: 'Burning ambition',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'warlords-seal',
    emoji: '🏺',
    name: "Warlord's Seal",
    description: 'Authority unquestioned',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'power',
    archetypeAffinity: ['warlord', 'commander'],
    unlockCondition: 'personality',
  },

  // Garments
  {
    id: 'blood-knight-armor',
    emoji: '🦾',
    name: 'Blood Knight Armor',
    description: 'Battle-tested protection',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['champion', 'guardian'],
    unlockCondition: 'personality',
  },
  {
    id: 'generals-cloak',
    emoji: '🧥',
    name: "General's Cloak",
    description: 'Command respect',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['commander'],
    unlockCondition: 'personality',
  },
  {
    id: 'battle-crown',
    emoji: '👑',
    name: 'Battle Crown',
    description: 'Rule the battlefield',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'war-boots',
    emoji: '🥾',
    name: 'War Boots',
    description: 'March to victory',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'crimson-sash',
    emoji: '🎗️',
    name: 'Crimson Sash',
    description: 'Mark of leadership',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'diplomat'],
    unlockCondition: 'personality',
  },
  {
    id: 'power-gloves',
    emoji: '🧤',
    name: 'Power Gloves',
    description: 'Grip victory tight',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'steel-shoulderguards',
    emoji: '⚔️',
    name: 'Steel Shoulderguards',
    description: 'Bear any burden',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['guardian'],
    unlockCondition: 'personality',
  },
  {
    id: 'champions-belt',
    emoji: '🏆',
    name: "Champion's Belt",
    description: 'Worn by winners',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'power',
    archetypeAffinity: ['champion'],
    unlockCondition: 'personality',
  },

  // Auras
  {
    id: 'blazing-inferno',
    emoji: '🔥',
    name: 'Blazing Inferno',
    description: 'Unstoppable flames of passion',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'power',
    archetypeAffinity: ['challenger', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'crimson-storm',
    emoji: '🌪️',
    name: 'Crimson Storm',
    description: 'Fury unleashed',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'lightning-surge',
    emoji: '⚡',
    name: 'Lightning Surge',
    description: 'Electric intensity',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'power',
    archetypeAffinity: ['warlord', 'champion'],
    unlockCondition: 'personality',
  },
  {
    id: 'power-pulse',
    emoji: '💥',
    name: 'Power Pulse',
    description: 'Waves of raw energy',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'dragons-breath',
    emoji: '🐉',
    name: "Dragon's Breath",
    description: 'Legendary might radiates',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },
  {
    id: 'volcanic-eruption',
    emoji: '🌋',
    name: 'Volcanic Eruption',
    description: 'Explosive power',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'power',
    archetypeAffinity: ['challenger'],
    unlockCondition: 'personality',
  },
  {
    id: 'war-cry-shockwave',
    emoji: '📢',
    name: 'War Cry Shockwave',
    description: 'Intimidating presence',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'power',
    archetypeAffinity: ['commander', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'iron-will-aura',
    emoji: '🛡️',
    name: 'Iron Will Aura',
    description: 'Unbreakable determination',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'power',
    archetypeAffinity: ['guardian', 'strategist'],
    unlockCondition: 'personality',
  },

  // Companions
  {
    id: 'war-hawk',
    emoji: '🦅',
    name: 'War Hawk',
    description: 'Swift aerial scout',
    rarity: 'Epic',
    category: 'companions',
    suitAffinity: 'power',
    archetypeAffinity: ['strategist'],
    unlockCondition: 'personality',
  },
  {
    id: 'shadow-wolf',
    emoji: '🐺',
    name: 'Shadow Wolf',
    description: 'Loyal pack hunter',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'power',
    archetypeAffinity: ['guardian', 'warlord'],
    unlockCondition: 'personality',
  },
  {
    id: 'battle-ram',
    emoji: '🐏',
    name: 'Battle Ram',
    description: 'Unstoppable charge',
    rarity: 'Rare',
    category: 'companions',
    suitAffinity: 'power',
    archetypeAffinity: ['challenger'],
    unlockCondition: 'personality',
  },
  {
    id: 'fire-drake',
    emoji: '🐉',
    name: 'Fire Drake',
    description: 'Dragon companion',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'power',
    unlockCondition: 'personality',
  },

  // HEART SUIT ITEMS (Pink/Empathy)
  // Tools
  {
    id: 'healing-harp',
    emoji: '🎻',
    name: 'Healing Harp',
    description: 'Melodies that mend souls',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['healer', 'peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'compassion-compass',
    emoji: '🧭',
    name: 'Compassion Compass',
    description: 'Guide others with empathy',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver', 'mentor'],
    unlockCondition: 'personality',
  },
  {
    id: 'empathy-mirror',
    emoji: '🪞',
    name: 'Empathy Mirror',
    description: 'Reflect others\' feelings',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['empath'],
    unlockCondition: 'personality',
  },
  {
    id: 'heart-lantern',
    emoji: '🏮',
    name: 'Heart Lantern',
    description: 'Light the path of love',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['altruist', 'devotee'],
    unlockCondition: 'personality',
  },
  {
    id: 'bonding-ribbon',
    emoji: '🎀',
    name: 'Bonding Ribbon',
    description: 'Connect hearts together',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['connector'],
    unlockCondition: 'personality',
  },
  {
    id: 'hope-quill',
    emoji: '🪶',
    name: 'Hope Quill',
    description: 'Write words of comfort',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['mentor'],
    unlockCondition: 'personality',
  },
  {
    id: 'harmony-bell',
    emoji: '🔔',
    name: 'Harmony Bell',
    description: 'Ring in peace',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'peace-pipe',
    emoji: '🕊️',
    name: 'Peace Pipe',
    description: 'Seal truces and bonds',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },

  // Charms
  {
    id: 'rose-quartz-heart',
    emoji: '💗',
    name: 'Rose Quartz Heart',
    description: 'Stone of unconditional love',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['devotee', 'altruist'],
    unlockCondition: 'personality',
  },
  {
    id: 'doves-grace',
    emoji: '🕊️',
    name: "Dove's Grace",
    description: 'Pure peace within',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'angel-wing-pin',
    emoji: '🪽',
    name: 'Angel Wing Pin',
    description: 'Guardian blessing',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver', 'healer'],
    unlockCondition: 'personality',
  },
  {
    id: 'friendship-bracelet',
    emoji: '🤝',
    name: 'Friendship Bracelet',
    description: 'Bond of trust',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['connector'],
    unlockCondition: 'personality',
  },
  {
    id: 'soul-stone',
    emoji: '💎',
    name: 'Soul Stone',
    description: 'Deep connection crystal',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['empath'],
    unlockCondition: 'personality',
  },
  {
    id: 'kindness-crystal',
    emoji: '🔮',
    name: 'Kindness Crystal',
    description: 'Radiate compassion',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },
  {
    id: 'love-potion-vial',
    emoji: '🧪',
    name: 'Love Potion Vial',
    description: 'Spread warmth everywhere',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },
  {
    id: 'guardian-angel-medal',
    emoji: '👼',
    name: 'Guardian Angel Medal',
    description: 'Divine protection',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver', 'healer'],
    unlockCondition: 'personality',
  },

  // Garments
  {
    id: 'healers-robes',
    emoji: '👘',
    name: "Healer's Robes",
    description: 'Sacred garment of care',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['healer'],
    unlockCondition: 'personality',
  },
  {
    id: 'caregivers-apron',
    emoji: '🩺',
    name: "Caregiver's Apron",
    description: 'Ready to serve',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver'],
    unlockCondition: 'personality',
  },
  {
    id: 'mentors-hood',
    emoji: '🎓',
    name: "Mentor's Hood",
    description: 'Wisdom passed down',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['mentor'],
    unlockCondition: 'personality',
  },
  {
    id: 'peacemakers-stole',
    emoji: '🧣',
    name: "Peacemaker's Stole",
    description: 'Diplomatic vestment',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'altruists-mantle',
    emoji: '🦺',
    name: "Altruist's Mantle",
    description: 'Cloak of service',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['altruist'],
    unlockCondition: 'personality',
  },
  {
    id: 'empaths-scarf',
    emoji: '🧣',
    name: "Empath's Scarf",
    description: 'Feel deeply, stay warm',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'heart',
    archetypeAffinity: ['empath'],
    unlockCondition: 'personality',
  },
  {
    id: 'heart-crown',
    emoji: '👑',
    name: 'Heart Crown',
    description: 'Rule with love',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-shawl',
    emoji: '🪭',
    name: 'Spirit Shawl',
    description: 'Wrap in comfort',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },

  // Auras
  {
    id: 'warm-embrace-glow',
    emoji: '🤗',
    name: 'Warm Embrace Glow',
    description: 'Comforting presence',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver', 'empath'],
    unlockCondition: 'personality',
  },
  {
    id: 'healing-light',
    emoji: '💫',
    name: 'Healing Light',
    description: 'Restorative radiance',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['healer'],
    unlockCondition: 'personality',
  },
  {
    id: 'pink-blossom-rain',
    emoji: '🌸',
    name: 'Pink Blossom Rain',
    description: 'Beauty and grace',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },
  {
    id: 'heart-pulse-wave',
    emoji: '💓',
    name: 'Heart Pulse Wave',
    description: 'Rhythmic love energy',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['devotee'],
    unlockCondition: 'personality',
  },
  {
    id: 'gentle-mist',
    emoji: '🌫️',
    name: 'Gentle Mist',
    description: 'Soft and soothing',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'compassion-radiance',
    emoji: '✨',
    name: 'Compassion Radiance',
    description: 'Pure empathy shines',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['empath', 'altruist'],
    unlockCondition: 'personality',
  },
  {
    id: 'love-shield',
    emoji: '💗',
    name: 'Love Shield',
    description: 'Protected by care',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver'],
    unlockCondition: 'personality',
  },
  {
    id: 'harmony-circle',
    emoji: '⭕',
    name: 'Harmony Circle',
    description: 'Peace surrounds you',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'heart',
    archetypeAffinity: ['peacemaker'],
    unlockCondition: 'personality',
  },

  // Companions
  {
    id: 'healing-dove',
    emoji: '🕊️',
    name: 'Healing Dove',
    description: 'Symbol of peace',
    rarity: 'Epic',
    category: 'companions',
    suitAffinity: 'heart',
    archetypeAffinity: ['healer', 'peacemaker'],
    unlockCondition: 'personality',
  },
  {
    id: 'gentle-stag',
    emoji: '🦌',
    name: 'Gentle Stag',
    description: 'Noble protector',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'heart',
    archetypeAffinity: ['caregiver'],
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-fox',
    emoji: '🦊',
    name: 'Spirit Fox',
    description: 'Wise companion',
    rarity: 'Rare',
    category: 'companions',
    suitAffinity: 'heart',
    archetypeAffinity: ['mentor'],
    unlockCondition: 'personality',
  },
  {
    id: 'baby-phoenix',
    emoji: '🐣',
    name: 'Baby Phoenix',
    description: 'New beginnings',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'heart',
    unlockCondition: 'personality',
  },

  // MIND SUIT ITEMS (Blue/Reason)
  // Tools
  {
    id: 'scholars-telescope',
    emoji: '🔭',
    name: "Scholar's Telescope",
    description: 'See far into knowledge',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage', 'scholar'],
    unlockCondition: 'personality',
  },
  {
    id: 'logic-engine',
    emoji: '⚙️',
    name: 'Logic Engine',
    description: 'Process pure reason',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst', 'engineer'],
    unlockCondition: 'personality',
  },
  {
    id: 'knowledge-codex',
    emoji: '📚',
    name: 'Knowledge Codex',
    description: 'Infinite wisdom bound',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['scholar', 'sage'],
    unlockCondition: 'personality',
  },
  {
    id: 'analysis-lens',
    emoji: '🔍',
    name: 'Analysis Lens',
    description: 'See through complexity',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst', 'detective'],
    unlockCondition: 'personality',
  },
  {
    id: 'blueprint-pen',
    emoji: '🖊️',
    name: 'Blueprint Pen',
    description: 'Design perfect systems',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'circuit-board',
    emoji: '💾',
    name: 'Circuit Board',
    description: 'Build digital solutions',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['engineer', 'inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'research-flask',
    emoji: '🧪',
    name: 'Research Flask',
    description: 'Experiment and discover',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'algorithm-cube',
    emoji: '🎲',
    name: 'Algorithm Cube',
    description: 'Solve any problem',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst'],
    unlockCondition: 'personality',
  },

  // Charms
  {
    id: 'wisdom-tooth',
    emoji: '🦷',
    name: 'Wisdom Tooth',
    description: 'Ancient knowledge',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage'],
    unlockCondition: 'personality',
  },
  {
    id: 'owl-eye-monocle',
    emoji: '🦉',
    name: 'Owl Eye Monocle',
    description: 'See truth clearly',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage', 'philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'brain-coral',
    emoji: '🧠',
    name: 'Brain Coral',
    description: 'Neural network talisman',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'mind',
    unlockCondition: 'personality',
  },
  {
    id: 'mercury-drop',
    emoji: '💧',
    name: 'Mercury Drop',
    description: 'Quicksilver mind',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'philosophers-stone',
    emoji: '💎',
    name: "Philosopher's Stone",
    description: 'Transform understanding',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'think-tank-globe',
    emoji: '🌐',
    name: 'Think Tank Globe',
    description: 'World of ideas',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'eureka-light-bulb',
    emoji: '💡',
    name: 'Eureka Light Bulb',
    description: 'Brilliant insights',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'library-key',
    emoji: '🔑',
    name: 'Library Key',
    description: 'Unlock all knowledge',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'mind',
    archetypeAffinity: ['scholar'],
    unlockCondition: 'personality',
  },

  // Garments
  {
    id: 'professors-jacket',
    emoji: '🥼',
    name: "Professor's Jacket",
    description: 'Academic distinction',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['scholar', 'sage'],
    unlockCondition: 'personality',
  },
  {
    id: 'inventors-goggles',
    emoji: '🥽',
    name: "Inventor's Goggles",
    description: 'See possibilities',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'architects-hard-hat',
    emoji: '👷',
    name: "Architect's Hard Hat",
    description: 'Build great systems',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'analysts-lab-coat',
    emoji: '🥼',
    name: "Analyst's Lab Coat",
    description: 'Scientific precision',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst'],
    unlockCondition: 'personality',
  },
  {
    id: 'scholars-toga',
    emoji: '👘',
    name: "Scholar's Toga",
    description: 'Classical learning',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['scholar', 'philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'detectives-trenchcoat',
    emoji: '🧥',
    name: "Detective's Trenchcoat",
    description: 'Investigate mysteries',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['detective'],
    unlockCondition: 'personality',
  },
  {
    id: 'philosophers-cap',
    emoji: '🎩',
    name: "Philosopher's Cap",
    description: 'Deep thinking hat',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'engineers-vest',
    emoji: '🦺',
    name: "Engineer's Vest",
    description: 'Tool-ready wear',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'mind',
    archetypeAffinity: ['engineer'],
    unlockCondition: 'personality',
  },

  // Auras
  {
    id: 'neural-network-glow',
    emoji: '🧠',
    name: 'Neural Network Glow',
    description: 'Thoughts interconnect',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst', 'architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'blueprint-hologram',
    emoji: '📐',
    name: 'Blueprint Hologram',
    description: 'Design visualization',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'data-stream-rain',
    emoji: '💾',
    name: 'Data Stream Rain',
    description: 'Information flows',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst'],
    unlockCondition: 'personality',
  },
  {
    id: 'thought-bubble-cloud',
    emoji: '💭',
    name: 'Thought Bubble Cloud',
    description: 'Ideas manifest',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'logic-matrix',
    emoji: '⚡',
    name: 'Logic Matrix',
    description: 'Reason crystallized',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'mind',
    unlockCondition: 'personality',
  },
  {
    id: 'quantum-field',
    emoji: '🌌',
    name: 'Quantum Field',
    description: 'Probability waves',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage', 'inventor'],
    unlockCondition: 'personality',
  },
  {
    id: 'knowledge-aurora',
    emoji: '🌠',
    name: 'Knowledge Aurora',
    description: 'Wisdom illuminates',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage', 'scholar'],
    unlockCondition: 'personality',
  },
  {
    id: 'calculation-cascade',
    emoji: '🔢',
    name: 'Calculation Cascade',
    description: 'Numbers dance',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst', 'engineer'],
    unlockCondition: 'personality',
  },

  // Companions
  {
    id: 'wisdom-owl',
    emoji: '🦉',
    name: 'Wisdom Owl',
    description: 'Ancient knowledge keeper',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'mind',
    archetypeAffinity: ['sage', 'philosopher'],
    unlockCondition: 'personality',
  },
  {
    id: 'clockwork-companion',
    emoji: '⏰',
    name: 'Clockwork Companion',
    description: 'Precision automaton',
    rarity: 'Epic',
    category: 'companions',
    suitAffinity: 'mind',
    archetypeAffinity: ['engineer', 'architect'],
    unlockCondition: 'personality',
  },
  {
    id: 'code-spider',
    emoji: '🕷️',
    name: 'Code Spider',
    description: 'Weaves logic webs',
    rarity: 'Rare',
    category: 'companions',
    suitAffinity: 'mind',
    archetypeAffinity: ['analyst'],
    unlockCondition: 'personality',
  },
  {
    id: 'knowledge-sprite',
    emoji: '🧚',
    name: 'Knowledge Sprite',
    description: 'Information familiar',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'mind',
    unlockCondition: 'personality',
  },

  // SPIRIT SUIT ITEMS (Purple/Vision)
  // Tools
  {
    id: 'vision-orb',
    emoji: '🔮',
    name: 'Vision Orb',
    description: 'See future possibilities',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['visionary', 'mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'dream-journal',
    emoji: '📔',
    name: 'Dream Journal',
    description: 'Capture visions',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['dreamer', 'creator'],
    unlockCondition: 'personality',
  },
  {
    id: 'soul-compass',
    emoji: '🧭',
    name: 'Soul Compass',
    description: 'Navigate inner worlds',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic', 'shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'star-map',
    emoji: '🗺️',
    name: 'Star Map',
    description: 'Chart your destiny',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['explorer', 'pioneer'],
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-drum',
    emoji: '🥁',
    name: 'Spirit Drum',
    description: 'Shamanic journey tool',
    rarity: 'Legendary',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'mystic-wand',
    emoji: '✨',
    name: 'Mystic Wand',
    description: 'Channel cosmic energy',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'creators-palette',
    emoji: '🎨',
    name: "Creator's Palette",
    description: 'Paint new realities',
    rarity: 'Rare',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['creator'],
    unlockCondition: 'personality',
  },
  {
    id: 'rebels-flag',
    emoji: '🏴',
    name: "Rebel's Flag",
    description: 'Symbol of revolution',
    rarity: 'Epic',
    category: 'tools',
    suitAffinity: 'spirit',
    archetypeAffinity: ['rebel'],
    unlockCondition: 'personality',
  },

  // Charms
  {
    id: 'third-eye-gem',
    emoji: '👁️',
    name: 'Third Eye Gem',
    description: 'See beyond the veil',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-feather',
    emoji: '🪶',
    name: 'Spirit Feather',
    description: 'Touch the divine',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'cosmic-dust-jar',
    emoji: '✨',
    name: 'Cosmic Dust Jar',
    description: 'Stardust essence',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['visionary'],
    unlockCondition: 'personality',
  },
  {
    id: 'dream-catcher',
    emoji: '🕸️',
    name: 'Dream Catcher',
    description: 'Protect your visions',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['dreamer'],
    unlockCondition: 'personality',
  },
  {
    id: 'astral-key',
    emoji: '🔑',
    name: 'Astral Key',
    description: 'Unlock dimensions',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic', 'explorer'],
    unlockCondition: 'personality',
  },
  {
    id: 'moon-shard',
    emoji: '🌙',
    name: 'Moon Shard',
    description: 'Lunar power',
    rarity: 'Epic',
    category: 'charms',
    suitAffinity: 'spirit',
    unlockCondition: 'personality',
  },
  {
    id: 'starlight-pendant',
    emoji: '⭐',
    name: 'Starlight Pendant',
    description: 'Celestial blessing',
    rarity: 'Rare',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['pioneer'],
    unlockCondition: 'personality',
  },
  {
    id: 'vision-quartz',
    emoji: '💎',
    name: 'Vision Quartz',
    description: 'Clarity of purpose',
    rarity: 'Legendary',
    category: 'charms',
    suitAffinity: 'spirit',
    archetypeAffinity: ['visionary'],
    unlockCondition: 'personality',
  },

  // Garments
  {
    id: 'mystic-cloak',
    emoji: '🧙',
    name: 'Mystic Cloak',
    description: 'Shrouded in mystery',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'dreamers-nightgown',
    emoji: '👗',
    name: "Dreamer's Nightgown",
    description: 'Comfortable in dreams',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['dreamer'],
    unlockCondition: 'personality',
  },
  {
    id: 'visionarys-crown',
    emoji: '👑',
    name: "Visionary's Crown",
    description: 'See what could be',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['visionary'],
    unlockCondition: 'personality',
  },
  {
    id: 'explorers-safari-hat',
    emoji: '🧢',
    name: "Explorer's Safari Hat",
    description: 'Ready for adventure',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['explorer'],
    unlockCondition: 'personality',
  },
  {
    id: 'creators-smock',
    emoji: '👕',
    name: "Creator's Smock",
    description: 'Artistic freedom',
    rarity: 'Rare',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['creator'],
    unlockCondition: 'personality',
  },
  {
    id: 'rebels-leather-jacket',
    emoji: '🧥',
    name: "Rebel's Leather Jacket",
    description: 'Defy the norm',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['rebel'],
    unlockCondition: 'personality',
  },
  {
    id: 'shamans-beads',
    emoji: '📿',
    name: "Shaman's Beads",
    description: 'Sacred adornment',
    rarity: 'Legendary',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'pioneers-space-suit',
    emoji: '🚀',
    name: "Pioneer's Space Suit",
    description: 'Explore the unknown',
    rarity: 'Epic',
    category: 'garments',
    suitAffinity: 'spirit',
    archetypeAffinity: ['pioneer'],
    unlockCondition: 'personality',
  },

  // Auras
  {
    id: 'astral-projection',
    emoji: '👻',
    name: 'Astral Projection',
    description: 'Spirit walks freely',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'cosmic-nebula',
    emoji: '🌌',
    name: 'Cosmic Nebula',
    description: 'Universe within',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['visionary', 'explorer'],
    unlockCondition: 'personality',
  },
  {
    id: 'aurora-borealis',
    emoji: '🌠',
    name: 'Aurora Borealis',
    description: 'Northern lights dance',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'spirit',
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-walk-shimmer',
    emoji: '✨',
    name: 'Spirit Walk Shimmer',
    description: 'Between worlds',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'dream-haze',
    emoji: '🌫️',
    name: 'Dream Haze',
    description: 'Surreal atmosphere',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['dreamer'],
    unlockCondition: 'personality',
  },
  {
    id: 'starfield-aura',
    emoji: '⭐',
    name: 'Starfield Aura',
    description: 'Stars surround you',
    rarity: 'Epic',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['pioneer', 'explorer'],
    unlockCondition: 'personality',
  },
  {
    id: 'mystic-fog',
    emoji: '🌀',
    name: 'Mystic Fog',
    description: 'Enigmatic presence',
    rarity: 'Rare',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'creative-spark-storm',
    emoji: '💫',
    name: 'Creative Spark Storm',
    description: 'Ideas explode',
    rarity: 'Legendary',
    category: 'auras',
    suitAffinity: 'spirit',
    archetypeAffinity: ['creator', 'visionary'],
    unlockCondition: 'personality',
  },

  // Companions
  {
    id: 'cosmic-cat',
    emoji: '🐱',
    name: 'Cosmic Cat',
    description: 'Nine lives, infinite wisdom',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'spirit',
    archetypeAffinity: ['mystic'],
    unlockCondition: 'personality',
  },
  {
    id: 'dream-butterfly',
    emoji: '🦋',
    name: 'Dream Butterfly',
    description: 'Transform reality',
    rarity: 'Epic',
    category: 'companions',
    suitAffinity: 'spirit',
    archetypeAffinity: ['dreamer', 'creator'],
    unlockCondition: 'personality',
  },
  {
    id: 'spirit-owl',
    emoji: '🦉',
    name: 'Spirit Owl',
    description: 'Night vision guide',
    rarity: 'Rare',
    category: 'companions',
    suitAffinity: 'spirit',
    archetypeAffinity: ['shaman'],
    unlockCondition: 'personality',
  },
  {
    id: 'astral-dragon',
    emoji: '🐉',
    name: 'Astral Dragon',
    description: 'Dimensional traveler',
    rarity: 'Legendary',
    category: 'companions',
    suitAffinity: 'spirit',
    archetypeAffinity: ['pioneer', 'explorer'],
    unlockCondition: 'personality',
  },

  // GENERIC/UNIVERSAL BADGES (no suit affinity)
  {
    id: 'early-bird',
    emoji: '🌅',
    name: 'Early Bird',
    description: 'First to seize the day',
    rarity: 'Rare',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 500,
  },
  {
    id: 'night-owl',
    emoji: '🦉',
    name: 'Night Owl',
    description: 'Productive under the moon',
    rarity: 'Rare',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 500,
  },
  {
    id: 'streak-master',
    emoji: '🔥',
    name: 'Streak Master',
    description: 'Consistency is your superpower',
    rarity: 'Epic',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 1000,
  },
  {
    id: 'zen-warrior',
    emoji: '☯️',
    name: 'Zen Warrior',
    description: 'Balance in all things',
    rarity: 'Legendary',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 2000,
  },
  {
    id: 'goal-crusher',
    emoji: '🎯',
    name: 'Goal Crusher',
    description: 'Targets never stand a chance',
    rarity: 'Epic',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 1000,
  },
  {
    id: 'habit-hero',
    emoji: '💪',
    name: 'Habit Hero',
    description: 'Routines forged in steel',
    rarity: 'Legendary',
    category: 'badges',
    unlockCondition: 'achievement',
    price: 2000,
  },
  {
    id: 'level-10-badge',
    emoji: '🏅',
    name: 'Level 10 Hero',
    description: 'Reached Level 10',
    rarity: 'Epic',
    category: 'badges',
    unlockCondition: 'achievement',
  },
  {
    id: 'level-25-badge',
    emoji: '🥇',
    name: 'Level 25 Champion',
    description: 'Reached Level 25',
    rarity: 'Legendary',
    category: 'badges',
    unlockCondition: 'achievement',
  },
];

export const CATEGORY_INFO: Record<
  AvatarItemCategory,
  { emoji: string; label: string }
> = {
  tools: { emoji: '🛠️', label: 'Tools' },
  charms: { emoji: '🍀', label: 'Lucky Charms' },
  garments: { emoji: '👕', label: 'Garments' },
  auras: { emoji: '✨', label: 'Auras' },
  badges: { emoji: '🏅', label: 'Badges' },
  companions: { emoji: '🐾', label: 'Companions' },
};
