import { FAMILIES, getFamily } from './content';
import { VISUAL_IDENTITIES, ART_PRODUCTION_BATCHES, BODY_PLAN_POLICY, artProductionStatus } from './visualIdentity';
import { LEGACY_FORM_ART_CANDIDATES } from './artCandidates';
import { CreatureContrastReview } from './CreatureContrastReview';
import { ClayDirection } from './ClayDirection';
import { CreatureBatchReview } from './CreatureBatchReview';
import { EvolutionStudiesReview } from './EvolutionStudiesReview';
const candidateFormArt = (id:string, form:number) => LEGACY_FORM_ART_CANDIDATES[id]?.[form] ?? null;

export function ArtProduction({onOpen}:{onOpen:(id:string,form?:number)=>void}) {
  const status=artProductionStatus();
  return <section className="cs-art-production">
    <div className="cs-section-title"><div><h2>Distinct creatures. One artistic world.</h2><p>Production priority: complete the roster identities before more score tuning.</p></div></div>
    <ol className="cs-production-steps"><li>Reserve 50 distinct bodies, materials and mature faces.</li><li>Approve contrasting mature anchors, then work through the roster in small groups.</li><li>Finish hatch forms and remaining evolution art without losing family identity.</li><li>Review matching, then integrate collection, trio, eggs, progression and saves.</li></ol>
    <div className="cs-stat-summary"><article><span>Identity briefs</span><strong>{VISUAL_IDENTITIES.length} / {status.totalFamilies}</strong><small>Drafts, not approved illustrations</small></article><article><span>Mature candidate families</span><strong>{status.matureFamilies} / {status.totalFamilies}</strong><small>{status.totalFamilies-status.matureFamilies} families still need mature art</small></article><article><span>Individual form candidates</span><strong>{status.candidateForms} / {status.totalForms}</strong><small>{status.firstForms} first-form candidates · form count provisional</small></article><article><span>Approved production forms</span><strong>{status.approvedForms} / {status.totalForms}</strong><small>Generation is not approval</small></article></div>
    <p className="cs-note"><strong>Creature-first roster rule:</strong> at least {BODY_PLAN_POLICY.creatureBodiedMinimum} of {BODY_PLAN_POLICY.totalFamilies} families must read immediately as animate, bondable creatures with locomotion, attention and expressive posture. At most {BODY_PLAN_POLICY.abstractExceptionMaximum} may be deliberate living-monument or abstract-organism exceptions. Shared rendering style does not mean shared bodies or faces. Baby-like eyes may recur in form 1 only; forms 2+ use family-specific attention anatomy. No ordinary animal with decorative accessories.</p>
    <details className="cs-explanation"><summary>Prioritised production queue · all 50 families</summary><p>First pass: mature identity anchors across the roster. Second pass: missing hatch forms, then remaining forms. Do not advance past the contrast gate by treating a generated candidate as approved.</p><ol>{ART_PRODUCTION_BATCHES.map(batch=><li key={batch.order}><strong>{batch.label}</strong><p>{batch.families.map(f=>`F${String(f.number).padStart(2,'0')} ${f.name}`).join(' · ')}</p></li>)}</ol></details>
    <EvolutionStudiesReview />
    <CreatureBatchReview />
    <ClayDirection />
    <CreatureContrastReview />
    <section className="cs-study-intro"><div><p className="cs-eyebrow">Interaction prototype · Bloom form 2 only</p><h3>What if the creature stepped out of its card?</h3><p>A tiny rounded 3D maquette. Open Bloom, choose “Try 3D study”, then tap the image. Its frozen poster and live figure use the same pose and camera.</p><button type="button" onClick={()=>onOpen('common-bloom-mite',2)}>Open the pop-out card ↗</button><small>Earlier geometry study; not rebuilt from the new comparison images. Not approved original-style art; not added to production-form counts.</small></div><img src="/assets/creatures/style-studies/bloom-rounded/model-poster-v1.png" alt="Rounded Bloom model study"/></section>
    <h3>Previous candidates in cards · review pending</h3>
    <div className="cs-art-contrast">{['common-twilight-seed','common-bloom-mite','mythic-echo-phoenix'].map(id=><button type="button" key={id} onClick={()=>onOpen(id,2)}><img src={candidateFormArt(id,2)!} alt={`${getFamily(id)?.name}, form 2 art candidate`} /><strong>{getFamily(id)?.name} · form 2</strong><span>{getFamily(id)?.emotions?.[0]}</span><small>{id==='common-bloom-mite'?'Revised tiny sensory eyes; still review for mammal-like muzzle and readable tenderness.':id==='mythic-echo-phoenix'?'Eyeless radial organism; check that intent reads as alive rather than an ornament.':'Seed/husk gaze; mature eye proportion and expression still under review.'}</small></button>)}</div>
    <h3>Full-roster identity reservations</h3><p className="cs-note">These are production briefs. Existing legacy art is not automatically certified by its brief. Unique text does not prove unique pictures; silhouette and face comparisons remain mandatory.</p>
    <div className="cs-art-ledger">{VISUAL_IDENTITIES.map(brief=>{const family=FAMILIES.find(f=>f.id===brief.familyId)!;return <details key={brief.familyId}><summary>F{String(family.number).padStart(2,'0')} · {family.name} · {brief.dominantEmotion}</summary><div className="cs-palette">{brief.palette.map(color=><span key={color}><i style={{background:color}} aria-hidden="true" />{color}</span>)}</div><p><strong>Body:</strong> {brief.silhouette}</p><p><strong>Material:</strong> {brief.material}</p><p><strong>Mature eyes / attention:</strong> {brief.matureAttention}</p><p><strong>Motion:</strong> {brief.motion}</p><p>{brief.form1Rule}</p><p>{brief.matureRule}</p><button type="button" onClick={()=>onOpen(brief.familyId)}>Inspect family and forms</button></details>;})}</div>
  </section>;
}
