/** Draft bridges from existing emotional/expression/practice briefs to motivations.
 * Kept separate from the audited snapshot: these are new design proposals, not recovered facts.
 * Tuple order is dominant / supporting / counterbalancing motivation, followed by rationale.
 */
export const ROSTER_BRIEFS: Record<string, readonly [string, string, string, string]> = {
  'common-sproutling': ['enforcer','devotee','pioneer','Earnest hope comes from keeping a small promise. Commitment supplies continuity; the first small return softens rigid standards.'],
  'common-pebble-spirit': ['peacemaker','sage','guardian','Serenity lowers the temperature before action. Perspective and a grounded boundary distinguish calm from merely avoiding change.'],
  'common-mossling': ['healer','caregiver','dreamer','Tender sorrow notices what needs recovery. Shelter supports it while cautious hope leaves room for a new beginning.'],
  'common-glowtail': ['scholar','analyst','explorer','Keen interest stays with one question long enough to understand it. Evidence narrows a route; exploration prevents study becoming indecision.'],
  'common-drift-pup': ['explorer','creator','pioneer','Playful delight tries a route before judging it. Imagination proposes variations; a first step brings wandering attention back to action.'],
  'common-stone-hopper': ['warlord','guardian','enforcer','Stubborn resolve meets resistance head-on and carries obligations. Protective purpose and reliable standards give that force direction; its practice is setting down excess load, not dominating others.'],
  'common-fern-fox': ['mentor','empath','explorer','Warm curiosity asks what helps another person grow. Attunement and discovery keep guidance open instead of taking their choice away.'],
  'common-dewling': ['peacemaker','empath','healer','Tranquillity restores enough space to listen. Receiving feelings and helping them settle distinguishes it from the more grounded Pebble Spirit.'],
  'common-root-whisp': ['devotee','shaman','sage','Longing follows a trusted tether. Meaningful ritual and remembered wisdom help commitment survive change without clinging.'],
  'common-garden-puff': ['connector','creator','peacemaker','Buoyant amusement makes room for shared ease. Playful expression and a softer atmosphere invite connection, while its pressure pattern avoids difficult feelings.'],
  'common-lichen-kit': ['challenger','guardian','engineer','Wariness checks whether changing conditions deserve trust. A protected constant and practical adaptation turn questioning into workable resilience.'],
  'common-river-bud': ['altruist','caregiver','devotee','Gratitude wants to give beyond itself. Everyday care and lasting commitment sustain that generosity; refilling first counters self-depletion.'],
  'common-petal-scout': ['explorer','detective','pioneer','Apprehensive curiosity follows one inviting clue. Investigation gives discovery direction and a small first move carries it past hesitation.'],
  'rare-luma-hatchling': ['creator','dreamer','empath','Shy anticipation protects an idea before showing it. Possibility and sensitivity explain both the tender expression and embarrassment at being seen.'],
  'rare-nebula-wisp': ['inventor','mystic','analyst','Fascination experiments at the edge of the understood. Wonder keeps uncertainty open; evidence makes the experiment safe and informative.'],
  'rare-dewleaf-sprite': ['guardian','caregiver','enforcer','Protective concern makes a kind guardrail. Care sets its purpose and a repeatable standard holds it; alarm can make the canopy too closed.'],
  'rare-aurora-finch': ['creator','connector','visionary','Exhilaration turns an inner direction into a visible signal. Connection seeks an audience and vision gives the expression somewhere to go.'],
  'rare-ember-sprout': ['pioneer','champion','inventor','Eager excitement wants the first move now. Challenge energizes it and experimentation makes a tiny start useful instead of merely hurried.'],
  'rare-solar-pika': ['visionary','champion','caregiver','Brave hope sees a warmer possibility worth attempting. Courage and care bring the future close enough for a small exposed act.'],
  'rare-comet-cub': ['strategist','engineer','commander','Quiet assurance orders a tangled plan into three moves. Reliable execution and responsibility support the sequence; uncertainty can become overplanning.'],
  'rare-bloom-seraph': ['mentor','healer','sage','Compassion helps another person regain ownership. Recovery and perspective guide its questions without deciding on their behalf.'],
  'rare-shard-marten': ['analyst','engineer','architect','Skeptical interest examines whether a joint actually works. Practical reliability and structural thinking turn scrutiny into a good-enough repeatable design.'],
  'rare-tide-lantern': ['diplomat','peacemaker','empath','Conciliatory warmth looks for a shared shore. De-escalation and understanding help agreement without erasing real differences.'],
  'rare-halo-staglet': ['guardian','devotee','caregiver','Protective affection stays close to what it shelters. Loyal attachment and everyday care explain a shield that must learn to remain open.'],
  'rare-gear-wing': ['engineer','architect','enforcer','Quiet satisfaction comes from a reliable sequence. Structure and consistent standards carry recurring burdens out of memory and into a system.'],
  'rare-mirage-pup': ['rebel','creator','challenger','Mischievous amusement changes the rules of a heavy task. Invented expression and questioning open alternatives; commitment remains its pressure point.'],
  'rare-crown-drifter': ['pioneer','visionary','devotee','Adventurous anticipation chooses a new horizon. A future worth moving toward and a tether of care counter endless restless departures.'],
  'mythic-starhorn-seraph': ['mystic','philosopher','sage','Solemn awe searches for a practical north. Meaning and perspective ground reverence in an action instead of an answer it cannot verify.'],
  'mythic-voidlight-familiar': ['devotee','visionary','detective','Quiet trust carries a difficult vision into darkness. An imagined future supplies direction, while verification keeps trust from becoming blind certainty.'],
  'mythic-sunflare-kirin': ['champion','mentor','altruist','Heartening confidence encourages courage in others. Development and outward generosity give achievement a shared purpose; restoring warmth prevents depletion.'],
  'mythic-dreamroot-ancient': ['philosopher','sage','dreamer','Contemplative wonder asks what an experience means. Wisdom and possibility deepen reflection; wistful distance invites a return to participation.'],
  'mythic-orbit-vulpine': ['explorer','devotee','scholar','Contented curiosity revisits a familiar route deeply. Attachment and sustained learning distinguish it from a scout always seeking the unfamiliar.'],
  'mythic-astral-titanet': ['architect','inventor','guardian','Cautious optimism designs a structure for possibility. Experiment and protection improve it, but worry can keep adding unnecessary safeguards.'],
  'mythic-solstice-sylph': ['shaman','dreamer','healer','Wistful hope marks a season ending. Imagining the next season and tending loss make transition meaningful without denying sadness.'],
  'mythic-nightbloom-drake': ['guardian','empath','rebel','Guarded affection watches the pace of approach. Sensitivity and self-chosen boundaries let trust grow without demanding immediate openness.'],
  'mythic-prism-warden': ['guardian','altruist','architect','Compassionate vigilance protects a shared center. Outward purpose and a containing structure distinguish its shelter from possessive protection.'],
  'mythic-aurora-maned-cat': ['creator','champion','devotee','Poised anticipation gathers courage to be seen. Commitment to expression and the challenge of an imperfect public act counter embarrassment.'],
  'mythic-cosmos-songbird': ['connector','diplomat','scholar','Attentive delight listens before sharing an insight. Common language and careful understanding help another person remember it.'],
  'mythic-infinity-sprite': ['sage','philosopher','inventor','Patient amazement holds several interpretations. Meaning and alternative explanations widen perspective without losing one practical anchor.'],
  'common-hearth-hare': ['caregiver','devotee','guardian','Affectionate concern maintains a warm place over time. Loyalty and boundaries reserve some of that warmth for the one giving it.'],
  'rare-aura-otter': ['empath','healer','guardian','Empathic concern receives another feeling without becoming it. Recovery and a personal boundary allow care without absorbing everything.'],
  'rare-threadtail-weaver': ['connector','devotee','architect','Fondness tends reciprocal threads. Commitment and deliberate structure help attention reach the relationships that matter most.'],
  'rare-lantern-lynx': ['detective','analyst','sage','Watchful doubt seeks enough evidence. Analysis checks the clue and perspective supplies a stopping rule rather than endless investigation.'],
  'mythic-grove-caller': ['shaman','enforcer','healer','Reverence turns change into a repeatable ritual. Gentle consistency and recovery make transformation something practiced rather than merely declared.'],
};
