import json,copy,hashlib,pathlib
p=pathlib.Path('.img2threejs/island-003-v2/keep-frozen-world'); old=pathlib.Path('.img2threejs/island-003-frostmoon-upgrade/aurora-keep-l3')
ref='docs/gauntlets/island-003-v2/concepts/02-frostmoon-frozen-ocean-goal.png'
turn='docs/visual-references/island-003-frostmoon-upgrade/secondary-inferred/landmark-turnarounds/003-aurora-keep-turnaround-v001.png'
def save(name,x): (p/name).write_text(json.dumps(x,indent=2)+'\n')
analysis={'scope':'Representative macro slice: Aurora Keep, continuous deep frozen ocean and terrain, economical planting. Other landmarks and Archive unchanged. No material/detail completion claimed.','referenceHierarchy':[{'path':x,'sha256':hashlib.sha256(pathlib.Path(x).read_bytes()).hexdigest(),'authority':a} for x,a in [(ref,'user-approved V002 hierarchy and frozen-world direction'),(turn,'approved prior Keep identity; new hierarchy supersedes former height'),('docs/gauntlets/island-003-v2/baseline-v002/overview.png','actual locked camera/route before implementation')]],'observed':['Central Keep is much taller and more voluminous than outer landmarks, with a continuous high great hall, paired round front turrets and copper gables.','The concept has continuous white frozen sea and pale-blue thick ice strata; no exposed dark ocean or loose floating floes.','Snow-covered terrain connects every landmark and encloses a coherent ridge beyond route.','Snow fir banks use varied tall silhouettes with visible horizontal branch lobes.','Prior Keep identity includes two brass ridge rings, front gallery, lower side wings and rear service entrance.'],'inferred':['Exact V2 rear ice perimeter and subsurface depth are inferred from user many-metres-deep requirement; geometry shows 2.8 world-unit ice cliff atop frozen sea.','Only actual runtime 36-tile route and current camera are authoritative, not approximate concept route.','Keep central hall vertical construction grows through funded courses; footprint remains original.','Planting in representative slice uses shared low-poly branch modules; final juniper/rowan details follow macro approval.'],'suitability':{'verdict':'conditional','reason':'Concept is sufficient for composition and ice hierarchy, prior five-view sheet for architecture. Exact scene pixel registration is not valid because concept route differs; actual fixed POV and silhouette review govern, with full-image Tier1 diagnostics retained but not misrepresented.'},'projection':{'required':False,'reason':'Procedural 360-degree architecture, frozen terrain and vegetation. No photo-projection or baked shading; neutral clay macro geometry first.'},'materialEvidence':{'deferred':True,'reason':'Representative naked macro only; inherited approved palette used in assembly. No new PBR claim or extracted maps. Material evidence and wiring are deferred until macro approval.'},'familyBudget':{'family':'continuous-tall-hall-and-solid-ice-v001','maxFamilies':2,'blockoutsPerFamily':1,'correctionsPerFamily':1,'maxIndependentReviews':4}}
save('image-analysis.json',analysis)
a=json.load(open(p/'pre-spec-assessment.json')); olda=json.load(open(old/'pre-spec-assessment.v1.json'))
a['preSpecAssessment']=copy.deepcopy(olda['preSpecAssessment']);a['qualityContract']=copy.deepcopy(olda['qualityContract']);a['sourceImage']=ref;a['preSpecAssessment']['sourceImage']=ref
pc=a['preSpecAssessment'];pc['objectClass']['primaryType']='dominant winter civic keep and contiguous deep-frozen environment';pc['complexity']['estimatedCounts'].update(macroComponents=23,mesoComponents=10,microFeatureGroups=12,repetitionSystems=8)
pc['complexity']['reasoning']+=analysis['observed'][:4];pc['resolvedUnknowns']=analysis['inferred'];pc['unknownsToResolveBeforeImplementation']=[]
q=a['qualityContract'];q['definitionOfDone']=analysis['observed'][:5]+['Worst required macro view >=0.85; all 36 route tiles remain in locked overview frame, no tall foreground planting obscures interaction corridor.','Static terrain/pressure-ridge/vegetation roots batch separately from animated mission props; no added unbounded mesh repetition.'];q['minimumSpecDepth']['macroComponents']=15;q['minimumSpecDepth']['reviewViewpoints']=9
for id,name,criteria in [('continuous-frozen-world','Continuous deep frozen ocean',['Opaque frozen sea with many-metres-thick stratified shelf, no open-water gaps or floating floes.']),('economical-planting','Branched snow fir banks',['Varied branch silhouettes in coherent banks outside route and plots; shared/merged geometry.'])]:q['featureGroups'].append({'id':id,'name':name,'required':True,'qualityCriteria':criteria,'evidenceRefs':['frozen-ocean-v002'],'failureModes':['disconnected floaters','route occlusion','expensive repeated draw calls']})
save('pre-spec-assessment.json',a)
d=json.load(open(old/'object-sculpt-spec.v1.json'));d['targetName']=a['targetName'];d['targetId']='island-003-v2-keep-frozen-world';d['sourceImage']=ref;d['preSpecAssessment']=pc;d['qualityContract']=q;d['localSpecSearch']=a['localSpecSearch'];d['reviewHistory']=[];d['tier1Results']=[];d['visualEvidence']=[];d['scores']={};d['sculptPipeline']['currentPass']='blockout';d['sculptPipeline']['completedPasses']=[]
d['selfCorrectLoop']['visualAcceptance']['threshold']=.85;d['selfCorrectLoop']['visualAcceptance']['featureReviewPolicy']['criticalDefaultThreshold']=.85;d['qualityTargets']['targetFidelity']=.85;d['qualityTargets']['reviewViewpoints']=['front','front-left-40','left-80','rear-left-120','rear-160','rear-right-200','right-240','front-right-280','high-320']
d['viewEvidence']=[x for x in d['viewEvidence'] if x['id'] in ['full-object','five-view-turnaround']];d['viewEvidence'][0]['observations']=analysis['observed'];d['viewEvidence'].append({'id':'frozen-ocean-v002','view':'overview','imageRegion':{'x':0,'y':0,'width':1,'height':1,'units':'normalized'},'observations':analysis['observed'],'confidence':.95})
d['assumptions']=analysis['inferred'];d['referenceCamera']['note']='Actual runtime locked camera is approval authority; concept camera not reproduced. Nine-angle neutral naked Keep plus whole assembled phone views.'
# Carry identity definitions, replacing stale prototype dimensions for owned macro masses.
sizes={'raised-frost-stone-foundation':(3.72,.42,3.72),'central-great-hall-shell':(1.82,2.52,1.4),'main-snow-copper-gable-roof':(2.14,1.04,1.7),'left-round-guard-tower':(.8,1.78,.8),'right-round-guard-tower':(.8,1.78,.8)}
for c in d['componentTree']:
 if c['id'] in sizes: c['dimensions']=dict(zip(['width','height','depth'],sizes[c['id']]),units='world')
for id,name,primitive,dimensions,material in [('continuous-ice-ocean','Continuous solid frozen sea','box',(140,3,140),'frost-stone'),('connected-terrain-shelf','Connected snow and thick blue ice shelf','extrude',(13.8,2.8,12.8),'frost-stone'),('pressure-ridge-banks','Grounded ice pressure ridges','instanced-cluster',(14,1,14),'snow'),('snow-fir-bank','Economical branched snow fir banks','instanced-cluster',(14,2.8,14),'dark-timber')]:
 c=copy.deepcopy(d['componentTree'][1]);c.update(id=id,name=name,primitive=primitive,parent='root',material=material,materialLayers=[material],localFeatures=[],evidenceRefs=['frozen-ocean-v002']);c['dimensions']=dict(zip(['width','height','depth'],dimensions),units='world');c['transform']['position']=[0,0,0];c['attachment']['parentSocket']='root-socket';d['componentTree'].append(c)
 for b in d['buildPasses']: b['componentRefs'].append(id)
d['performanceBudget'].update(representativeScope='Static semantic roots; measure whole-world draw calls before expansion. Full high target <=175 calls / <=180000 triangles; parent integrates batching.')
# Select five salient systems in one full pair; inherited feature records may carry old approval, so reset entirely.
d['featureReviewTargets']=[{'id':id,'name':name,'tier':'critical','threshold':.85,'componentRefs':refs,'passIds':['blockout'],'evidenceRefs':['frozen-ocean-v002','five-view-turnaround']} for id,name,refs in [('keep-dominance','Dominant continuous great hall',['central-great-hall-shell']),('turret-roof-identity','Paired turrets, copper gables and two rings',['left-round-guard-tower','right-round-guard-tower','ridge-ring-beacon-system']),('ice-continuity','Deep continuous frozen ocean',['continuous-ice-ocean','connected-terrain-shelf']),('planting-hierarchy','Economical coherent snow fir banks',['snow-fir-bank']),('route-clearance','Fixed route visibility and plot clearance',['root'])]]
save('object-sculpt-spec.json',d)
