import { useEffect, useMemo, useState } from 'react';
import { listCrystalMinersTelemetry, type RecentTelemetryEventRow } from '../../services/adminTelemetry';
import { summarizeMinerTelemetry } from '../../services/crystalMinersAnalytics';
export function CrystalMinersTelemetryPanel({lookbackDays}:{lookbackDays:number}) {
  const [events,setEvents]=useState<RecentTelemetryEventRow[]>([]);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;void listCrystalMinersTelemetry(lookbackDays).then(result=>{if(active){setEvents(result.data);setError(result.error?.message??'');}});return()=>{active=false;};},[lookbackDays,refresh]);
  const metrics=useMemo(()=>summarizeMinerTelemetry(events),[events]);
  return <section aria-label="Crystal Miners balance telemetry"><h4>Crystal Miners · event loop</h4><button type="button" className="btn" onClick={()=>setRefresh(n=>n+1)}>Refresh mining data</button><p className="account-panel__hint">Last {lookbackDays} days · {events.length} sampled events. Telemetry-enabled players only; local previews are excluded.{events.length===1000?' The 1,000-event limit was reached; this is a recent sample.':''}</p>{error&&<p role="status">Could not load mining data: {error}</p>}<p>{metrics.blocked} ticket shortages · {metrics.returns} returns to island earning · {metrics.offers} supply-offer visits</p>{metrics.levels.length===0?<p>No mining attempts recorded in this window.</p>:<div style={{overflowX:'auto'}}><table><caption>Attempt outcomes by cavern (not unique-player conversion)</caption><thead><tr><th>Cavern</th><th>Attempts</th><th>Cleared</th><th>Clear rate</th><th>Ore / drop</th><th>Chests / drop</th><th>Avg forge</th><th>Avg top tier</th></tr></thead><tbody>{metrics.levels.map(row=><tr key={row.level}><td>{row.level}</td><td>{row.attempts}</td><td>{row.clears}</td><td>{Math.round(row.clears/row.attempts*100)}%</td><td>{Math.round(row.ore/row.attempts)}</td><td>{(row.chests/row.attempts).toFixed(1)}</td><td>{(row.forge/row.attempts).toFixed(1)}</td><td>{(row.highestTier/row.attempts).toFixed(1)}</td></tr>)}</tbody></table></div>}{metrics.errors.length>0&&<><h5>Failures and delayed sync</h5><ul>{metrics.errors.map(row=><li key={row.reason}>{row.reason}: {row.count}</li>)}</ul></>}</section>;
}
