export const GAME_CONFIG = {
  ANIMATION: {
    TILE_BREAK_DURATION: 150,
    TILE_REVEAL_DELAY: 120,
    TILE_SCALE_SPRING: {
      type: 'spring' as const,
      stiffness: 300,
      damping: 22,
    },
    PULSE_DURATION: 0.5,
    SHAKE_FRAMES: [0, -1.5, 1.5, 0] as number[],
    SCALE_FRAMES: [1, 0.9, 1.05, 1] as number[],
    
    CELEBRATION_FOUND_DURATION: 500,
    CELEBRATION_BOARD_TRANSITION_DURATION: 800,
    CELEBRATION_CONFETTI_START_DELAY: 400,
    CELEBRATION_CONFETTI_DURATION: 2500,
    CELEBRATION_MODAL_DELAY: 2000,
    CELEBRATION_AUTO_ADVANCE_DELAY: 3500,
  },
  
  SCORING: {
    PER_OBJECT: 100,
    TOOL_BONUS: 10,
    LEVEL_COMPLETE_BONUS: 500,
  },
  
  REWARDS: {
    COINS_PER_OBJECT: 50,
    COINS_PER_TOOL_LEFT: 10,
    COINS_LEVEL_COMPLETE: 100,
    MILESTONE_LEVELS: [4, 8, 12, 16, 20],
    MILESTONE_REWARDS: [150, 300, 500, 750, 1000],
  },
  
  UI: {
    BOARD_MAX_WIDTH: '600px',
    BOARD_PADDING_DEFAULT: 16,
    BOARD_PADDING_COMPACT: 8,
    TILE_GAP_LARGE: 6,
    TILE_GAP_SMALL: 8,
    TILE_GAP_THRESHOLD: 7,
    LOW_TOOLS_THRESHOLD: 2,
  },
  
  VALIDATION: {
    MIN_BOARD_SIZE: 4,
    MAX_BOARD_SIZE: 8,
    MIN_TOOLS: 1,
  },
} as const

export type GameConfig = typeof GAME_CONFIG
