from pathlib import Path
import json,copy,hashlib,subprocess
p=Path('.img2threejs/island-003-v2/moonwell-thermal');old=Path('.img2threejs/island-003-frostmoon-upgrade/moonwell-observatory-l3');ref='docs/visual-references/island-003-frostmoon-upgrade/secondary-inferred/landmark-goals/003-moonwell-observatory-l3-goal-v001.png'
def save(n,x):(p/n).write_text(json.dumps(x,indent=2)+'\n')
a=json.load(open(p/'pre-spec-assessment.json'));d=json.load(open(old/'object-sculpt-spec.json'))
analysis={'scope':'Bounded additive Moonwell geometry + frozen-to-warm presentation roles, preserving approved observatory identity. No gameplay authority.','source':ref,'sha256':hashlib.sha256(Path(ref).read_bytes()).hexdigest(),'observed':['Circular stone basin under three open timber/copper arches meeting a crown.','Nested brass rings on a diagonal spindle above basin; supported telescope and rear chart service.','Pale blue-white contained basin and dark timber/copper exterior, no purple magic.'],'userOverride':'September user explicitly requires all-complete L3 to begin wholly frozen; optional tile/action thaws basin. Warm reference basin is final thermal state only.','supersededReference':'landmark-turnarounds/003-moonwell-observatory-turnaround-v001.png is obsolete purple-gazebo image and was inspected/rejected as authority.','inferred':['Six opaque shallow ice sectors cover entire basin and recede independently under presentation fraction.','Five modest bubbles and three steam puffs exist only as explicitly tagged hidden thermal nodes before heating.','Existing QuadraticBezier control y=height is not an apex; set control y=2*height-.53 to meet existing crown without moving outer envelope.'],'suitability':{'verdict':'pass','reason':'Actual approved multi-view goal supports structure; later explicit user cold-state instruction overrides initial liquid surface.'},'projection':'Not applicable to procedural multi-view object; no baked studio lighting.','materialEvidence':'Reuse approved procedural palette and existing material-evidence.md. Opacity/visibility are explicit user state changes; no new extracted PBR claim.'}
save('image-analysis.json',analysis)
a['preSpecAssessment']=d['preSpecAssessment'];a['qualityContract']=d['qualityContract'];a['preSpecAssessment']['sourceImage']=ref;a['preSpecAssessment']['resolvedUnknowns']+=analysis['inferred'];a['preSpecAssessment']['unknownsToResolveBeforeImplementation']=[]
a['qualityContract']['definitionOfDone']+=['L1/L2 funded vertex transforms persist unchanged through L3.','Cold default completely opaque basin with water/bubble/steam invisible; explicit per-mesh ice/water/heater/bubble/steam roles survive board compaction.','Rib true apex meets crown; copper cladding does not duplicate underlying timber or feet.']
save('pre-spec-assessment.json',a);save('detail-inventory.json',{'reusedFrom':str(old/'detail-inventory.json'),'scope':'Existing approved architecture details unchanged; re-inspected full goal three survey views','detailInventory':d['preSpecAssessment']['detailInventory'],'newPresentationSystems':['opaque-frozen-sector-cover','separate-warm-water','heater-rim','bounded-bubble-system','bounded-steam-system']})
d['targetName']=a['targetName'];d['targetId']='island-003-v2-moonwell-thermal';d['sourceImage']=ref;d['preSpecAssessment']=a['preSpecAssessment'];d['qualityContract']=a['qualityContract'];d['localSpecSearch']=a['localSpecSearch'];d['reviewHistory']=[];d['visualEvidence']=[];d['scores']={};d['sculptPipeline']['currentPass']='blockout';d['sculptPipeline']['completedPasses']=[];d['sculptPipeline']['blockedReason']='';d['qualityTargets']['targetFidelity']=.85;d['selfCorrectLoop']['visualAcceptance']['threshold']=.85
d['assumptions']+=analysis['inferred']+[analysis['userOverride']];d['thermalContract']={'roles':['ice','water','heater','bubble','steam'],'tag':'mesh.userData.moonwellThermalRole','controllerOwner':'parent Island3MoonwellThermalPresentation.ts','noGameplayWrites':True,'staticBatchPredicate':'exclude every mesh with a thermalRole','coldDefault':{'ice':True,'water':False,'bubble':False,'steam':False},'bounds':{'basinRadius':.63,'waterY':.65,'iceY':.68},'repetitions':{'ice':6,'bubble':5,'steam':3}}
save('object-sculpt-spec.json',d)
