import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createMultiplierHologram} from '../../src/features/gamification/level-worlds/components/living-controller/multiplier-hologram.js';
import {PILL,MAX_JUMP_SECONDS,maxJumpFeedback,multiplierAppearance as appearance} from '../../src/features/gamification/level-worlds/components/living-controller/multiplier-hologram.js';
assert.equal(MAX_JUMP_SECONDS,.54);
assert.ok(maxJumpFeedback(.54*.34).offset>.09);
assert.ok(maxJumpFeedback(.54*.64).offset<0);
assert.equal(maxJumpFeedback(.54).offset,0);
assert.equal(maxJumpFeedback(.2,true).offset,0);
assert.ok(maxJumpFeedback(.2,true).glow>1);
assert.ok(PILL.width>PILL.height*4);
assert.equal(appearance(1,20,24).atMax,false);
assert.equal(appearance(1,1,24).atMax,false);
assert.equal(appearance(20,20,500).atMax,true);
assert.ok(appearance(10,20,500).level>appearance(2,20,500).level);
assert.equal(appearance(20,20,0).powered,false);
assert.notEqual(appearance(20,20,500).color,appearance(1,20,500).color);
console.log('PASS: wide pill, player-relative power, MAX threshold and depleted power');
const labels=[];
globalThis.document={createElement:()=>({getContext:()=>({clearRect(){},fillRect(){},fillText(text){labels.push(text);}})})};
const pill=createMultiplierHologram(THREE);
pill.update({multiplier:2,maximum:20,dice:500},1,true);
assert.deepEqual(labels,['×2'],'Resting pill prioritizes one large crisp number');
labels.length=0;
pill.update({multiplier:20,maximum:20,dice:500},2,true);
assert.ok(labels.includes('MAX')&&labels.includes('×20'));
assert.equal(pill.root.position.y,PILL.y,'Loading at MAX must not fake a click');
pill.update({multiplier:20,maximum:20,dice:500,multiplierMaxJumping:true},3,false);
pill.update({multiplier:20,maximum:20,dice:500,multiplierMaxJumping:true},3.18,false);
assert.ok(pill.root.position.y>PILL.y,'Canonical MAX click animates pill');
pill.update({multiplier:20,maximum:20,dice:500},3.6,false);
assert.equal(pill.root.position.y,PILL.y,'Pill settles back at its original anchor');
pill.root.traverse(object=>{
 const positions=object.geometry?.attributes.position.array;
 if(positions)assert.ok(positions.every(Number.isFinite),'Finite capsule and rim geometry');
 object.geometry?.dispose();
 object.material?.map?.dispose();object.material?.dispose();
});
delete globalThis.document;
console.log('PASS: real Three.js pill geometry and multiplier/cost/MAX canvas labels');
