import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import type { Island3DQuality, Island5LandmarkDefinition } from './island5ThreePilotContract';
import type { Island9HeartshaftMaterials } from './Island9HeartshaftThreeWorld';
import type { IslandConstructionFactoryOptions } from './IslandConstructionAuthoring';

/** Unwired family14/unit1. Hidden depth and rear closure are inferred from one source projection. */
export const SWITCHYARD_SOURCE_PROFILE = { family:'occupied-pressure-switchyard',globalFamily:14,unitFamily:1,sourceCrop:'pressure-switchyard-exact-v001.png',anchorUncertaintyPixels:18,sourceProjected:{chamber:[222,178,349,283],crown:[247,79,338,180],frontBowl:[196,275,283,350]},footprintRadius:1.53,receiving:{bottom:-.05,top:.24,radius:1.43,segments:16},inference:'Six heavy contour ribs, hidden cross-sections and auxiliary depth are economical inferred closures, not recovered source counts.' };
type Phase = 1 | 2 | 3 | 4 | 5;
const V = (x: number, y: number, z: number) => new THREE.Vector3(x,y,z);
function owner(id: string, level: number) {
  const g = new THREE.Group(); g.name = id; g.userData = { partId:id, constructionBuildLevel:level, keepSeparate:true, sculptRuntime:{parts:[{id,nodeName:id}],sockets:{},presentationOnly:true} }; return g;
}
function socket(g: THREE.Group, name: string, p: THREE.Vector3) {
  const n = new THREE.Object3D(); n.name=name;n.position.copy(p);n.userData.socket=true;g.add(n);g.userData.sculptRuntime.sockets[name]={nodeName:name,localPosition:p.toArray()};return n;
}
function mesh(g: THREE.Group,name:string,geometry:THREE.BufferGeometry,material:THREE.Material,at=V(0,0,0),phase:Phase=2) {
  const n=new THREE.Mesh(geometry,material);n.name=name;n.position.copy(at);n.castShadow=n.receiveShadow=true;
  n.userData={partId:g.userData.partId,constructionBuildLevel:g.userData.constructionBuildLevel,constructionStage:phase,constructionPreserveOwnership:true};g.add(n);return n;
}
function solidProfile(points:number[][],n:number) {
  const strips=points.slice(1).map((b,i)=>{
    const a=points[i],g=new THREE.LatheGeometry([new THREE.Vector2(a[0],a[1]),new THREE.Vector2(b[0],b[1])],n);
    const normal=g.getAttribute('normal'),dy=b[1]-a[1],dr=b[0]-a[0],length=Math.hypot(dy,dr);
    for(let j=0;j<=n;j++)for(let k=0;k<2;k++)normal.setXYZ(j*2+k,Math.sin(j/n*Math.PI*2)*dy/length,-dr/length,Math.cos(j/n*Math.PI*2)*dy/length);
    return g;
  });
  const merged=mergeGeometries(strips,false)!;strips.forEach(g=>g.dispose());
  // Remove only the zero-area pole triangles generated by standard lathe caps.
  const pos=merged.getAttribute('position'),idx=merged.index!,indices:number[]=[];
  for(let i=0;i<idx.count;i+=3){const ids=[idx.getX(i),idx.getX(i+1),idx.getX(i+2)],v=ids.map(j=>new THREE.Vector3().fromBufferAttribute(pos,j));if(v[1].sub(v[0]).cross(v[2].sub(v[0])).lengthSq()>1e-18)indices.push(...ids);}
  merged.setIndex(indices);return merged;
}
function crownSector(points:number[][],start:number,width:number){
 const vertices:number[]=[],indices:number[]=[],count=points.length;
 for(const angle of [start,start+width])for(const [r,y]of points)vertices.push(Math.sin(angle)*r,y,Math.cos(angle)*r);
 for(let i=0;i<count;i++){const j=(i+1)%count;indices.push(i,j,count+i,j,count+j,count+i);}
 const faces=THREE.ShapeUtils.triangulateShape(points.map(([r,y])=>new THREE.Vector2(r,y)),[]);
 for(const [a,b,c]of faces)indices.push(a,c,b,count+a,count+b,count+c);
 for(let i=0;i<indices.length;i+=3)[indices[i+1],indices[i+2]]=[indices[i+2],indices[i+1]];
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(vertices.length/3*2).fill(0),2));return g;
}
function collar(g:THREE.Group,name:string,r:number,inner:number,y:number,h:number,m:THREE.Material,n:number) {
  return mesh(g,name,solidProfile([[inner,y-h/2],[r,y-h/2],[r,y+h/2],[inner,y+h/2],[inner,y-h/2]],n),m,V(0,0,0),3);
}
function rod(g:THREE.Group,name:string,a:THREE.Vector3,b:THREE.Vector3,r:number,m:THREE.Material,phase:Phase=3){const d=b.clone().sub(a),n=mesh(g,name,new THREE.CylinderGeometry(r,r,d.length(),10),m,a.clone().lerp(b,.5),phase);n.quaternion.setFromUnitVectors(V(0,1,0),d.normalize());return n;}
function batch(g:THREE.Group){
  const sets=new Map<string,THREE.Mesh[]>();for(const n of g.children)if(n instanceof THREE.Mesh){const key=(n.material as THREE.Material).uuid+':'+n.userData.constructionStage;const a=sets.get(key)??[];a.push(n);sets.set(key,a);}
  for(const nodes of sets.values()){if(nodes.length<2)continue;const inputs=nodes.map(n=>{n.updateMatrix();const a=n.geometry.index?n.geometry.toNonIndexed():n.geometry.clone();a.applyMatrix4(n.matrix);return a;});const geo=mergeGeometries(inputs,false);inputs.forEach(g=>g.dispose());if(!geo)throw Error('Switchyard batch attributes incompatible');const n=mesh(g,g.name+'_PHASE_'+nodes[0].userData.constructionStage,geo,nodes[0].material as THREE.Material,V(0,0,0),nodes[0].userData.constructionStage);n.userData.sourceMeshes=nodes.map(n=>n.name);nodes.forEach(n=>{g.remove(n);n.geometry.dispose();});}
}
/** Closed lobed pressure contents, with real recessed valleys rather than primitive spheres. */
function contents(bottom:number,top:number,radius:number,segments:number,rows:number,offset:number){
  const pos:number[]=[],idx:number[]=[];
  for(let j=0;j<=rows;j++){const t=j/rows,shape=t<.16?.34+t*2.1:t<.44?.676+(t-.16)*1.05:t<.68?.97-(t-.44)*.48:t<.87?.855-(t-.68)*1.42:.585-(t-.87)*1.8846;for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2;const lobe=1-.26*(.5+.5*Math.cos(5*a+offset))*(Math.sin(Math.PI*t));const r=radius*shape*lobe;pos.push(Math.sin(a)*r+.025*Math.sin(Math.PI*t)*Math.sin(offset),bottom+(top-bottom)*t,Math.cos(a)*r*.92);}}
  for(let j=0;j<rows;j++)for(let i=0;i<segments;i++){const k=(i+1)%segments,a=j*segments+i,b=j*segments+k,c=(j+1)*segments+i,d=(j+1)*segments+k;idx.push(a,c,b,b,c,d);}
  for(const end of [0,rows]){const center=pos.length/3;pos.push(0,end?top:bottom,0);for(let i=0;i<segments;i++){const a=end*segments+i,b=end*segments+(i+1)%segments;idx.push(...(end?[center,b,a]:[center,a,b]));}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx.flatMap((_,i)=>i%3===0?[idx[i],idx[i+2],idx[i+1]]:[]));g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(pos.length/3*2).fill(0),2));const flat=g.toNonIndexed();g.dispose();flat.computeVertexNormals();return flat;
}
function chamber(root:THREE.Group,id:string,level:number,bottom:number,top:number,radius:number,cast:THREE.Material,core:THREE.Material,n:number){
  const g=owner(id,level);root.add(g);g.userData.chamber={bottom,top,radius,occupied:true};
  mesh(g,id+'_OCCUPIED_SCALLOPED_ENVELOPE',contents(bottom,top,radius-.055,20,10,level*.67),core,V(0,0,0),3);
  mesh(g,id+'_LOWER_RECEIVER',solidProfile([[.17,bottom],[.35,bottom],[.43,bottom+.065],[.43,bottom+.14],[.36,bottom+.20],[.17,bottom+.20],[.17,bottom]],n),cast,V(0,0,0),3);mesh(g,id+'_UPPER_RECEIVER',solidProfile([[.17,top-.20],[.36,top-.20],[.40,top-.12],[.40,top-.06],[.34,top],[.17,top],[.17,top-.20]],n),cast,V(0,0,0),3);
  const angles=[.12,1.04,2.03,3.12,4.17,5.20];const contacts:{rib:number;end:string;point:number[];receiverRadius:number[]}[]=[];
  angles.forEach((a,i)=>{
    const points=[0,.15,.35,.55,.77,1].map(t=>{const r=.30+(radius-.30)*Math.pow(Math.sin(Math.PI*t),.82);return V(Math.sin(a)*r,bottom+(top-bottom)*t,Math.cos(a)*r);});
    const curve=new THREE.CatmullRomCurve3(points,false,'centripetal'),vertices:number[]=[],indices:number[]=[],steps=20;
    for(let j=0;j<=steps;j++){const t=j/steps,p=curve.getPoint(t),radial=V(Math.sin(a),0,Math.cos(a)),side=V(Math.cos(a),0,-Math.sin(a)),width=.055+.013*Math.abs(t-.5)*2;
      for(const [w,d] of [[-width,-.035],[width,-.035],[width,.035],[-width,.035]])vertices.push(...p.clone().addScaledVector(side,w).addScaledVector(radial,d).toArray());}
    for(let j=0;j<steps;j++)for(let k=0;k<4;k++){const l=(k+1)%4,A=j*4+k,B=j*4+l,C=(j+1)*4+k,D=(j+1)*4+l;indices.push(A,B,C,B,D,C);}indices.push(0,2,1,0,3,2);const e=steps*4;indices.push(e,e+1,e+2,e,e+2,e+3);
    const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setIndex(indices.flatMap((_,i)=>i%3===0?[indices[i],indices[i+2],indices[i+1]]:[]));geo.computeVertexNormals();geo.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(vertices.length/3*2).fill(0),2));mesh(g,id+'_BOWED_LOAD_RIB_'+i,geo,cast,V(0,0,0),3);
    for(const [end,p]of [['lower',points[0]],['upper',points[points.length-1]]] as const){socket(g,id+'/rib-'+i+'-'+end,p);contacts.push({rib:i,end,point:p.toArray(),receiverRadius:[.17,end==='lower'?.39:.36]});}
  });
  socket(g,id+'/bottom',V(0,bottom,0));socket(g,id+'/top',V(0,top,0));g.userData.ribContacts=contacts;batch(g);return g;
}

export function buildIsland9SeismicSwitchyardStructure(definition:Island5LandmarkDefinition,level:0|1|2|3,quality:Island3DQuality,_materials:Island9HeartshaftMaterials,_options:IslandConstructionFactoryOptions={}){
 const root=owner('seismic-switchyard-structural-assembly',0);root.name='ISLAND_9_HEARTSHAFT_EVENT_ROOT';root.position.set(...definition.position);root.userData.family=SWITCHYARD_SOURCE_PROFILE.family;root.userData.authoringProfile=SWITCHYARD_SOURCE_PROFILE;root.userData.approval='unreviewed';root.userData.constructionPreviewImplemented=false;
 socket(root,'ISLAND_9_EVENT_FOCUS_SOCKET',V(0,1.5,0));
 const mat=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:.82,metalness:0}),cast=mat(0xa0a5a7),core=mat(0x626c72),stone=mat(0x747b7e),n=quality==='high'?40:quality==='medium'?32:24;
 const add=(id:string,l:number)=>{const g=owner(id,l);root.add(g);return g;};
 const profile=(g:THREE.Group,name:string,points:number[][],at:THREE.Vector3,phase:Phase=4)=>mesh(g,name,solidProfile(points,n),cast,at,phase);
 const base=add('switchyard-foundation',0);mesh(base,'SWITCHYARD_FROZEN_RECEIVING_FOOTPRINT',new THREE.CylinderGeometry(1.43,1.43,.29,16),stone,V(0,.095,0),1);socket(base,'switchyard/foundation-seat',V(0,.24,0));if(!level)return root;
 const cradle=add('lower-manifold-and-cradle',1);
 profile(cradle,'OCCUPIED_BRANCHING_MANIFOLD',[[0,.24],[.53,.24],[.60,.36],[.49,.74],[.30,1.0],[.31,1.25],[0,1.25]],V(.1,0,-.2),2).scale.z=.75;
 rod(cradle,'FORWARD_BOWL_LOAD_NECK',V(.1,.8,-.2),V(-.28,.78,.40),.15,cast,2);
 rod(cradle,'RIGHT_FEED_MANIFOLD',V(.1,.65,-.2),V(.44,.70,.50),.11,cast,2);
 socket(cradle,'switchyard/chamber-seat',V(.1,1.25,-.2));batch(cradle);
 const bulb=chamber(root,'occupied-ovoid-chamber',1,1.25,2.72,.65,cast,core,n);bulb.position.set(.1,0,-.2);bulb.scale.z=.91;
 const bowl=add('front-pressure-bowl',1);rod(bowl,'BOWL_GROUNDED_SEAT',V(-.28,.24,.63),V(-.28,.75,.63),.22,cast,2);const bowlMesh=profile(bowl,'OCCUPIED_FLATTENED_PRESSURE_BOWL',[[0,.70],[.24,.70],[.40,.77],[.50,.89],[.52,1.01],[.55,1.035],[.55,1.12],[.48,1.18],[.405,1.18],[.405,1.08],[.34,.96],[.19,.89],[0,.89]],V(-.28,0,.63),4);bowlMesh.scale.z=.70;socket(bowl,'switchyard/bowl-seat',V(-.28,.70,.63));batch(bowl);
 const tower=(id:string,l:number,x:number,z:number,top:number,r:number)=>{
 const g=add(id,l),h=top-.24;
 // Three separately proportioned pressure castings; collars bear on occupied bodies.
 const sections=id==='left-service-tower'
 ? [[0,0],[.82,0],[.82,.07],[.62,.11],[.62,.22],[.82,.27],[.82,.37],[.70,.40],[.70,.72],[1,.76],[1,.81],[.74,.84],[.52,.89],[.28,.94],[.28,1],[0,1]]
 : id==='right-capped-vessel'
 ? [[0,0],[1,0],[1,.055],[.72,.10],[.72,.25],[.82,.28],[.82,.32],[.70,.35],[.70,.69],[.85,.72],[.85,.77],[.79,.83],[.62,.88],[.36,.91],[.22,.96],[.22,1],[0,1]]
 : [[0,0],[.92,0],[.92,.06],[.68,.10],[.68,.36],[.83,.38],[.83,.42],[.65,.44],[.65,.73],[1,.77],[1,.81],[.88,.86],[.57,.90],[.22,.94],[.22,1],[0,1]];
 profile(g,id+'_OCCUPIED_STEPPED_CASTING',sections.map(([radius,y])=>[radius*r,.24+y*h]),V(x,0,z));
 // Wide load shoes at the base, distinct from the narrow cap fittings.
 for(let i=0;i<4;i++){const a=i*Math.PI/2+.22;rod(g,id+'_BEARING_'+i,V(x+Math.sin(a)*r*.77,.28,z+Math.cos(a)*r*.77),V(x+Math.sin(a)*r*.65,.24+h*.23,z+Math.cos(a)*r*.65),r*.12,cast,4);}
 socket(g,'switchyard/'+id+'-seat',V(x,.24,z));batch(g);return g;};
 const instrument=(id:string,l:number,x:number,z:number,top:number,r:number)=>{
 const g=add(id,l),large=id==='large-front-instrument',small=id==='small-forward-instrument';
 const gaugeY=top-r*.35,shoulder=gaugeY-r*.28;
 const sections=large?[[0,.24],[r*.92,.24],[r*.92,.35],[r*.70,.43],[r*.70,shoulder-.26],[r*.91,shoulder-.19],[r*.91,shoulder],[0,shoulder]]
 : small?[[0,.24],[r*.95,.24],[r*.95,.31],[r*.72,.36],[r*.72,shoulder-.10],[r*.92,shoulder],[0,shoulder]]
 : [[0,.24],[r*.82,.24],[r*.82,.34],[r*.58,.41],[r*.58,shoulder-.18],[r*.88,shoulder-.09],[r*.88,shoulder],[0,shoulder]];
 profile(g,id+'_BEARING_PEDESTAL',sections,V(x,0,z));
 // Gauge is a thick cast lid facing upward and slightly toward the source front.
 const drum=mesh(g,id+'_OCCUPIED_DRUM',solidProfile([[0,-r*.28],[r*.87,-r*.28],[r*.95,-r*.14],[r*.95,r*.08],[r*.78,r*.08],[r*.78,-r*.035],[0,-r*.035]],n),cast,V(x,gaugeY,z),4);
 drum.rotation.x=.24;
 for(let i=0;i<4;i++){const a=i*Math.PI/2+.3;rod(g,id+'_LOAD_FOOT_'+i,V(x+Math.sin(a)*r*.75,.26,z+Math.cos(a)*r*.75),V(x+Math.sin(a)*r*.66,shoulder-.05,z+Math.cos(a)*r*.66),r*.11,cast,4);}
 socket(g,'switchyard/'+id+'-seat',V(x,.24,z));batch(g);};
 if(level>=2){
 const crown=add('layered-crown-and-neck',2);profile(crown,'BROAD_LAYERED_RECESSED_CROWN',[[0,2.72],[.31,2.72],[.36,2.80],[.47,2.86],[.52,2.93],[.52,3.02],[.44,3.09],[.405,3.16],[.405,3.48],[.48,3.52],[.51,3.59],[.51,3.67],[.44,3.74],[.26,3.74],[.26,3.61],[0,3.61]],V(.1,0,-.2),3);for(let i=0;i<8;i++){const a=i*Math.PI/4;mesh(crown,'CROWN_RECESSED_CAST_PANEL_'+i,crownSector([[.402,3.10],[.455,3.10],[.455,3.20],[.422,3.24],[.422,3.40],[.455,3.44],[.455,3.52],[.402,3.52]],a+.07,Math.PI/4-.14),cast,V(.1,0,-.2),3);}
 socket(crown,'switchyard/crown-seat',V(.1,2.72,-.2));batch(crown);
 tower('left-service-tower',2,-.95,.05,2.85,.24);tower('right-capped-vessel',2,1.01,.08,2.45,.24);instrument('left-small-instrument',2,-1.02,.48,1.35,.16);
 }
 if(level>=3){
 tower('rear-capped-vessel',3,-.73,-.67,3.75,.22);
 const ret=add('rear-tall-return',3);profile(ret,'RETURN_SUPPORTED_FOOT',[[0,.24],[.18,.24],[.18,.43],[.12,.51],[.12,1.1],[0,1.1]],V(-.43,0,-1.1));
 rod(ret,'RETURN_VERTICAL_SERVICE_BODY',V(-.43,.45,-1.1),V(-.43,4.23,-1.1),.095,cast,4);
 // Bent closed header, with its own supported vertical run; no duplicated neighboring tower.
 rod(ret,'RETURN_UPPER_BEND',V(-.43,4.20,-1.1),V(-.36,4.35,-1.1),.10,cast,4);profile(ret,'RETURN_TOP_CAP',[[0,4.30],[.105,4.30],[.105,4.45],[0,4.45]],V(-.36,0,-1.1));
 rod(ret,'RETURN_TO_CROWN_BRACKET',V(-.43,3.10,-1.1),V(.1,3.10,-.60),.065,cast,4);socket(ret,'switchyard/rear-tall-return-seat',V(-.43,.24,-1.1));batch(ret);
 instrument('large-front-instrument',3,.58,.90,1.5,.30);instrument('small-forward-instrument',3,.12,1.18,.95,.21);
 const tip=add('neutral-crown-core-tip',3);mesh(tip,'OCCUPIED_CROWN_CORE_TIP',solidProfile([[0,3.61],[.11,3.61],[.21,3.78],[.14,3.91],[0,4.10]],6),core,V(.1,0,-.2),5);batch(tip);
 const routes=[{id:'a',points:[[-.48,.85,.5],[-.9,.7,.75],[-.64,.48,1.22]]},{id:'b',points:[[.44,.7,.5],[.75,.48,.92],[.48,.38,1.27]]}];root.userData.networkPorts=[];
 for(const route of routes){const g=add('factory-conduit-'+route.id,3),p=route.points.map(a=>V(a[0],a[1],a[2]));
 // Fully occupied segmented casting bends, closed at joins; the external run begins at the terminal face.
 for(let i=0;i<p.length-1;i++)rod(g,'CONDUIT_'+route.id+'_SEGMENT_'+i,p[i],p[i+1],.095,cast,4);
 mesh(g,'CONDUIT_'+route.id+'_CAST_ELBOW',new THREE.SphereGeometry(.103,16,10),cast,p[1],4);
 const tangent=p[2].clone().sub(p[1]).normalize();rod(g,'CONDUIT_'+route.id+'_TERMINAL_COLLAR',p[2].clone().addScaledVector(tangent,-.12),p[2],.13,cast,4);
 rod(g,'CONDUIT_'+route.id+'_BODY_COUPLING',p[0],p[0].clone().lerp(p[1],.18),.13,cast,4);
 rod(g,'CONDUIT_'+route.id+'_FOOT',V(p[1].x,.24,p[1].z),p[1],.085,cast,4);
 const port=socket(g,'seismic-switchyard/network-'+route.id+'-out',p[2]);port.userData.direction=tangent.toArray();root.userData.networkPorts.push({name:port.name,position:p[2].toArray(),direction:tangent.toArray()});batch(g);
 }
 }
 root.userData.interfaceContacts=[['switchyard/chamber-seat','occupied-ovoid-chamber/bottom'],...(level>=2?[['occupied-ovoid-chamber/top','switchyard/crown-seat']]:[])];return root;
}
