import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import type { Island3DQuality, Island5LandmarkDefinition } from './island5ThreePilotContract';
import type { Island9HeartshaftMaterials } from './Island9HeartshaftThreeWorld';
import type { IslandConstructionFactoryOptions } from './IslandConstructionAuthoring';

/** Unwired family13/r04 tapering pressure-crown refinement. Source projection is not world calibration. */
export const BLASTGLASS_SOURCE_PROFILE = {
  family: 'occupied-unequal-ovoid-incubator', globalFamily: 13, unitFamily: 1,
  source: 'docs/visual-references/island-009-heartshaft-crucible/009-source.png',
  crop: 'docs/visual-references/island-009-heartshaft-crucible/derived-crops/blastglass-incubator-exact-v001.png',
  cropPixelsXYXY: [0, 35, 330, 510], anchorUncertaintyNormalized: .04,
  projected: { chimney: [.43,.08], upper: [.49,.40], waist: [.51,.50], lower: [.52,.59], rightFlue: [.75,.26], frontEntry: [.37,.78], rightEntry: [.74,.73] },
  inference: 'Hidden closed cross-sections, scalloped occupied contents, six unequal-angle ribs and concealed pipe joints are inferred; no creature anatomy or calibrated world dimensions claimed.',
  allocation: { lower: { bottom: 1.12, top: 2.38, radius: .68 }, upper: { bottom: 2.48, top: 3.64, radius: .62 }, height: 4.76 },
  receiving: { bottom: -.05, lowerRadius: 1.43, top: .21, upperRadius: 1.35, segments: 16 },
  footprintRadius: 1.53, yaw: 0,
};
type Phase = 1 | 2 | 3 | 4 | 5;
const V = (x: number, y: number, z: number) => new THREE.Vector3(x,y,z);
function owner(id: string, level: number) {
  const g = new THREE.Group(); g.name = id; g.userData = { partId:id, constructionBuildLevel:level, keepSeparate:true, sculptRuntime:{parts:[{id,nodeName:id}],sockets:{},presentationOnly:true} }; return g;
}
function socket(g: THREE.Group, name: string, p: THREE.Vector3) {
  const n = new THREE.Object3D(); n.name=name;n.position.copy(p);n.userData.socket=true;g.add(n);g.userData.sculptRuntime.sockets[name]={nodeName:name,localPosition:p.toArray()};return n;
}
function mesh(g: THREE.Group,name:string,geometry:THREE.BufferGeometry,material:THREE.Material,at=V(0,0,0),phase:Phase=2) {
  const n=new THREE.Mesh(geometry,material);n.name=name;n.position.copy(at);n.castShadow=n.receiveShadow=true;
  n.userData={partId:g.userData.partId,constructionBuildLevel:g.userData.constructionBuildLevel,constructionStage:phase,constructionPreserveOwnership:true};g.add(n);return n;
}
function solidProfile(points:number[][],n:number) {
  const strips=points.slice(1).map((b,i)=>{
    const a=points[i],g=new THREE.LatheGeometry([new THREE.Vector2(a[0],a[1]),new THREE.Vector2(b[0],b[1])],n);
    const normal=g.getAttribute('normal'),dy=b[1]-a[1],dr=b[0]-a[0],length=Math.hypot(dy,dr);
    for(let j=0;j<=n;j++)for(let k=0;k<2;k++)normal.setXYZ(j*2+k,Math.sin(j/n*Math.PI*2)*dy/length,-dr/length,Math.cos(j/n*Math.PI*2)*dy/length);
    return g;
  });
  const merged=mergeGeometries(strips,false)!;strips.forEach(g=>g.dispose());
  // Remove only the zero-area pole triangles generated by standard lathe caps.
  const pos=merged.getAttribute('position'),idx=merged.index!,indices:number[]=[];
  for(let i=0;i<idx.count;i+=3){const ids=[idx.getX(i),idx.getX(i+1),idx.getX(i+2)],v=ids.map(j=>new THREE.Vector3().fromBufferAttribute(pos,j));if(v[1].sub(v[0]).cross(v[2].sub(v[0])).lengthSq()>1e-18)indices.push(...ids);}
  merged.setIndex(indices);return merged;
}
function collar(g:THREE.Group,name:string,r:number,inner:number,y:number,h:number,m:THREE.Material,n:number) {
  return mesh(g,name,solidProfile([[inner,y-h/2],[r,y-h/2],[r,y+h/2],[inner,y+h/2],[inner,y-h/2]],n),m,V(0,0,0),3);
}
function rod(g:THREE.Group,name:string,a:THREE.Vector3,b:THREE.Vector3,r:number,m:THREE.Material,phase:Phase=3){const d=b.clone().sub(a),n=mesh(g,name,new THREE.CylinderGeometry(r,r,d.length(),10),m,a.clone().lerp(b,.5),phase);n.quaternion.setFromUnitVectors(V(0,1,0),d.normalize());return n;}
function pipe(g:THREE.Group,name:string,points:THREE.Vector3[],r:number,m:THREE.Material,n:number){return mesh(g,name,new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,false,'centripetal'),n,r,10,false),m,V(0,0,0),4);}
function batch(g:THREE.Group){
  const sets=new Map<string,THREE.Mesh[]>();for(const n of g.children)if(n instanceof THREE.Mesh && !n.name.startsWith('INCUBATOR_RECESSED_PRESSURE_NECK_')){const key=(n.material as THREE.Material).uuid+':'+n.userData.constructionStage;const a=sets.get(key)??[];a.push(n);sets.set(key,a);}
  for(const nodes of sets.values()){if(nodes.length<2)continue;const inputs=nodes.map(n=>{n.updateMatrix();const a=n.geometry.index?n.geometry.toNonIndexed():n.geometry.clone();a.applyMatrix4(n.matrix);return a;});const geo=mergeGeometries(inputs,false);inputs.forEach(g=>g.dispose());if(!geo)throw Error('Incubator batch attributes incompatible');const n=mesh(g,g.name+'_PHASE_'+nodes[0].userData.constructionStage,geo,nodes[0].material as THREE.Material,V(0,0,0),nodes[0].userData.constructionStage);n.userData.sourceMeshes=nodes.map(n=>n.name);nodes.forEach(n=>{g.remove(n);n.geometry.dispose();});}
}
/** Closed lobed pressure contents, with real recessed valleys rather than primitive spheres. */
function contents(bottom:number,top:number,radius:number,segments:number,rows:number,offset:number){
  const pos:number[]=[],idx:number[]=[];
  for(let j=0;j<=rows;j++){const t=j/rows,shape=.34+.66*Math.pow(Math.sin(Math.PI*t),.64);for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2;const ridge=Math.pow(.5+.5*Math.cos(6*a+offset),2.4);const lobe=1-.34*(1-ridge)*Math.sin(Math.PI*t);const r=radius*shape*lobe;pos.push(Math.sin(a)*r+.025*Math.sin(Math.PI*t)*Math.sin(offset),bottom+(top-bottom)*(t+.08*Math.sin(3*a+offset)*t*(1-t)),Math.cos(a)*r*.92);}}
  for(let j=0;j<rows;j++)for(let i=0;i<segments;i++){const k=(i+1)%segments,a=j*segments+i,b=j*segments+k,c=(j+1)*segments+i,d=(j+1)*segments+k;idx.push(a,c,b,b,c,d);}
  for(const end of [0,rows]){const center=pos.length/3;pos.push(0,end?top:bottom,0);for(let i=0;i<segments;i++){const a=end*segments+i,b=end*segments+(i+1)%segments;idx.push(...(end?[center,b,a]:[center,a,b]));}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx.flatMap((_,i)=>i%3===0?[idx[i],idx[i+2],idx[i+1]]:[]));g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(pos.length/3*2).fill(0),2));return g;
}
function crownSector(points:number[][],start:number,width:number){
 const vertices:number[]=[],indices:number[]=[],count=points.length;
 for(const angle of [start,start+width])for(const [r,y]of points)vertices.push(Math.sin(angle)*r,y,Math.cos(angle)*r);
 for(let i=0;i<count;i++){const j=(i+1)%count;indices.push(i,j,count+i,j,count+j,count+i);}
 const faces=THREE.ShapeUtils.triangulateShape(points.map(([r,y])=>new THREE.Vector2(r,y)),[]);
 for(const [a,b,c]of faces)indices.push(a,c,b,count+a,count+b,count+c);
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices.flatMap((_,i)=>i%3===0?[indices[i],indices[i+2],indices[i+1]]:[]));g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(vertices.length/3*2).fill(0),2));return g;
}
function chamber(root:THREE.Group,id:string,level:number,bottom:number,top:number,radius:number,cast:THREE.Material,core:THREE.Material,n:number){
  const g=owner(id,level);root.add(g);g.userData.chamber={bottom,top,radius,occupied:true};
  mesh(g,id+'_OCCUPIED_SCALLOPED_ENVELOPE',contents(bottom,top,radius-.055,n,12,level*.67),core);
  mesh(g,id+'_LOWER_STEPPED_BEARING',solidProfile([[.17,bottom-.06],[.39,bottom-.06],[.44,bottom],[.44,bottom+.075],[.37,bottom+.13],[.17,bottom+.13],[.17,bottom-.06]],n),cast,V(0,0,0),3);mesh(g,id+'_UPPER_STEPPED_BEARING',solidProfile([[.17,top-.13],[.37,top-.13],[.42,top-.065],[.42,top+.02],[.36,top+.06],[.17,top+.06],[.17,top-.13]],n),cast,V(0,0,0),3);
  const angles=[.12,1.04,2.03,3.12,4.17,5.20];const contacts:{rib:number;end:string;point:number[];receiverRadius:number[]}[]=[];
  angles.forEach((a,i)=>{
    const points=[0,.15,.35,.55,.77,1].map(t=>{const r=.30+(radius-.30)*Math.pow(Math.sin(Math.PI*t),.82);return V(Math.sin(a)*r,bottom+(top-bottom)*t,Math.cos(a)*r);});
    const curve=new THREE.CatmullRomCurve3(points,false,'centripetal'),vertices:number[]=[],indices:number[]=[],steps=20;
    for(let j=0;j<=steps;j++){const t=j/steps,p=curve.getPoint(t),radial=V(Math.sin(a),0,Math.cos(a)),side=V(Math.cos(a),0,-Math.sin(a)),width=.068+.030*Math.pow(Math.abs(t-.5)*2,2);
      for(const [w,d] of [[-width,-.035],[width,-.035],[width,.035],[-width,.035]])vertices.push(...p.clone().addScaledVector(side,w).addScaledVector(radial,d).toArray());}
    for(let j=0;j<steps;j++)for(let k=0;k<4;k++){const l=(k+1)%4,A=j*4+k,B=j*4+l,C=(j+1)*4+k,D=(j+1)*4+l;indices.push(A,B,C,B,D,C);}indices.push(0,2,1,0,3,2);const e=steps*4;indices.push(e,e+1,e+2,e,e+2,e+3);
    const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setIndex(indices.flatMap((_,i)=>i%3===0?[indices[i],indices[i+2],indices[i+1]]:[]));geo.computeVertexNormals();geo.setAttribute('uv',new THREE.Float32BufferAttribute(new Array(vertices.length/3*2).fill(0),2));mesh(g,id+'_BOWED_LOAD_RIB_'+i,geo,cast,V(0,0,0),3);
    for(const [end,p]of [['lower',points[0]],['upper',points[points.length-1]]] as const){socket(g,id+'/rib-'+i+'-'+end,p);contacts.push({rib:i,end,point:p.toArray(),receiverRadius:[.17,end==='lower'?.39:.36]});}
  });
  socket(g,id+'/bottom',V(0,bottom,0));socket(g,id+'/top',V(0,top,0));g.userData.ribContacts=contacts;batch(g);return g;
}
export function buildIsland9BlastglassIncubatorStructure(definition:Island5LandmarkDefinition,level:0|1|2|3,quality:Island3DQuality,_materials:Island9HeartshaftMaterials,_options:IslandConstructionFactoryOptions={}){
  const root=owner('blastglass-incubator-structural-assembly',0);root.name='ISLAND_9_HEARTSHAFT_HATCHERY_ROOT';root.position.set(...definition.position);root.userData.family=BLASTGLASS_SOURCE_PROFILE.family;root.userData.authoringProfile=BLASTGLASS_SOURCE_PROFILE;root.userData.footprintRadius=1.53;root.userData.approval='unreviewed';root.userData.constructionPreviewImplemented=false;
  socket(root,'ISLAND_9_HATCHERY_FOCUS_SOCKET',V(0,1.5,0));
  const mat=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:.82,metalness:0});const stone=mat(0x747b7e),cast=mat(0xa0a5a7),core=mat(0x626c72);const n=quality==='high'?40:quality==='medium'?32:24;
  const base=owner('incubator-foundation',0);root.add(base);mesh(base,'INCUBATOR_FROZEN_RECEIVING_FOOTPRINT',new THREE.CylinderGeometry(1.35,1.43,.26,16),stone,V(0,.08,0),1);socket(base,'incubator/foundation-seat',V(0,.21,0));batch(base);if(!level)return root;
  const basement=owner('incubator-supported-basement',1);root.add(basement);
  mesh(basement,'OCCUPIED_FACETED_BASEMENT',solidProfile([[0,.21],[.79,.21],[.84,.30],[.68,.40],[.63,.78],[.57,.99],[.35,1.12],[0,1.12]],12),cast);
  // Broad cast load fingers articulate the basement wall and transfer chamber load to its foot.
  for(const a of [.70,2.22,2.95,3.69,5.20,5.72]){
    const shape=new THREE.Shape();shape.moveTo(.64,.22);shape.lineTo(.84,.22);shape.lineTo(.81,.39);shape.lineTo(.71,.77);shape.lineTo(.42,1.12);shape.lineTo(.29,1.12);shape.lineTo(.54,.74);shape.closePath();
    const geo=new THREE.ExtrudeGeometry(shape,{depth:.14,bevelEnabled:false});geo.translate(0,0,-.07);geo.setIndex(Array.from({length:geo.getAttribute('position').count},(_,i)=>i));
    const finger=mesh(basement,'INCUBATOR_BASEMENT_CAST_LOAD_FINGER_'+a,geo,cast,V(0,0,0),2);finger.rotation.y=a;
  }
  for(const [yaw,label]of [[0,'front'],[Math.PI/2,'right']] as const){
    const access=owner('incubator-'+label+'-access',1);access.rotation.y=yaw;basement.add(access);
    for(let i=0;i<5;i++){const h=.07*(i+1);mesh(access,'INCUBATOR_'+label+'_TREAD_'+i,new THREE.BoxGeometry(.34,h,.10),stone,V(-.20,.21+h/2,1.27-i*.10),2);}
    // Recessed service mouth is an occupied inset with substantial arched rim.
    const shape=new THREE.Shape();shape.moveTo(-.24,0);shape.lineTo(.24,0);shape.lineTo(.24,.30);shape.quadraticCurveTo(.24,.51,0,.56);shape.quadraticCurveTo(-.24,.51,-.24,.30);shape.closePath();
    const hole=new THREE.Path();hole.moveTo(-.14,.03);hole.lineTo(-.14,.28);hole.quadraticCurveTo(0,.53,.14,.28);hole.lineTo(.14,.03);hole.closePath();shape.holes.push(hole);
    mesh(access,'INCUBATOR_'+label+'_SERVICE_ARCH',new THREE.ExtrudeGeometry(shape,{depth:.13,bevelEnabled:false,curveSegments:8}),cast,V(-.20,.53,.79),2);
    mesh(access,'INCUBATOR_'+label+'_RECESSED_BACK',new THREE.BoxGeometry(.27,.37,.07),core,V(-.20,.735,.785),2);
    mesh(access,'INCUBATOR_'+label+'_LANDING',new THREE.BoxGeometry(.34,.35,.14),stone,V(-.20,.385,.80),2);socket(access,'incubator/'+label+'-entry',V(-.20,.56,.80));batch(access);
  }
  socket(basement,'incubator/lower-receiver',V(0,1.12,0));batch(basement);
  chamber(root,'incubator-lower-ovoid',1,1.12,2.38,.68,cast,core,n);
  const waist=owner('incubator-pinched-waist',1);root.add(waist);mesh(waist,'INCUBATOR_WAIST_TRANSFER',solidProfile([[.17,2.22],[.34,2.22],[.42,2.30],[.46,2.34],[.46,2.40],[.35,2.43],[.35,2.49],[.44,2.52],[.44,2.57],[.34,2.64],[.17,2.64],[.17,2.22]],n),cast,V(0,0,0),3);socket(waist,'incubator/upper-receiver',V(0,2.48,0));batch(waist);
  if(level>=2){
    chamber(root,'incubator-upper-ovoid',2,2.48,3.64,.62,cast,core,n);
    const crown=owner('incubator-stepped-crown',2);root.add(crown);
    // Exact-source taper/retainer interpretation; hidden eight-fold arrangement inferred.
    // Retainers overlap the occupied neck by .017-.02 radially and stay separately auditable.

    mesh(crown,'INCUBATOR_OCCUPIED_CROWN_SHOULDER',solidProfile([[.15,3.60],[.38,3.60],[.49,3.70],[.51,3.75],[.51,3.81],[.44,3.88],[.365,4.02],[.29,4.17],[.23,4.30],[.19,4.36],[.15,4.36],[.15,3.60]],n),cast,V(0,0,0),3);
    for(let i=0;i<8;i++)mesh(crown,'INCUBATOR_RECESSED_PRESSURE_NECK_'+i,crownSector([[.47,3.74],[.54,3.74],[.54,3.81],[.48,3.89],[.397,4.03],[.32,4.18],[.25,4.30],[.213,4.30],[.27,4.17],[.345,4.02],[.42,3.88],[.49,3.81]],i*Math.PI/4+.27,Math.PI/4-.54),cast,V(0,0,0),3);
    mesh(crown,'INCUBATOR_OPEN_SHORT_FLUE',solidProfile([[.13,4.30],[.20,4.30],[.18,4.61],[.23,4.70],[.23,4.76],[.15,4.76],[.13,4.64],[.13,4.30]],n),cast,V(0,0,0),4);
    socket(crown,'incubator/crown-seat',V(0,3.64,0));socket(crown,'incubator/open-flue',V(0,4.76,0));batch(crown);
  }
  if(level>=3){
    const service=owner('incubator-asymmetric-service-system',3);root.add(service);
    // Occupied unequal right service body and separate tall flue; no mirrored twin.
    mesh(service,'INCUBATOR_RIGHT_SERVICE_BODY',solidProfile([[0,.21],[.26,.21],[.29,.32],[.24,1.06],[.18,1.20],[0,1.20]],12),cast,V(.98,0,-.10),2);
    const right=[V(.98,1.13,-.10),V(1.13,1.39,-.10),V(1.10,1.70,-.12),V(.96,1.92,-.13),V(.93,3.43,-.13)];pipe(service,'INCUBATOR_UNEQUAL_RIGHT_FLUE',right,.105,cast,n);
    mesh(service,'INCUBATOR_RIGHT_OPEN_MOUTH',solidProfile([[.075,3.37],[.14,3.37],[.14,3.50],[.075,3.50],[.075,3.37]],n),cast,V(.93,0,-.13),4);
    const left=[V(-.35,3.90,-.10),V(-.69,3.72,-.10),V(-.94,3.44,-.10),V(-.98,2.82,-.10),V(-.86,2.30,-.10),V(-.74,1.08,-.10)];pipe(service,'INCUBATOR_LEFT_SHOULDER_RETURN',left,.105,cast,n);
    mesh(service,'INCUBATOR_LEFT_LOWER_SERVICE_VESSEL',solidProfile([[0,.21],[.18,.21],[.21,.32],[.17,1.16],[.12,1.34],[0,1.34]],12),cast,V(-1.02,0,.34),2);
    pipe(service,'INCUBATOR_LOWER_BENT_FEED',[V(-1.02,.48,.34),V(-1.06,.65,.64),V(-.70,.80,.59),V(-.58,.72,.25)],.08,cast,n);
    // Real short brackets connect unequal pipes to the collar/crown castings.
    rod(service,'INCUBATOR_RIGHT_COLLAR_BRACKET',V(.31,2.43,-.13),V(.94,2.43,-.13),.055,cast);
    rod(service,'INCUBATOR_LEFT_WAIST_BRACKET',V(-.31,2.43,-.10),V(-.89,2.43,-.10),.055,cast);
    rod(service,'INCUBATOR_LEFT_RETURN_RECEIVER',V(-.32,1.08,-.10),V(-.78,1.08,-.10),.13,cast,2);
    rod(service,'INCUBATOR_LEFT_CROWN_PORT',V(-.30,3.90,-.10),V(-.45,3.90,-.10),.13,cast);
    for(const [name,p]of [['right-flue-foot',right[0]],['left-crown-port',left[0]],['left-return-foot',left[left.length-1]]] as const)socket(service,'incubator/'+name,p);
    service.userData.contactProbes=[{name:'right-flue-foot',point:right[0].toArray(),target:'INCUBATOR_RIGHT_SERVICE_BODY'},{name:'left-crown-port',point:left[0].toArray(),target:'incubator-stepped-crown'},{name:'left-return-foot',point:left[left.length-1].toArray(),target:'incubator-supported-basement'}];batch(service);
  }
  root.userData.interfaceContacts=[['incubator/lower-receiver','incubator-lower-ovoid/bottom'],...(level>=2?[['incubator/upper-receiver','incubator-upper-ovoid/bottom'],['incubator-upper-ovoid/top','incubator/crown-seat']]:[])];return root;
}
