import { createIsland22PremiumFishMarketHall } from '../features/gamification/level-worlds/dev/Island22PremiumLandmarkFamilies';
import * as THREE from 'three';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { buildIsland22FishermansVillageLandmark, createIsland22FishermansVillageMaterials, createIsland22NorthCottage, createIsland22NetMenderCottage, createIsland22SmokehouseCottage, createIsland22SecondaryCottage } from '../features/gamification/level-worlds/dev/Island22FishermansVillageThreeWorld';
import { ISLAND_5_LANDMARKS, type Island3DQuality } from '../features/gamification/level-worlds/dev/island5ThreePilotContract';
const params=new URLSearchParams(location.search);
const quality=(params.get('quality')||'medium') as Island3DQuality;
const isMarket=params.get('building')==='market';
const isCottage=params.get('building')==='cottage-01';
const isMender=params.get('building')==='cottage-02';
const isSmoke=params.get('building')==='cottage-03';
const secondaryIndex=Number(params.get('building')?.match(/^cottage-(\d+)$/)?.[1]||0)-1;
const isSecondary=[3,4,6,7,8,9,10,11].includes(secondaryIndex);
const secondaryTall=[4,6,8,10].includes(secondaryIndex);
const definition=ISLAND_5_LANDMARKS.find(d=>d.id===(isMarket||isCottage||isMender||isSmoke||isSecondary?'habit':params.get('building')||'habit'))!;
const level=Number(params.get('level')||3) as 1|2|3;
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
document.body.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc5d5d6);
const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.1);scene.environment=environment.texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xfff1d8,0x546c74,1.4));
const sun=new THREE.DirectionalLight(0xffe7c0,3);sun.position.set(-4,9,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:1,far:25});sun.shadow.bias=-.0004;sun.shadow.normalBias=.025;scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0xa8b7b6,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=isSecondary?([3,4].includes(secondaryIndex)?-1.03:-.34):isSmoke?-.34:isMender?-.34:isCottage?-.34:isMarket?-.8:definition.id==='boss'?-1.175:-.025;floor.receiveShadow=true;scene.add(floor);
const root=isSecondary?createIsland22SecondaryCottage(secondaryIndex,quality,createIsland22FishermansVillageMaterials()):isSmoke?createIsland22SmokehouseCottage(quality,createIsland22FishermansVillageMaterials()):isMender?createIsland22NetMenderCottage(quality,createIsland22FishermansVillageMaterials()):isCottage?createIsland22NorthCottage(quality,createIsland22FishermansVillageMaterials()):isMarket?createIsland22PremiumFishMarketHall({level,quality,materials:createIsland22FishermansVillageMaterials()}):buildIsland22FishermansVillageLandmark(definition,level,quality,createIsland22FishermansVillageMaterials());root.position.set(0,0,0);root.rotation.set(0,0,0);scene.add(root);
if(params.get('clay')==='1'){const clay=new THREE.MeshStandardMaterial({color:0xb6aba0,roughness:.85});const doubleShadowClay=clay.clone();doubleShadowClay.shadowSide=THREE.DoubleSide;root.traverse(o=>{if(o instanceof THREE.Mesh){const original=Array.isArray(o.material)?o.material[0]:o.material;o.material=original.shadowSide===THREE.DoubleSide?doubleShadowClay:clay;}});}
const targetY=isSecondary?(secondaryTall?1.35:1.05):isSmoke?1.35:isMender?.95:isCottage?1.3:definition.id==='boss'?2.0:definition.id==='wisdom'?2.6:1.15;
const halfHeight=isSecondary?(secondaryTall?2.5:2.1):isSmoke?2.5:isMender?1.9:isCottage?2.5:definition.id==='boss'?4.4:definition.id==='wisdom'?4:3.3;
const camera=new THREE.OrthographicCamera(-halfHeight*innerWidth/innerHeight,halfHeight*innerWidth/innerHeight,halfHeight,-halfHeight,.1,100);
const angle=THREE.MathUtils.degToRad(Number(params.get('azimuth')||35));const elevation=THREE.MathUtils.degToRad(Number(params.get('elevation')||25));
camera.position.set(Math.sin(angle)*10*Math.cos(elevation),targetY+Math.sin(elevation)*10,Math.cos(angle)*10*Math.cos(elevation));camera.lookAt(0,targetY,0);renderer.render(scene,camera);
document.body.dataset.ready='true';document.body.dataset.calls=String(renderer.info.render.calls);document.body.dataset.triangles=String(renderer.info.render.triangles);document.body.dataset.camera=JSON.stringify({position:camera.position.toArray(),target:[0,targetY,0],orthographic:[camera.left,camera.right,camera.top,camera.bottom]});
